// Code generated by ent, DO NOT EDIT.

package syncjob

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/IanShaw027/sub2api-plugin-market/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldLTE(FieldID, id))
}

// PluginID applies equality check predicate on the "plugin_id" field. It's identical to PluginIDEQ.
func PluginID(v uuid.UUID) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEQ(FieldPluginID, v))
}

// TargetRef applies equality check predicate on the "target_ref" field. It's identical to TargetRefEQ.
func TargetRef(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEQ(FieldTargetRef, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEQ(FieldErrorMessage, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEQ(FieldStartedAt, v))
}

// FinishedAt applies equality check predicate on the "finished_at" field. It's identical to FinishedAtEQ.
func FinishedAt(v time.Time) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEQ(FieldFinishedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEQ(FieldUpdatedAt, v))
}

// PluginIDEQ applies the EQ predicate on the "plugin_id" field.
func PluginIDEQ(v uuid.UUID) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEQ(FieldPluginID, v))
}

// PluginIDNEQ applies the NEQ predicate on the "plugin_id" field.
func PluginIDNEQ(v uuid.UUID) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNEQ(FieldPluginID, v))
}

// PluginIDIn applies the In predicate on the "plugin_id" field.
func PluginIDIn(vs ...uuid.UUID) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldIn(FieldPluginID, vs...))
}

// PluginIDNotIn applies the NotIn predicate on the "plugin_id" field.
func PluginIDNotIn(vs ...uuid.UUID) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNotIn(FieldPluginID, vs...))
}

// TriggerTypeEQ applies the EQ predicate on the "trigger_type" field.
func TriggerTypeEQ(v TriggerType) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEQ(FieldTriggerType, v))
}

// TriggerTypeNEQ applies the NEQ predicate on the "trigger_type" field.
func TriggerTypeNEQ(v TriggerType) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNEQ(FieldTriggerType, v))
}

// TriggerTypeIn applies the In predicate on the "trigger_type" field.
func TriggerTypeIn(vs ...TriggerType) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldIn(FieldTriggerType, vs...))
}

// TriggerTypeNotIn applies the NotIn predicate on the "trigger_type" field.
func TriggerTypeNotIn(vs ...TriggerType) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNotIn(FieldTriggerType, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNotIn(FieldStatus, vs...))
}

// TargetRefEQ applies the EQ predicate on the "target_ref" field.
func TargetRefEQ(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEQ(FieldTargetRef, v))
}

// TargetRefNEQ applies the NEQ predicate on the "target_ref" field.
func TargetRefNEQ(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNEQ(FieldTargetRef, v))
}

// TargetRefIn applies the In predicate on the "target_ref" field.
func TargetRefIn(vs ...string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldIn(FieldTargetRef, vs...))
}

// TargetRefNotIn applies the NotIn predicate on the "target_ref" field.
func TargetRefNotIn(vs ...string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNotIn(FieldTargetRef, vs...))
}

// TargetRefGT applies the GT predicate on the "target_ref" field.
func TargetRefGT(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldGT(FieldTargetRef, v))
}

// TargetRefGTE applies the GTE predicate on the "target_ref" field.
func TargetRefGTE(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldGTE(FieldTargetRef, v))
}

// TargetRefLT applies the LT predicate on the "target_ref" field.
func TargetRefLT(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldLT(FieldTargetRef, v))
}

// TargetRefLTE applies the LTE predicate on the "target_ref" field.
func TargetRefLTE(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldLTE(FieldTargetRef, v))
}

// TargetRefContains applies the Contains predicate on the "target_ref" field.
func TargetRefContains(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldContains(FieldTargetRef, v))
}

// TargetRefHasPrefix applies the HasPrefix predicate on the "target_ref" field.
func TargetRefHasPrefix(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldHasPrefix(FieldTargetRef, v))
}

// TargetRefHasSuffix applies the HasSuffix predicate on the "target_ref" field.
func TargetRefHasSuffix(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldHasSuffix(FieldTargetRef, v))
}

// TargetRefIsNil applies the IsNil predicate on the "target_ref" field.
func TargetRefIsNil() predicate.SyncJob {
	return predicate.SyncJob(sql.FieldIsNull(FieldTargetRef))
}

// TargetRefNotNil applies the NotNil predicate on the "target_ref" field.
func TargetRefNotNil() predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNotNull(FieldTargetRef))
}

// TargetRefEqualFold applies the EqualFold predicate on the "target_ref" field.
func TargetRefEqualFold(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEqualFold(FieldTargetRef, v))
}

// TargetRefContainsFold applies the ContainsFold predicate on the "target_ref" field.
func TargetRefContainsFold(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldContainsFold(FieldTargetRef, v))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.SyncJob {
	return predicate.SyncJob(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldContainsFold(FieldErrorMessage, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldLTE(FieldStartedAt, v))
}

// StartedAtIsNil applies the IsNil predicate on the "started_at" field.
func StartedAtIsNil() predicate.SyncJob {
	return predicate.SyncJob(sql.FieldIsNull(FieldStartedAt))
}

// StartedAtNotNil applies the NotNil predicate on the "started_at" field.
func StartedAtNotNil() predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNotNull(FieldStartedAt))
}

// FinishedAtEQ applies the EQ predicate on the "finished_at" field.
func FinishedAtEQ(v time.Time) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEQ(FieldFinishedAt, v))
}

// FinishedAtNEQ applies the NEQ predicate on the "finished_at" field.
func FinishedAtNEQ(v time.Time) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNEQ(FieldFinishedAt, v))
}

// FinishedAtIn applies the In predicate on the "finished_at" field.
func FinishedAtIn(vs ...time.Time) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldIn(FieldFinishedAt, vs...))
}

// FinishedAtNotIn applies the NotIn predicate on the "finished_at" field.
func FinishedAtNotIn(vs ...time.Time) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNotIn(FieldFinishedAt, vs...))
}

// FinishedAtGT applies the GT predicate on the "finished_at" field.
func FinishedAtGT(v time.Time) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldGT(FieldFinishedAt, v))
}

// FinishedAtGTE applies the GTE predicate on the "finished_at" field.
func FinishedAtGTE(v time.Time) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldGTE(FieldFinishedAt, v))
}

// FinishedAtLT applies the LT predicate on the "finished_at" field.
func FinishedAtLT(v time.Time) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldLT(FieldFinishedAt, v))
}

// FinishedAtLTE applies the LTE predicate on the "finished_at" field.
func FinishedAtLTE(v time.Time) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldLTE(FieldFinishedAt, v))
}

// FinishedAtIsNil applies the IsNil predicate on the "finished_at" field.
func FinishedAtIsNil() predicate.SyncJob {
	return predicate.SyncJob(sql.FieldIsNull(FieldFinishedAt))
}

// FinishedAtNotNil applies the NotNil predicate on the "finished_at" field.
func FinishedAtNotNil() predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNotNull(FieldFinishedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasPlugin applies the HasEdge predicate on the "plugin" edge.
func HasPlugin() predicate.SyncJob {
	return predicate.SyncJob(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PluginTable, PluginColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPluginWith applies the HasEdge predicate on the "plugin" edge with a given conditions (other predicates).
func HasPluginWith(preds ...predicate.Plugin) predicate.SyncJob {
	return predicate.SyncJob(func(s *sql.Selector) {
		step := newPluginStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SyncJob) predicate.SyncJob {
	return predicate.SyncJob(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SyncJob) predicate.SyncJob {
	return predicate.SyncJob(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SyncJob) predicate.SyncJob {
	return predicate.SyncJob(sql.NotPredicates(p))
}
