// Code generated by ent, DO NOT EDIT.

package submission

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/IanShaw027/sub2api-plugin-market/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Submission {
	return predicate.Submission(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Submission {
	return predicate.Submission(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Submission {
	return predicate.Submission(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Submission {
	return predicate.Submission(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Submission {
	return predicate.Submission(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Submission {
	return predicate.Submission(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Submission {
	return predicate.Submission(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Submission {
	return predicate.Submission(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Submission {
	return predicate.Submission(sql.FieldLTE(FieldID, id))
}

// PluginID applies equality check predicate on the "plugin_id" field. It's identical to PluginIDEQ.
func PluginID(v uuid.UUID) predicate.Submission {
	return predicate.Submission(sql.FieldEQ(FieldPluginID, v))
}

// SubmitterEmail applies equality check predicate on the "submitter_email" field. It's identical to SubmitterEmailEQ.
func SubmitterEmail(v string) predicate.Submission {
	return predicate.Submission(sql.FieldEQ(FieldSubmitterEmail, v))
}

// SubmitterName applies equality check predicate on the "submitter_name" field. It's identical to SubmitterNameEQ.
func SubmitterName(v string) predicate.Submission {
	return predicate.Submission(sql.FieldEQ(FieldSubmitterName, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.Submission {
	return predicate.Submission(sql.FieldEQ(FieldNotes, v))
}

// GithubRepoURL applies equality check predicate on the "github_repo_url" field. It's identical to GithubRepoURLEQ.
func GithubRepoURL(v string) predicate.Submission {
	return predicate.Submission(sql.FieldEQ(FieldGithubRepoURL, v))
}

// AutoUpgradeEnabled applies equality check predicate on the "auto_upgrade_enabled" field. It's identical to AutoUpgradeEnabledEQ.
func AutoUpgradeEnabled(v bool) predicate.Submission {
	return predicate.Submission(sql.FieldEQ(FieldAutoUpgradeEnabled, v))
}

// ReviewerNotes applies equality check predicate on the "reviewer_notes" field. It's identical to ReviewerNotesEQ.
func ReviewerNotes(v string) predicate.Submission {
	return predicate.Submission(sql.FieldEQ(FieldReviewerNotes, v))
}

// ReviewedBy applies equality check predicate on the "reviewed_by" field. It's identical to ReviewedByEQ.
func ReviewedBy(v string) predicate.Submission {
	return predicate.Submission(sql.FieldEQ(FieldReviewedBy, v))
}

// ReviewedAt applies equality check predicate on the "reviewed_at" field. It's identical to ReviewedAtEQ.
func ReviewedAt(v time.Time) predicate.Submission {
	return predicate.Submission(sql.FieldEQ(FieldReviewedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Submission {
	return predicate.Submission(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Submission {
	return predicate.Submission(sql.FieldEQ(FieldUpdatedAt, v))
}

// PluginIDEQ applies the EQ predicate on the "plugin_id" field.
func PluginIDEQ(v uuid.UUID) predicate.Submission {
	return predicate.Submission(sql.FieldEQ(FieldPluginID, v))
}

// PluginIDNEQ applies the NEQ predicate on the "plugin_id" field.
func PluginIDNEQ(v uuid.UUID) predicate.Submission {
	return predicate.Submission(sql.FieldNEQ(FieldPluginID, v))
}

// PluginIDIn applies the In predicate on the "plugin_id" field.
func PluginIDIn(vs ...uuid.UUID) predicate.Submission {
	return predicate.Submission(sql.FieldIn(FieldPluginID, vs...))
}

// PluginIDNotIn applies the NotIn predicate on the "plugin_id" field.
func PluginIDNotIn(vs ...uuid.UUID) predicate.Submission {
	return predicate.Submission(sql.FieldNotIn(FieldPluginID, vs...))
}

// SubmissionTypeEQ applies the EQ predicate on the "submission_type" field.
func SubmissionTypeEQ(v SubmissionType) predicate.Submission {
	return predicate.Submission(sql.FieldEQ(FieldSubmissionType, v))
}

// SubmissionTypeNEQ applies the NEQ predicate on the "submission_type" field.
func SubmissionTypeNEQ(v SubmissionType) predicate.Submission {
	return predicate.Submission(sql.FieldNEQ(FieldSubmissionType, v))
}

// SubmissionTypeIn applies the In predicate on the "submission_type" field.
func SubmissionTypeIn(vs ...SubmissionType) predicate.Submission {
	return predicate.Submission(sql.FieldIn(FieldSubmissionType, vs...))
}

// SubmissionTypeNotIn applies the NotIn predicate on the "submission_type" field.
func SubmissionTypeNotIn(vs ...SubmissionType) predicate.Submission {
	return predicate.Submission(sql.FieldNotIn(FieldSubmissionType, vs...))
}

// SubmitterEmailEQ applies the EQ predicate on the "submitter_email" field.
func SubmitterEmailEQ(v string) predicate.Submission {
	return predicate.Submission(sql.FieldEQ(FieldSubmitterEmail, v))
}

// SubmitterEmailNEQ applies the NEQ predicate on the "submitter_email" field.
func SubmitterEmailNEQ(v string) predicate.Submission {
	return predicate.Submission(sql.FieldNEQ(FieldSubmitterEmail, v))
}

// SubmitterEmailIn applies the In predicate on the "submitter_email" field.
func SubmitterEmailIn(vs ...string) predicate.Submission {
	return predicate.Submission(sql.FieldIn(FieldSubmitterEmail, vs...))
}

// SubmitterEmailNotIn applies the NotIn predicate on the "submitter_email" field.
func SubmitterEmailNotIn(vs ...string) predicate.Submission {
	return predicate.Submission(sql.FieldNotIn(FieldSubmitterEmail, vs...))
}

// SubmitterEmailGT applies the GT predicate on the "submitter_email" field.
func SubmitterEmailGT(v string) predicate.Submission {
	return predicate.Submission(sql.FieldGT(FieldSubmitterEmail, v))
}

// SubmitterEmailGTE applies the GTE predicate on the "submitter_email" field.
func SubmitterEmailGTE(v string) predicate.Submission {
	return predicate.Submission(sql.FieldGTE(FieldSubmitterEmail, v))
}

// SubmitterEmailLT applies the LT predicate on the "submitter_email" field.
func SubmitterEmailLT(v string) predicate.Submission {
	return predicate.Submission(sql.FieldLT(FieldSubmitterEmail, v))
}

// SubmitterEmailLTE applies the LTE predicate on the "submitter_email" field.
func SubmitterEmailLTE(v string) predicate.Submission {
	return predicate.Submission(sql.FieldLTE(FieldSubmitterEmail, v))
}

// SubmitterEmailContains applies the Contains predicate on the "submitter_email" field.
func SubmitterEmailContains(v string) predicate.Submission {
	return predicate.Submission(sql.FieldContains(FieldSubmitterEmail, v))
}

// SubmitterEmailHasPrefix applies the HasPrefix predicate on the "submitter_email" field.
func SubmitterEmailHasPrefix(v string) predicate.Submission {
	return predicate.Submission(sql.FieldHasPrefix(FieldSubmitterEmail, v))
}

// SubmitterEmailHasSuffix applies the HasSuffix predicate on the "submitter_email" field.
func SubmitterEmailHasSuffix(v string) predicate.Submission {
	return predicate.Submission(sql.FieldHasSuffix(FieldSubmitterEmail, v))
}

// SubmitterEmailEqualFold applies the EqualFold predicate on the "submitter_email" field.
func SubmitterEmailEqualFold(v string) predicate.Submission {
	return predicate.Submission(sql.FieldEqualFold(FieldSubmitterEmail, v))
}

// SubmitterEmailContainsFold applies the ContainsFold predicate on the "submitter_email" field.
func SubmitterEmailContainsFold(v string) predicate.Submission {
	return predicate.Submission(sql.FieldContainsFold(FieldSubmitterEmail, v))
}

// SubmitterNameEQ applies the EQ predicate on the "submitter_name" field.
func SubmitterNameEQ(v string) predicate.Submission {
	return predicate.Submission(sql.FieldEQ(FieldSubmitterName, v))
}

// SubmitterNameNEQ applies the NEQ predicate on the "submitter_name" field.
func SubmitterNameNEQ(v string) predicate.Submission {
	return predicate.Submission(sql.FieldNEQ(FieldSubmitterName, v))
}

// SubmitterNameIn applies the In predicate on the "submitter_name" field.
func SubmitterNameIn(vs ...string) predicate.Submission {
	return predicate.Submission(sql.FieldIn(FieldSubmitterName, vs...))
}

// SubmitterNameNotIn applies the NotIn predicate on the "submitter_name" field.
func SubmitterNameNotIn(vs ...string) predicate.Submission {
	return predicate.Submission(sql.FieldNotIn(FieldSubmitterName, vs...))
}

// SubmitterNameGT applies the GT predicate on the "submitter_name" field.
func SubmitterNameGT(v string) predicate.Submission {
	return predicate.Submission(sql.FieldGT(FieldSubmitterName, v))
}

// SubmitterNameGTE applies the GTE predicate on the "submitter_name" field.
func SubmitterNameGTE(v string) predicate.Submission {
	return predicate.Submission(sql.FieldGTE(FieldSubmitterName, v))
}

// SubmitterNameLT applies the LT predicate on the "submitter_name" field.
func SubmitterNameLT(v string) predicate.Submission {
	return predicate.Submission(sql.FieldLT(FieldSubmitterName, v))
}

// SubmitterNameLTE applies the LTE predicate on the "submitter_name" field.
func SubmitterNameLTE(v string) predicate.Submission {
	return predicate.Submission(sql.FieldLTE(FieldSubmitterName, v))
}

// SubmitterNameContains applies the Contains predicate on the "submitter_name" field.
func SubmitterNameContains(v string) predicate.Submission {
	return predicate.Submission(sql.FieldContains(FieldSubmitterName, v))
}

// SubmitterNameHasPrefix applies the HasPrefix predicate on the "submitter_name" field.
func SubmitterNameHasPrefix(v string) predicate.Submission {
	return predicate.Submission(sql.FieldHasPrefix(FieldSubmitterName, v))
}

// SubmitterNameHasSuffix applies the HasSuffix predicate on the "submitter_name" field.
func SubmitterNameHasSuffix(v string) predicate.Submission {
	return predicate.Submission(sql.FieldHasSuffix(FieldSubmitterName, v))
}

// SubmitterNameEqualFold applies the EqualFold predicate on the "submitter_name" field.
func SubmitterNameEqualFold(v string) predicate.Submission {
	return predicate.Submission(sql.FieldEqualFold(FieldSubmitterName, v))
}

// SubmitterNameContainsFold applies the ContainsFold predicate on the "submitter_name" field.
func SubmitterNameContainsFold(v string) predicate.Submission {
	return predicate.Submission(sql.FieldContainsFold(FieldSubmitterName, v))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.Submission {
	return predicate.Submission(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.Submission {
	return predicate.Submission(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.Submission {
	return predicate.Submission(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.Submission {
	return predicate.Submission(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.Submission {
	return predicate.Submission(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.Submission {
	return predicate.Submission(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.Submission {
	return predicate.Submission(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.Submission {
	return predicate.Submission(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.Submission {
	return predicate.Submission(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.Submission {
	return predicate.Submission(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.Submission {
	return predicate.Submission(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.Submission {
	return predicate.Submission(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.Submission {
	return predicate.Submission(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.Submission {
	return predicate.Submission(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.Submission {
	return predicate.Submission(sql.FieldContainsFold(FieldNotes, v))
}

// SourceTypeEQ applies the EQ predicate on the "source_type" field.
func SourceTypeEQ(v SourceType) predicate.Submission {
	return predicate.Submission(sql.FieldEQ(FieldSourceType, v))
}

// SourceTypeNEQ applies the NEQ predicate on the "source_type" field.
func SourceTypeNEQ(v SourceType) predicate.Submission {
	return predicate.Submission(sql.FieldNEQ(FieldSourceType, v))
}

// SourceTypeIn applies the In predicate on the "source_type" field.
func SourceTypeIn(vs ...SourceType) predicate.Submission {
	return predicate.Submission(sql.FieldIn(FieldSourceType, vs...))
}

// SourceTypeNotIn applies the NotIn predicate on the "source_type" field.
func SourceTypeNotIn(vs ...SourceType) predicate.Submission {
	return predicate.Submission(sql.FieldNotIn(FieldSourceType, vs...))
}

// GithubRepoURLEQ applies the EQ predicate on the "github_repo_url" field.
func GithubRepoURLEQ(v string) predicate.Submission {
	return predicate.Submission(sql.FieldEQ(FieldGithubRepoURL, v))
}

// GithubRepoURLNEQ applies the NEQ predicate on the "github_repo_url" field.
func GithubRepoURLNEQ(v string) predicate.Submission {
	return predicate.Submission(sql.FieldNEQ(FieldGithubRepoURL, v))
}

// GithubRepoURLIn applies the In predicate on the "github_repo_url" field.
func GithubRepoURLIn(vs ...string) predicate.Submission {
	return predicate.Submission(sql.FieldIn(FieldGithubRepoURL, vs...))
}

// GithubRepoURLNotIn applies the NotIn predicate on the "github_repo_url" field.
func GithubRepoURLNotIn(vs ...string) predicate.Submission {
	return predicate.Submission(sql.FieldNotIn(FieldGithubRepoURL, vs...))
}

// GithubRepoURLGT applies the GT predicate on the "github_repo_url" field.
func GithubRepoURLGT(v string) predicate.Submission {
	return predicate.Submission(sql.FieldGT(FieldGithubRepoURL, v))
}

// GithubRepoURLGTE applies the GTE predicate on the "github_repo_url" field.
func GithubRepoURLGTE(v string) predicate.Submission {
	return predicate.Submission(sql.FieldGTE(FieldGithubRepoURL, v))
}

// GithubRepoURLLT applies the LT predicate on the "github_repo_url" field.
func GithubRepoURLLT(v string) predicate.Submission {
	return predicate.Submission(sql.FieldLT(FieldGithubRepoURL, v))
}

// GithubRepoURLLTE applies the LTE predicate on the "github_repo_url" field.
func GithubRepoURLLTE(v string) predicate.Submission {
	return predicate.Submission(sql.FieldLTE(FieldGithubRepoURL, v))
}

// GithubRepoURLContains applies the Contains predicate on the "github_repo_url" field.
func GithubRepoURLContains(v string) predicate.Submission {
	return predicate.Submission(sql.FieldContains(FieldGithubRepoURL, v))
}

// GithubRepoURLHasPrefix applies the HasPrefix predicate on the "github_repo_url" field.
func GithubRepoURLHasPrefix(v string) predicate.Submission {
	return predicate.Submission(sql.FieldHasPrefix(FieldGithubRepoURL, v))
}

// GithubRepoURLHasSuffix applies the HasSuffix predicate on the "github_repo_url" field.
func GithubRepoURLHasSuffix(v string) predicate.Submission {
	return predicate.Submission(sql.FieldHasSuffix(FieldGithubRepoURL, v))
}

// GithubRepoURLIsNil applies the IsNil predicate on the "github_repo_url" field.
func GithubRepoURLIsNil() predicate.Submission {
	return predicate.Submission(sql.FieldIsNull(FieldGithubRepoURL))
}

// GithubRepoURLNotNil applies the NotNil predicate on the "github_repo_url" field.
func GithubRepoURLNotNil() predicate.Submission {
	return predicate.Submission(sql.FieldNotNull(FieldGithubRepoURL))
}

// GithubRepoURLEqualFold applies the EqualFold predicate on the "github_repo_url" field.
func GithubRepoURLEqualFold(v string) predicate.Submission {
	return predicate.Submission(sql.FieldEqualFold(FieldGithubRepoURL, v))
}

// GithubRepoURLContainsFold applies the ContainsFold predicate on the "github_repo_url" field.
func GithubRepoURLContainsFold(v string) predicate.Submission {
	return predicate.Submission(sql.FieldContainsFold(FieldGithubRepoURL, v))
}

// AutoUpgradeEnabledEQ applies the EQ predicate on the "auto_upgrade_enabled" field.
func AutoUpgradeEnabledEQ(v bool) predicate.Submission {
	return predicate.Submission(sql.FieldEQ(FieldAutoUpgradeEnabled, v))
}

// AutoUpgradeEnabledNEQ applies the NEQ predicate on the "auto_upgrade_enabled" field.
func AutoUpgradeEnabledNEQ(v bool) predicate.Submission {
	return predicate.Submission(sql.FieldNEQ(FieldAutoUpgradeEnabled, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Submission {
	return predicate.Submission(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Submission {
	return predicate.Submission(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Submission {
	return predicate.Submission(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Submission {
	return predicate.Submission(sql.FieldNotIn(FieldStatus, vs...))
}

// ReviewerNotesEQ applies the EQ predicate on the "reviewer_notes" field.
func ReviewerNotesEQ(v string) predicate.Submission {
	return predicate.Submission(sql.FieldEQ(FieldReviewerNotes, v))
}

// ReviewerNotesNEQ applies the NEQ predicate on the "reviewer_notes" field.
func ReviewerNotesNEQ(v string) predicate.Submission {
	return predicate.Submission(sql.FieldNEQ(FieldReviewerNotes, v))
}

// ReviewerNotesIn applies the In predicate on the "reviewer_notes" field.
func ReviewerNotesIn(vs ...string) predicate.Submission {
	return predicate.Submission(sql.FieldIn(FieldReviewerNotes, vs...))
}

// ReviewerNotesNotIn applies the NotIn predicate on the "reviewer_notes" field.
func ReviewerNotesNotIn(vs ...string) predicate.Submission {
	return predicate.Submission(sql.FieldNotIn(FieldReviewerNotes, vs...))
}

// ReviewerNotesGT applies the GT predicate on the "reviewer_notes" field.
func ReviewerNotesGT(v string) predicate.Submission {
	return predicate.Submission(sql.FieldGT(FieldReviewerNotes, v))
}

// ReviewerNotesGTE applies the GTE predicate on the "reviewer_notes" field.
func ReviewerNotesGTE(v string) predicate.Submission {
	return predicate.Submission(sql.FieldGTE(FieldReviewerNotes, v))
}

// ReviewerNotesLT applies the LT predicate on the "reviewer_notes" field.
func ReviewerNotesLT(v string) predicate.Submission {
	return predicate.Submission(sql.FieldLT(FieldReviewerNotes, v))
}

// ReviewerNotesLTE applies the LTE predicate on the "reviewer_notes" field.
func ReviewerNotesLTE(v string) predicate.Submission {
	return predicate.Submission(sql.FieldLTE(FieldReviewerNotes, v))
}

// ReviewerNotesContains applies the Contains predicate on the "reviewer_notes" field.
func ReviewerNotesContains(v string) predicate.Submission {
	return predicate.Submission(sql.FieldContains(FieldReviewerNotes, v))
}

// ReviewerNotesHasPrefix applies the HasPrefix predicate on the "reviewer_notes" field.
func ReviewerNotesHasPrefix(v string) predicate.Submission {
	return predicate.Submission(sql.FieldHasPrefix(FieldReviewerNotes, v))
}

// ReviewerNotesHasSuffix applies the HasSuffix predicate on the "reviewer_notes" field.
func ReviewerNotesHasSuffix(v string) predicate.Submission {
	return predicate.Submission(sql.FieldHasSuffix(FieldReviewerNotes, v))
}

// ReviewerNotesIsNil applies the IsNil predicate on the "reviewer_notes" field.
func ReviewerNotesIsNil() predicate.Submission {
	return predicate.Submission(sql.FieldIsNull(FieldReviewerNotes))
}

// ReviewerNotesNotNil applies the NotNil predicate on the "reviewer_notes" field.
func ReviewerNotesNotNil() predicate.Submission {
	return predicate.Submission(sql.FieldNotNull(FieldReviewerNotes))
}

// ReviewerNotesEqualFold applies the EqualFold predicate on the "reviewer_notes" field.
func ReviewerNotesEqualFold(v string) predicate.Submission {
	return predicate.Submission(sql.FieldEqualFold(FieldReviewerNotes, v))
}

// ReviewerNotesContainsFold applies the ContainsFold predicate on the "reviewer_notes" field.
func ReviewerNotesContainsFold(v string) predicate.Submission {
	return predicate.Submission(sql.FieldContainsFold(FieldReviewerNotes, v))
}

// ReviewedByEQ applies the EQ predicate on the "reviewed_by" field.
func ReviewedByEQ(v string) predicate.Submission {
	return predicate.Submission(sql.FieldEQ(FieldReviewedBy, v))
}

// ReviewedByNEQ applies the NEQ predicate on the "reviewed_by" field.
func ReviewedByNEQ(v string) predicate.Submission {
	return predicate.Submission(sql.FieldNEQ(FieldReviewedBy, v))
}

// ReviewedByIn applies the In predicate on the "reviewed_by" field.
func ReviewedByIn(vs ...string) predicate.Submission {
	return predicate.Submission(sql.FieldIn(FieldReviewedBy, vs...))
}

// ReviewedByNotIn applies the NotIn predicate on the "reviewed_by" field.
func ReviewedByNotIn(vs ...string) predicate.Submission {
	return predicate.Submission(sql.FieldNotIn(FieldReviewedBy, vs...))
}

// ReviewedByGT applies the GT predicate on the "reviewed_by" field.
func ReviewedByGT(v string) predicate.Submission {
	return predicate.Submission(sql.FieldGT(FieldReviewedBy, v))
}

// ReviewedByGTE applies the GTE predicate on the "reviewed_by" field.
func ReviewedByGTE(v string) predicate.Submission {
	return predicate.Submission(sql.FieldGTE(FieldReviewedBy, v))
}

// ReviewedByLT applies the LT predicate on the "reviewed_by" field.
func ReviewedByLT(v string) predicate.Submission {
	return predicate.Submission(sql.FieldLT(FieldReviewedBy, v))
}

// ReviewedByLTE applies the LTE predicate on the "reviewed_by" field.
func ReviewedByLTE(v string) predicate.Submission {
	return predicate.Submission(sql.FieldLTE(FieldReviewedBy, v))
}

// ReviewedByContains applies the Contains predicate on the "reviewed_by" field.
func ReviewedByContains(v string) predicate.Submission {
	return predicate.Submission(sql.FieldContains(FieldReviewedBy, v))
}

// ReviewedByHasPrefix applies the HasPrefix predicate on the "reviewed_by" field.
func ReviewedByHasPrefix(v string) predicate.Submission {
	return predicate.Submission(sql.FieldHasPrefix(FieldReviewedBy, v))
}

// ReviewedByHasSuffix applies the HasSuffix predicate on the "reviewed_by" field.
func ReviewedByHasSuffix(v string) predicate.Submission {
	return predicate.Submission(sql.FieldHasSuffix(FieldReviewedBy, v))
}

// ReviewedByIsNil applies the IsNil predicate on the "reviewed_by" field.
func ReviewedByIsNil() predicate.Submission {
	return predicate.Submission(sql.FieldIsNull(FieldReviewedBy))
}

// ReviewedByNotNil applies the NotNil predicate on the "reviewed_by" field.
func ReviewedByNotNil() predicate.Submission {
	return predicate.Submission(sql.FieldNotNull(FieldReviewedBy))
}

// ReviewedByEqualFold applies the EqualFold predicate on the "reviewed_by" field.
func ReviewedByEqualFold(v string) predicate.Submission {
	return predicate.Submission(sql.FieldEqualFold(FieldReviewedBy, v))
}

// ReviewedByContainsFold applies the ContainsFold predicate on the "reviewed_by" field.
func ReviewedByContainsFold(v string) predicate.Submission {
	return predicate.Submission(sql.FieldContainsFold(FieldReviewedBy, v))
}

// ReviewedAtEQ applies the EQ predicate on the "reviewed_at" field.
func ReviewedAtEQ(v time.Time) predicate.Submission {
	return predicate.Submission(sql.FieldEQ(FieldReviewedAt, v))
}

// ReviewedAtNEQ applies the NEQ predicate on the "reviewed_at" field.
func ReviewedAtNEQ(v time.Time) predicate.Submission {
	return predicate.Submission(sql.FieldNEQ(FieldReviewedAt, v))
}

// ReviewedAtIn applies the In predicate on the "reviewed_at" field.
func ReviewedAtIn(vs ...time.Time) predicate.Submission {
	return predicate.Submission(sql.FieldIn(FieldReviewedAt, vs...))
}

// ReviewedAtNotIn applies the NotIn predicate on the "reviewed_at" field.
func ReviewedAtNotIn(vs ...time.Time) predicate.Submission {
	return predicate.Submission(sql.FieldNotIn(FieldReviewedAt, vs...))
}

// ReviewedAtGT applies the GT predicate on the "reviewed_at" field.
func ReviewedAtGT(v time.Time) predicate.Submission {
	return predicate.Submission(sql.FieldGT(FieldReviewedAt, v))
}

// ReviewedAtGTE applies the GTE predicate on the "reviewed_at" field.
func ReviewedAtGTE(v time.Time) predicate.Submission {
	return predicate.Submission(sql.FieldGTE(FieldReviewedAt, v))
}

// ReviewedAtLT applies the LT predicate on the "reviewed_at" field.
func ReviewedAtLT(v time.Time) predicate.Submission {
	return predicate.Submission(sql.FieldLT(FieldReviewedAt, v))
}

// ReviewedAtLTE applies the LTE predicate on the "reviewed_at" field.
func ReviewedAtLTE(v time.Time) predicate.Submission {
	return predicate.Submission(sql.FieldLTE(FieldReviewedAt, v))
}

// ReviewedAtIsNil applies the IsNil predicate on the "reviewed_at" field.
func ReviewedAtIsNil() predicate.Submission {
	return predicate.Submission(sql.FieldIsNull(FieldReviewedAt))
}

// ReviewedAtNotNil applies the NotNil predicate on the "reviewed_at" field.
func ReviewedAtNotNil() predicate.Submission {
	return predicate.Submission(sql.FieldNotNull(FieldReviewedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Submission {
	return predicate.Submission(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Submission {
	return predicate.Submission(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Submission {
	return predicate.Submission(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Submission {
	return predicate.Submission(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Submission {
	return predicate.Submission(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Submission {
	return predicate.Submission(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Submission {
	return predicate.Submission(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Submission {
	return predicate.Submission(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Submission {
	return predicate.Submission(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Submission {
	return predicate.Submission(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Submission {
	return predicate.Submission(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Submission {
	return predicate.Submission(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Submission {
	return predicate.Submission(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Submission {
	return predicate.Submission(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Submission {
	return predicate.Submission(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Submission {
	return predicate.Submission(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasPlugin applies the HasEdge predicate on the "plugin" edge.
func HasPlugin() predicate.Submission {
	return predicate.Submission(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PluginTable, PluginColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPluginWith applies the HasEdge predicate on the "plugin" edge with a given conditions (other predicates).
func HasPluginWith(preds ...predicate.Plugin) predicate.Submission {
	return predicate.Submission(func(s *sql.Selector) {
		step := newPluginStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasVersion applies the HasEdge predicate on the "version" edge.
func HasVersion() predicate.Submission {
	return predicate.Submission(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, VersionTable, VersionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasVersionWith applies the HasEdge predicate on the "version" edge with a given conditions (other predicates).
func HasVersionWith(preds ...predicate.PluginVersion) predicate.Submission {
	return predicate.Submission(func(s *sql.Selector) {
		step := newVersionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Submission) predicate.Submission {
	return predicate.Submission(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Submission) predicate.Submission {
	return predicate.Submission(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Submission) predicate.Submission {
	return predicate.Submission(sql.NotPredicates(p))
}
