// Code generated by ent, DO NOT EDIT.

package plugin

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the plugin type in the database.
	Label = "plugin"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDisplayName holds the string denoting the display_name field in the database.
	FieldDisplayName = "display_name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldAuthor holds the string denoting the author field in the database.
	FieldAuthor = "author"
	// FieldRepositoryURL holds the string denoting the repository_url field in the database.
	FieldRepositoryURL = "repository_url"
	// FieldHomepageURL holds the string denoting the homepage_url field in the database.
	FieldHomepageURL = "homepage_url"
	// FieldLicense holds the string denoting the license field in the database.
	FieldLicense = "license"
	// FieldCategory holds the string denoting the category field in the database.
	FieldCategory = "category"
	// FieldTags holds the string denoting the tags field in the database.
	FieldTags = "tags"
	// FieldIsOfficial holds the string denoting the is_official field in the database.
	FieldIsOfficial = "is_official"
	// FieldIsVerified holds the string denoting the is_verified field in the database.
	FieldIsVerified = "is_verified"
	// FieldDownloadCount holds the string denoting the download_count field in the database.
	FieldDownloadCount = "download_count"
	// FieldRating holds the string denoting the rating field in the database.
	FieldRating = "rating"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeVersions holds the string denoting the versions edge name in mutations.
	EdgeVersions = "versions"
	// EdgeSubmissions holds the string denoting the submissions edge name in mutations.
	EdgeSubmissions = "submissions"
	// EdgeDownloadLogs holds the string denoting the download_logs edge name in mutations.
	EdgeDownloadLogs = "download_logs"
	// Table holds the table name of the plugin in the database.
	Table = "plugins"
	// VersionsTable is the table that holds the versions relation/edge.
	VersionsTable = "plugin_versions"
	// VersionsInverseTable is the table name for the PluginVersion entity.
	// It exists in this package in order to avoid circular dependency with the "pluginversion" package.
	VersionsInverseTable = "plugin_versions"
	// VersionsColumn is the table column denoting the versions relation/edge.
	VersionsColumn = "plugin_id"
	// SubmissionsTable is the table that holds the submissions relation/edge.
	SubmissionsTable = "submissions"
	// SubmissionsInverseTable is the table name for the Submission entity.
	// It exists in this package in order to avoid circular dependency with the "submission" package.
	SubmissionsInverseTable = "submissions"
	// SubmissionsColumn is the table column denoting the submissions relation/edge.
	SubmissionsColumn = "plugin_id"
	// DownloadLogsTable is the table that holds the download_logs relation/edge.
	DownloadLogsTable = "download_logs"
	// DownloadLogsInverseTable is the table name for the DownloadLog entity.
	// It exists in this package in order to avoid circular dependency with the "downloadlog" package.
	DownloadLogsInverseTable = "download_logs"
	// DownloadLogsColumn is the table column denoting the download_logs relation/edge.
	DownloadLogsColumn = "plugin_id"
)

// Columns holds all SQL columns for plugin fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDisplayName,
	FieldDescription,
	FieldAuthor,
	FieldRepositoryURL,
	FieldHomepageURL,
	FieldLicense,
	FieldCategory,
	FieldTags,
	FieldIsOfficial,
	FieldIsVerified,
	FieldDownloadCount,
	FieldRating,
	FieldStatus,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	DisplayNameValidator func(string) error
	// AuthorValidator is a validator for the "author" field. It is called by the builders before save.
	AuthorValidator func(string) error
	// DefaultLicense holds the default value on creation for the "license" field.
	DefaultLicense string
	// DefaultIsOfficial holds the default value on creation for the "is_official" field.
	DefaultIsOfficial bool
	// DefaultIsVerified holds the default value on creation for the "is_verified" field.
	DefaultIsVerified bool
	// DefaultDownloadCount holds the default value on creation for the "download_count" field.
	DefaultDownloadCount int
	// DownloadCountValidator is a validator for the "download_count" field. It is called by the builders before save.
	DownloadCountValidator func(int) error
	// RatingValidator is a validator for the "rating" field. It is called by the builders before save.
	RatingValidator func(float64) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Category defines the type for the "category" enum field.
type Category string

// CategoryOther is the default value of the Category enum.
const DefaultCategory = CategoryOther

// Category values.
const (
	CategoryProxy     Category = "proxy"
	CategoryAuth      Category = "auth"
	CategoryAnalytics Category = "analytics"
	CategorySecurity  Category = "security"
	CategoryOther     Category = "other"
)

func (c Category) String() string {
	return string(c)
}

// CategoryValidator is a validator for the "category" field enum values. It is called by the builders before save.
func CategoryValidator(c Category) error {
	switch c {
	case CategoryProxy, CategoryAuth, CategoryAnalytics, CategorySecurity, CategoryOther:
		return nil
	default:
		return fmt.Errorf("plugin: invalid enum value for category field: %q", c)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusActive is the default value of the Status enum.
const DefaultStatus = StatusActive

// Status values.
const (
	StatusActive     Status = "active"
	StatusDeprecated Status = "deprecated"
	StatusSuspended  Status = "suspended"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusActive, StatusDeprecated, StatusSuspended:
		return nil
	default:
		return fmt.Errorf("plugin: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Plugin queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDisplayName orders the results by the display_name field.
func ByDisplayName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByAuthor orders the results by the author field.
func ByAuthor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthor, opts...).ToFunc()
}

// ByRepositoryURL orders the results by the repository_url field.
func ByRepositoryURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRepositoryURL, opts...).ToFunc()
}

// ByHomepageURL orders the results by the homepage_url field.
func ByHomepageURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHomepageURL, opts...).ToFunc()
}

// ByLicense orders the results by the license field.
func ByLicense(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLicense, opts...).ToFunc()
}

// ByCategory orders the results by the category field.
func ByCategory(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCategory, opts...).ToFunc()
}

// ByIsOfficial orders the results by the is_official field.
func ByIsOfficial(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsOfficial, opts...).ToFunc()
}

// ByIsVerified orders the results by the is_verified field.
func ByIsVerified(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsVerified, opts...).ToFunc()
}

// ByDownloadCount orders the results by the download_count field.
func ByDownloadCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDownloadCount, opts...).ToFunc()
}

// ByRating orders the results by the rating field.
func ByRating(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRating, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByVersionsCount orders the results by versions count.
func ByVersionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newVersionsStep(), opts...)
	}
}

// ByVersions orders the results by versions terms.
func ByVersions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newVersionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// BySubmissionsCount orders the results by submissions count.
func BySubmissionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSubmissionsStep(), opts...)
	}
}

// BySubmissions orders the results by submissions terms.
func BySubmissions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSubmissionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByDownloadLogsCount orders the results by download_logs count.
func ByDownloadLogsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDownloadLogsStep(), opts...)
	}
}

// ByDownloadLogs orders the results by download_logs terms.
func ByDownloadLogs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDownloadLogsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newVersionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(VersionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, VersionsTable, VersionsColumn),
	)
}
func newSubmissionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SubmissionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SubmissionsTable, SubmissionsColumn),
	)
}
func newDownloadLogsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DownloadLogsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, DownloadLogsTable, DownloadLogsColumn),
	)
}
