// Code generated by ent, DO NOT EDIT.

package trustkey

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/IanShaw027/sub2api-plugin-market/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldLTE(FieldID, id))
}

// KeyID applies equality check predicate on the "key_id" field. It's identical to KeyIDEQ.
func KeyID(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldEQ(FieldKeyID, v))
}

// PublicKey applies equality check predicate on the "public_key" field. It's identical to PublicKeyEQ.
func PublicKey(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldEQ(FieldPublicKey, v))
}

// OwnerName applies equality check predicate on the "owner_name" field. It's identical to OwnerNameEQ.
func OwnerName(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldEQ(FieldOwnerName, v))
}

// OwnerEmail applies equality check predicate on the "owner_email" field. It's identical to OwnerEmailEQ.
func OwnerEmail(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldEQ(FieldOwnerEmail, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldEQ(FieldDescription, v))
}

// IsActive applies equality check predicate on the "is_active" field. It's identical to IsActiveEQ.
func IsActive(v bool) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldEQ(FieldIsActive, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldEQ(FieldExpiresAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldEQ(FieldUpdatedAt, v))
}

// KeyIDEQ applies the EQ predicate on the "key_id" field.
func KeyIDEQ(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldEQ(FieldKeyID, v))
}

// KeyIDNEQ applies the NEQ predicate on the "key_id" field.
func KeyIDNEQ(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldNEQ(FieldKeyID, v))
}

// KeyIDIn applies the In predicate on the "key_id" field.
func KeyIDIn(vs ...string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldIn(FieldKeyID, vs...))
}

// KeyIDNotIn applies the NotIn predicate on the "key_id" field.
func KeyIDNotIn(vs ...string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldNotIn(FieldKeyID, vs...))
}

// KeyIDGT applies the GT predicate on the "key_id" field.
func KeyIDGT(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldGT(FieldKeyID, v))
}

// KeyIDGTE applies the GTE predicate on the "key_id" field.
func KeyIDGTE(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldGTE(FieldKeyID, v))
}

// KeyIDLT applies the LT predicate on the "key_id" field.
func KeyIDLT(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldLT(FieldKeyID, v))
}

// KeyIDLTE applies the LTE predicate on the "key_id" field.
func KeyIDLTE(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldLTE(FieldKeyID, v))
}

// KeyIDContains applies the Contains predicate on the "key_id" field.
func KeyIDContains(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldContains(FieldKeyID, v))
}

// KeyIDHasPrefix applies the HasPrefix predicate on the "key_id" field.
func KeyIDHasPrefix(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldHasPrefix(FieldKeyID, v))
}

// KeyIDHasSuffix applies the HasSuffix predicate on the "key_id" field.
func KeyIDHasSuffix(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldHasSuffix(FieldKeyID, v))
}

// KeyIDEqualFold applies the EqualFold predicate on the "key_id" field.
func KeyIDEqualFold(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldEqualFold(FieldKeyID, v))
}

// KeyIDContainsFold applies the ContainsFold predicate on the "key_id" field.
func KeyIDContainsFold(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldContainsFold(FieldKeyID, v))
}

// PublicKeyEQ applies the EQ predicate on the "public_key" field.
func PublicKeyEQ(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldEQ(FieldPublicKey, v))
}

// PublicKeyNEQ applies the NEQ predicate on the "public_key" field.
func PublicKeyNEQ(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldNEQ(FieldPublicKey, v))
}

// PublicKeyIn applies the In predicate on the "public_key" field.
func PublicKeyIn(vs ...string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldIn(FieldPublicKey, vs...))
}

// PublicKeyNotIn applies the NotIn predicate on the "public_key" field.
func PublicKeyNotIn(vs ...string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldNotIn(FieldPublicKey, vs...))
}

// PublicKeyGT applies the GT predicate on the "public_key" field.
func PublicKeyGT(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldGT(FieldPublicKey, v))
}

// PublicKeyGTE applies the GTE predicate on the "public_key" field.
func PublicKeyGTE(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldGTE(FieldPublicKey, v))
}

// PublicKeyLT applies the LT predicate on the "public_key" field.
func PublicKeyLT(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldLT(FieldPublicKey, v))
}

// PublicKeyLTE applies the LTE predicate on the "public_key" field.
func PublicKeyLTE(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldLTE(FieldPublicKey, v))
}

// PublicKeyContains applies the Contains predicate on the "public_key" field.
func PublicKeyContains(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldContains(FieldPublicKey, v))
}

// PublicKeyHasPrefix applies the HasPrefix predicate on the "public_key" field.
func PublicKeyHasPrefix(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldHasPrefix(FieldPublicKey, v))
}

// PublicKeyHasSuffix applies the HasSuffix predicate on the "public_key" field.
func PublicKeyHasSuffix(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldHasSuffix(FieldPublicKey, v))
}

// PublicKeyEqualFold applies the EqualFold predicate on the "public_key" field.
func PublicKeyEqualFold(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldEqualFold(FieldPublicKey, v))
}

// PublicKeyContainsFold applies the ContainsFold predicate on the "public_key" field.
func PublicKeyContainsFold(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldContainsFold(FieldPublicKey, v))
}

// KeyTypeEQ applies the EQ predicate on the "key_type" field.
func KeyTypeEQ(v KeyType) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldEQ(FieldKeyType, v))
}

// KeyTypeNEQ applies the NEQ predicate on the "key_type" field.
func KeyTypeNEQ(v KeyType) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldNEQ(FieldKeyType, v))
}

// KeyTypeIn applies the In predicate on the "key_type" field.
func KeyTypeIn(vs ...KeyType) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldIn(FieldKeyType, vs...))
}

// KeyTypeNotIn applies the NotIn predicate on the "key_type" field.
func KeyTypeNotIn(vs ...KeyType) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldNotIn(FieldKeyType, vs...))
}

// OwnerNameEQ applies the EQ predicate on the "owner_name" field.
func OwnerNameEQ(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldEQ(FieldOwnerName, v))
}

// OwnerNameNEQ applies the NEQ predicate on the "owner_name" field.
func OwnerNameNEQ(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldNEQ(FieldOwnerName, v))
}

// OwnerNameIn applies the In predicate on the "owner_name" field.
func OwnerNameIn(vs ...string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldIn(FieldOwnerName, vs...))
}

// OwnerNameNotIn applies the NotIn predicate on the "owner_name" field.
func OwnerNameNotIn(vs ...string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldNotIn(FieldOwnerName, vs...))
}

// OwnerNameGT applies the GT predicate on the "owner_name" field.
func OwnerNameGT(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldGT(FieldOwnerName, v))
}

// OwnerNameGTE applies the GTE predicate on the "owner_name" field.
func OwnerNameGTE(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldGTE(FieldOwnerName, v))
}

// OwnerNameLT applies the LT predicate on the "owner_name" field.
func OwnerNameLT(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldLT(FieldOwnerName, v))
}

// OwnerNameLTE applies the LTE predicate on the "owner_name" field.
func OwnerNameLTE(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldLTE(FieldOwnerName, v))
}

// OwnerNameContains applies the Contains predicate on the "owner_name" field.
func OwnerNameContains(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldContains(FieldOwnerName, v))
}

// OwnerNameHasPrefix applies the HasPrefix predicate on the "owner_name" field.
func OwnerNameHasPrefix(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldHasPrefix(FieldOwnerName, v))
}

// OwnerNameHasSuffix applies the HasSuffix predicate on the "owner_name" field.
func OwnerNameHasSuffix(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldHasSuffix(FieldOwnerName, v))
}

// OwnerNameEqualFold applies the EqualFold predicate on the "owner_name" field.
func OwnerNameEqualFold(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldEqualFold(FieldOwnerName, v))
}

// OwnerNameContainsFold applies the ContainsFold predicate on the "owner_name" field.
func OwnerNameContainsFold(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldContainsFold(FieldOwnerName, v))
}

// OwnerEmailEQ applies the EQ predicate on the "owner_email" field.
func OwnerEmailEQ(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldEQ(FieldOwnerEmail, v))
}

// OwnerEmailNEQ applies the NEQ predicate on the "owner_email" field.
func OwnerEmailNEQ(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldNEQ(FieldOwnerEmail, v))
}

// OwnerEmailIn applies the In predicate on the "owner_email" field.
func OwnerEmailIn(vs ...string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldIn(FieldOwnerEmail, vs...))
}

// OwnerEmailNotIn applies the NotIn predicate on the "owner_email" field.
func OwnerEmailNotIn(vs ...string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldNotIn(FieldOwnerEmail, vs...))
}

// OwnerEmailGT applies the GT predicate on the "owner_email" field.
func OwnerEmailGT(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldGT(FieldOwnerEmail, v))
}

// OwnerEmailGTE applies the GTE predicate on the "owner_email" field.
func OwnerEmailGTE(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldGTE(FieldOwnerEmail, v))
}

// OwnerEmailLT applies the LT predicate on the "owner_email" field.
func OwnerEmailLT(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldLT(FieldOwnerEmail, v))
}

// OwnerEmailLTE applies the LTE predicate on the "owner_email" field.
func OwnerEmailLTE(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldLTE(FieldOwnerEmail, v))
}

// OwnerEmailContains applies the Contains predicate on the "owner_email" field.
func OwnerEmailContains(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldContains(FieldOwnerEmail, v))
}

// OwnerEmailHasPrefix applies the HasPrefix predicate on the "owner_email" field.
func OwnerEmailHasPrefix(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldHasPrefix(FieldOwnerEmail, v))
}

// OwnerEmailHasSuffix applies the HasSuffix predicate on the "owner_email" field.
func OwnerEmailHasSuffix(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldHasSuffix(FieldOwnerEmail, v))
}

// OwnerEmailEqualFold applies the EqualFold predicate on the "owner_email" field.
func OwnerEmailEqualFold(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldEqualFold(FieldOwnerEmail, v))
}

// OwnerEmailContainsFold applies the ContainsFold predicate on the "owner_email" field.
func OwnerEmailContainsFold(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldContainsFold(FieldOwnerEmail, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.TrustKey {
	return predicate.TrustKey(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.TrustKey {
	return predicate.TrustKey(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldContainsFold(FieldDescription, v))
}

// IsActiveEQ applies the EQ predicate on the "is_active" field.
func IsActiveEQ(v bool) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldEQ(FieldIsActive, v))
}

// IsActiveNEQ applies the NEQ predicate on the "is_active" field.
func IsActiveNEQ(v bool) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldNEQ(FieldIsActive, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.TrustKey {
	return predicate.TrustKey(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.TrustKey {
	return predicate.TrustKey(sql.FieldNotNull(FieldExpiresAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.TrustKey {
	return predicate.TrustKey(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TrustKey) predicate.TrustKey {
	return predicate.TrustKey(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TrustKey) predicate.TrustKey {
	return predicate.TrustKey(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TrustKey) predicate.TrustKey {
	return predicate.TrustKey(sql.NotPredicates(p))
}
