// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/IanShaw027/sub2api-plugin-market/ent/downloadlog"
	"github.com/IanShaw027/sub2api-plugin-market/ent/plugin"
	"github.com/google/uuid"
)

// DownloadLog is the model entity for the DownloadLog schema.
type DownloadLog struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// 关联的插件 ID
	PluginID uuid.UUID `json:"plugin_id,omitempty"`
	// 下载的版本号
	Version string `json:"version,omitempty"`
	// 客户端 IP（哈希处理）
	ClientIP string `json:"client_ip,omitempty"`
	// 用户代理
	UserAgent string `json:"user_agent,omitempty"`
	// 国家代码（ISO 3166-1 alpha-2）
	CountryCode string `json:"country_code,omitempty"`
	// 是否下载成功
	Success bool `json:"success,omitempty"`
	// 错误信息
	ErrorMessage string `json:"error_message,omitempty"`
	// 下载时间
	DownloadedAt time.Time `json:"downloaded_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DownloadLogQuery when eager-loading is set.
	Edges        DownloadLogEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DownloadLogEdges holds the relations/edges for other nodes in the graph.
type DownloadLogEdges struct {
	// Plugin holds the value of the plugin edge.
	Plugin *Plugin `json:"plugin,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PluginOrErr returns the Plugin value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DownloadLogEdges) PluginOrErr() (*Plugin, error) {
	if e.Plugin != nil {
		return e.Plugin, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: plugin.Label}
	}
	return nil, &NotLoadedError{edge: "plugin"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DownloadLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case downloadlog.FieldSuccess:
			values[i] = new(sql.NullBool)
		case downloadlog.FieldVersion, downloadlog.FieldClientIP, downloadlog.FieldUserAgent, downloadlog.FieldCountryCode, downloadlog.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case downloadlog.FieldDownloadedAt:
			values[i] = new(sql.NullTime)
		case downloadlog.FieldID, downloadlog.FieldPluginID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DownloadLog fields.
func (_m *DownloadLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case downloadlog.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case downloadlog.FieldPluginID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field plugin_id", values[i])
			} else if value != nil {
				_m.PluginID = *value
			}
		case downloadlog.FieldVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.String
			}
		case downloadlog.FieldClientIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field client_ip", values[i])
			} else if value.Valid {
				_m.ClientIP = value.String
			}
		case downloadlog.FieldUserAgent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_agent", values[i])
			} else if value.Valid {
				_m.UserAgent = value.String
			}
		case downloadlog.FieldCountryCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field country_code", values[i])
			} else if value.Valid {
				_m.CountryCode = value.String
			}
		case downloadlog.FieldSuccess:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field success", values[i])
			} else if value.Valid {
				_m.Success = value.Bool
			}
		case downloadlog.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = value.String
			}
		case downloadlog.FieldDownloadedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field downloaded_at", values[i])
			} else if value.Valid {
				_m.DownloadedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DownloadLog.
// This includes values selected through modifiers, order, etc.
func (_m *DownloadLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPlugin queries the "plugin" edge of the DownloadLog entity.
func (_m *DownloadLog) QueryPlugin() *PluginQuery {
	return NewDownloadLogClient(_m.config).QueryPlugin(_m)
}

// Update returns a builder for updating this DownloadLog.
// Note that you need to call DownloadLog.Unwrap() before calling this method if this DownloadLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DownloadLog) Update() *DownloadLogUpdateOne {
	return NewDownloadLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DownloadLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DownloadLog) Unwrap() *DownloadLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DownloadLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DownloadLog) String() string {
	var builder strings.Builder
	builder.WriteString("DownloadLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("plugin_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PluginID))
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(_m.Version)
	builder.WriteString(", ")
	builder.WriteString("client_ip=")
	builder.WriteString(_m.ClientIP)
	builder.WriteString(", ")
	builder.WriteString("user_agent=")
	builder.WriteString(_m.UserAgent)
	builder.WriteString(", ")
	builder.WriteString("country_code=")
	builder.WriteString(_m.CountryCode)
	builder.WriteString(", ")
	builder.WriteString("success=")
	builder.WriteString(fmt.Sprintf("%v", _m.Success))
	builder.WriteString(", ")
	builder.WriteString("error_message=")
	builder.WriteString(_m.ErrorMessage)
	builder.WriteString(", ")
	builder.WriteString("downloaded_at=")
	builder.WriteString(_m.DownloadedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// DownloadLogs is a parsable slice of DownloadLog.
type DownloadLogs []*DownloadLog
