// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/IanShaw027/sub2api-plugin-market/ent/plugin"
	"github.com/IanShaw027/sub2api-plugin-market/ent/pluginversion"
	"github.com/IanShaw027/sub2api-plugin-market/ent/submission"
)

// PluginVersionCreate is the builder for creating a PluginVersion entity.
type PluginVersionCreate struct {
	config
	mutation *PluginVersionMutation
	hooks    []Hook
}

// SetPluginID sets the "plugin_id" field.
func (_c *PluginVersionCreate) SetPluginID(v uuid.UUID) *PluginVersionCreate {
	_c.mutation.SetPluginID(v)
	return _c
}

// SetVersion sets the "version" field.
func (_c *PluginVersionCreate) SetVersion(v string) *PluginVersionCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetChangelog sets the "changelog" field.
func (_c *PluginVersionCreate) SetChangelog(v string) *PluginVersionCreate {
	_c.mutation.SetChangelog(v)
	return _c
}

// SetNillableChangelog sets the "changelog" field if the given value is not nil.
func (_c *PluginVersionCreate) SetNillableChangelog(v *string) *PluginVersionCreate {
	if v != nil {
		_c.SetChangelog(*v)
	}
	return _c
}

// SetWasmURL sets the "wasm_url" field.
func (_c *PluginVersionCreate) SetWasmURL(v string) *PluginVersionCreate {
	_c.mutation.SetWasmURL(v)
	return _c
}

// SetWasmHash sets the "wasm_hash" field.
func (_c *PluginVersionCreate) SetWasmHash(v string) *PluginVersionCreate {
	_c.mutation.SetWasmHash(v)
	return _c
}

// SetSignature sets the "signature" field.
func (_c *PluginVersionCreate) SetSignature(v string) *PluginVersionCreate {
	_c.mutation.SetSignature(v)
	return _c
}

// SetSignKeyID sets the "sign_key_id" field.
func (_c *PluginVersionCreate) SetSignKeyID(v string) *PluginVersionCreate {
	_c.mutation.SetSignKeyID(v)
	return _c
}

// SetNillableSignKeyID sets the "sign_key_id" field if the given value is not nil.
func (_c *PluginVersionCreate) SetNillableSignKeyID(v *string) *PluginVersionCreate {
	if v != nil {
		_c.SetSignKeyID(*v)
	}
	return _c
}

// SetFileSize sets the "file_size" field.
func (_c *PluginVersionCreate) SetFileSize(v int) *PluginVersionCreate {
	_c.mutation.SetFileSize(v)
	return _c
}

// SetMinAPIVersion sets the "min_api_version" field.
func (_c *PluginVersionCreate) SetMinAPIVersion(v string) *PluginVersionCreate {
	_c.mutation.SetMinAPIVersion(v)
	return _c
}

// SetPluginAPIVersion sets the "plugin_api_version" field.
func (_c *PluginVersionCreate) SetPluginAPIVersion(v string) *PluginVersionCreate {
	_c.mutation.SetPluginAPIVersion(v)
	return _c
}

// SetMaxAPIVersion sets the "max_api_version" field.
func (_c *PluginVersionCreate) SetMaxAPIVersion(v string) *PluginVersionCreate {
	_c.mutation.SetMaxAPIVersion(v)
	return _c
}

// SetNillableMaxAPIVersion sets the "max_api_version" field if the given value is not nil.
func (_c *PluginVersionCreate) SetNillableMaxAPIVersion(v *string) *PluginVersionCreate {
	if v != nil {
		_c.SetMaxAPIVersion(*v)
	}
	return _c
}

// SetDependencies sets the "dependencies" field.
func (_c *PluginVersionCreate) SetDependencies(v []map[string]string) *PluginVersionCreate {
	_c.mutation.SetDependencies(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *PluginVersionCreate) SetStatus(v pluginversion.Status) *PluginVersionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *PluginVersionCreate) SetNillableStatus(v *pluginversion.Status) *PluginVersionCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetPublishedAt sets the "published_at" field.
func (_c *PluginVersionCreate) SetPublishedAt(v time.Time) *PluginVersionCreate {
	_c.mutation.SetPublishedAt(v)
	return _c
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_c *PluginVersionCreate) SetNillablePublishedAt(v *time.Time) *PluginVersionCreate {
	if v != nil {
		_c.SetPublishedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PluginVersionCreate) SetCreatedAt(v time.Time) *PluginVersionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PluginVersionCreate) SetNillableCreatedAt(v *time.Time) *PluginVersionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PluginVersionCreate) SetUpdatedAt(v time.Time) *PluginVersionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PluginVersionCreate) SetNillableUpdatedAt(v *time.Time) *PluginVersionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PluginVersionCreate) SetID(v uuid.UUID) *PluginVersionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PluginVersionCreate) SetNillableID(v *uuid.UUID) *PluginVersionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetPlugin sets the "plugin" edge to the Plugin entity.
func (_c *PluginVersionCreate) SetPlugin(v *Plugin) *PluginVersionCreate {
	return _c.SetPluginID(v.ID)
}

// SetSubmissionID sets the "submission" edge to the Submission entity by ID.
func (_c *PluginVersionCreate) SetSubmissionID(id uuid.UUID) *PluginVersionCreate {
	_c.mutation.SetSubmissionID(id)
	return _c
}

// SetNillableSubmissionID sets the "submission" edge to the Submission entity by ID if the given value is not nil.
func (_c *PluginVersionCreate) SetNillableSubmissionID(id *uuid.UUID) *PluginVersionCreate {
	if id != nil {
		_c = _c.SetSubmissionID(*id)
	}
	return _c
}

// SetSubmission sets the "submission" edge to the Submission entity.
func (_c *PluginVersionCreate) SetSubmission(v *Submission) *PluginVersionCreate {
	return _c.SetSubmissionID(v.ID)
}

// Mutation returns the PluginVersionMutation object of the builder.
func (_c *PluginVersionCreate) Mutation() *PluginVersionMutation {
	return _c.mutation
}

// Save creates the PluginVersion in the database.
func (_c *PluginVersionCreate) Save(ctx context.Context) (*PluginVersion, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PluginVersionCreate) SaveX(ctx context.Context) *PluginVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PluginVersionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PluginVersionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PluginVersionCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := pluginversion.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := pluginversion.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := pluginversion.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := pluginversion.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PluginVersionCreate) check() error {
	if _, ok := _c.mutation.PluginID(); !ok {
		return &ValidationError{Name: "plugin_id", err: errors.New(`ent: missing required field "PluginVersion.plugin_id"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "PluginVersion.version"`)}
	}
	if v, ok := _c.mutation.Version(); ok {
		if err := pluginversion.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "PluginVersion.version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.WasmURL(); !ok {
		return &ValidationError{Name: "wasm_url", err: errors.New(`ent: missing required field "PluginVersion.wasm_url"`)}
	}
	if v, ok := _c.mutation.WasmURL(); ok {
		if err := pluginversion.WasmURLValidator(v); err != nil {
			return &ValidationError{Name: "wasm_url", err: fmt.Errorf(`ent: validator failed for field "PluginVersion.wasm_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.WasmHash(); !ok {
		return &ValidationError{Name: "wasm_hash", err: errors.New(`ent: missing required field "PluginVersion.wasm_hash"`)}
	}
	if v, ok := _c.mutation.WasmHash(); ok {
		if err := pluginversion.WasmHashValidator(v); err != nil {
			return &ValidationError{Name: "wasm_hash", err: fmt.Errorf(`ent: validator failed for field "PluginVersion.wasm_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Signature(); !ok {
		return &ValidationError{Name: "signature", err: errors.New(`ent: missing required field "PluginVersion.signature"`)}
	}
	if v, ok := _c.mutation.Signature(); ok {
		if err := pluginversion.SignatureValidator(v); err != nil {
			return &ValidationError{Name: "signature", err: fmt.Errorf(`ent: validator failed for field "PluginVersion.signature": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FileSize(); !ok {
		return &ValidationError{Name: "file_size", err: errors.New(`ent: missing required field "PluginVersion.file_size"`)}
	}
	if v, ok := _c.mutation.FileSize(); ok {
		if err := pluginversion.FileSizeValidator(v); err != nil {
			return &ValidationError{Name: "file_size", err: fmt.Errorf(`ent: validator failed for field "PluginVersion.file_size": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MinAPIVersion(); !ok {
		return &ValidationError{Name: "min_api_version", err: errors.New(`ent: missing required field "PluginVersion.min_api_version"`)}
	}
	if v, ok := _c.mutation.MinAPIVersion(); ok {
		if err := pluginversion.MinAPIVersionValidator(v); err != nil {
			return &ValidationError{Name: "min_api_version", err: fmt.Errorf(`ent: validator failed for field "PluginVersion.min_api_version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PluginAPIVersion(); !ok {
		return &ValidationError{Name: "plugin_api_version", err: errors.New(`ent: missing required field "PluginVersion.plugin_api_version"`)}
	}
	if v, ok := _c.mutation.PluginAPIVersion(); ok {
		if err := pluginversion.PluginAPIVersionValidator(v); err != nil {
			return &ValidationError{Name: "plugin_api_version", err: fmt.Errorf(`ent: validator failed for field "PluginVersion.plugin_api_version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "PluginVersion.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := pluginversion.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PluginVersion.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PluginVersion.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PluginVersion.updated_at"`)}
	}
	if len(_c.mutation.PluginIDs()) == 0 {
		return &ValidationError{Name: "plugin", err: errors.New(`ent: missing required edge "PluginVersion.plugin"`)}
	}
	return nil
}

func (_c *PluginVersionCreate) sqlSave(ctx context.Context) (*PluginVersion, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PluginVersionCreate) createSpec() (*PluginVersion, *sqlgraph.CreateSpec) {
	var (
		_node = &PluginVersion{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(pluginversion.Table, sqlgraph.NewFieldSpec(pluginversion.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(pluginversion.FieldVersion, field.TypeString, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.Changelog(); ok {
		_spec.SetField(pluginversion.FieldChangelog, field.TypeString, value)
		_node.Changelog = value
	}
	if value, ok := _c.mutation.WasmURL(); ok {
		_spec.SetField(pluginversion.FieldWasmURL, field.TypeString, value)
		_node.WasmURL = value
	}
	if value, ok := _c.mutation.WasmHash(); ok {
		_spec.SetField(pluginversion.FieldWasmHash, field.TypeString, value)
		_node.WasmHash = value
	}
	if value, ok := _c.mutation.Signature(); ok {
		_spec.SetField(pluginversion.FieldSignature, field.TypeString, value)
		_node.Signature = value
	}
	if value, ok := _c.mutation.SignKeyID(); ok {
		_spec.SetField(pluginversion.FieldSignKeyID, field.TypeString, value)
		_node.SignKeyID = value
	}
	if value, ok := _c.mutation.FileSize(); ok {
		_spec.SetField(pluginversion.FieldFileSize, field.TypeInt, value)
		_node.FileSize = value
	}
	if value, ok := _c.mutation.MinAPIVersion(); ok {
		_spec.SetField(pluginversion.FieldMinAPIVersion, field.TypeString, value)
		_node.MinAPIVersion = value
	}
	if value, ok := _c.mutation.PluginAPIVersion(); ok {
		_spec.SetField(pluginversion.FieldPluginAPIVersion, field.TypeString, value)
		_node.PluginAPIVersion = value
	}
	if value, ok := _c.mutation.MaxAPIVersion(); ok {
		_spec.SetField(pluginversion.FieldMaxAPIVersion, field.TypeString, value)
		_node.MaxAPIVersion = value
	}
	if value, ok := _c.mutation.Dependencies(); ok {
		_spec.SetField(pluginversion.FieldDependencies, field.TypeJSON, value)
		_node.Dependencies = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(pluginversion.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.PublishedAt(); ok {
		_spec.SetField(pluginversion.FieldPublishedAt, field.TypeTime, value)
		_node.PublishedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(pluginversion.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(pluginversion.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.PluginIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pluginversion.PluginTable,
			Columns: []string{pluginversion.PluginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PluginID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SubmissionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   pluginversion.SubmissionTable,
			Columns: []string{pluginversion.SubmissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(submission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.submission_version = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PluginVersionCreateBulk is the builder for creating many PluginVersion entities in bulk.
type PluginVersionCreateBulk struct {
	config
	err      error
	builders []*PluginVersionCreate
}

// Save creates the PluginVersion entities in the database.
func (_c *PluginVersionCreateBulk) Save(ctx context.Context) ([]*PluginVersion, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PluginVersion, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PluginVersionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PluginVersionCreateBulk) SaveX(ctx context.Context) []*PluginVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PluginVersionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PluginVersionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
