// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/IanShaw027/sub2api-plugin-market/ent/plugin"
	"github.com/IanShaw027/sub2api-plugin-market/ent/pluginversion"
	"github.com/IanShaw027/sub2api-plugin-market/ent/predicate"
	"github.com/IanShaw027/sub2api-plugin-market/ent/submission"
	"github.com/google/uuid"
)

// PluginVersionUpdate is the builder for updating PluginVersion entities.
type PluginVersionUpdate struct {
	config
	hooks    []Hook
	mutation *PluginVersionMutation
}

// Where appends a list predicates to the PluginVersionUpdate builder.
func (_u *PluginVersionUpdate) Where(ps ...predicate.PluginVersion) *PluginVersionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPluginID sets the "plugin_id" field.
func (_u *PluginVersionUpdate) SetPluginID(v uuid.UUID) *PluginVersionUpdate {
	_u.mutation.SetPluginID(v)
	return _u
}

// SetNillablePluginID sets the "plugin_id" field if the given value is not nil.
func (_u *PluginVersionUpdate) SetNillablePluginID(v *uuid.UUID) *PluginVersionUpdate {
	if v != nil {
		_u.SetPluginID(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *PluginVersionUpdate) SetVersion(v string) *PluginVersionUpdate {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *PluginVersionUpdate) SetNillableVersion(v *string) *PluginVersionUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetChangelog sets the "changelog" field.
func (_u *PluginVersionUpdate) SetChangelog(v string) *PluginVersionUpdate {
	_u.mutation.SetChangelog(v)
	return _u
}

// SetNillableChangelog sets the "changelog" field if the given value is not nil.
func (_u *PluginVersionUpdate) SetNillableChangelog(v *string) *PluginVersionUpdate {
	if v != nil {
		_u.SetChangelog(*v)
	}
	return _u
}

// ClearChangelog clears the value of the "changelog" field.
func (_u *PluginVersionUpdate) ClearChangelog() *PluginVersionUpdate {
	_u.mutation.ClearChangelog()
	return _u
}

// SetWasmURL sets the "wasm_url" field.
func (_u *PluginVersionUpdate) SetWasmURL(v string) *PluginVersionUpdate {
	_u.mutation.SetWasmURL(v)
	return _u
}

// SetNillableWasmURL sets the "wasm_url" field if the given value is not nil.
func (_u *PluginVersionUpdate) SetNillableWasmURL(v *string) *PluginVersionUpdate {
	if v != nil {
		_u.SetWasmURL(*v)
	}
	return _u
}

// SetWasmHash sets the "wasm_hash" field.
func (_u *PluginVersionUpdate) SetWasmHash(v string) *PluginVersionUpdate {
	_u.mutation.SetWasmHash(v)
	return _u
}

// SetNillableWasmHash sets the "wasm_hash" field if the given value is not nil.
func (_u *PluginVersionUpdate) SetNillableWasmHash(v *string) *PluginVersionUpdate {
	if v != nil {
		_u.SetWasmHash(*v)
	}
	return _u
}

// SetSignature sets the "signature" field.
func (_u *PluginVersionUpdate) SetSignature(v string) *PluginVersionUpdate {
	_u.mutation.SetSignature(v)
	return _u
}

// SetNillableSignature sets the "signature" field if the given value is not nil.
func (_u *PluginVersionUpdate) SetNillableSignature(v *string) *PluginVersionUpdate {
	if v != nil {
		_u.SetSignature(*v)
	}
	return _u
}

// ClearSignature clears the value of the "signature" field.
func (_u *PluginVersionUpdate) ClearSignature() *PluginVersionUpdate {
	_u.mutation.ClearSignature()
	return _u
}

// SetSignKeyID sets the "sign_key_id" field.
func (_u *PluginVersionUpdate) SetSignKeyID(v string) *PluginVersionUpdate {
	_u.mutation.SetSignKeyID(v)
	return _u
}

// SetNillableSignKeyID sets the "sign_key_id" field if the given value is not nil.
func (_u *PluginVersionUpdate) SetNillableSignKeyID(v *string) *PluginVersionUpdate {
	if v != nil {
		_u.SetSignKeyID(*v)
	}
	return _u
}

// ClearSignKeyID clears the value of the "sign_key_id" field.
func (_u *PluginVersionUpdate) ClearSignKeyID() *PluginVersionUpdate {
	_u.mutation.ClearSignKeyID()
	return _u
}

// SetFileSize sets the "file_size" field.
func (_u *PluginVersionUpdate) SetFileSize(v int) *PluginVersionUpdate {
	_u.mutation.ResetFileSize()
	_u.mutation.SetFileSize(v)
	return _u
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (_u *PluginVersionUpdate) SetNillableFileSize(v *int) *PluginVersionUpdate {
	if v != nil {
		_u.SetFileSize(*v)
	}
	return _u
}

// AddFileSize adds value to the "file_size" field.
func (_u *PluginVersionUpdate) AddFileSize(v int) *PluginVersionUpdate {
	_u.mutation.AddFileSize(v)
	return _u
}

// SetMinAPIVersion sets the "min_api_version" field.
func (_u *PluginVersionUpdate) SetMinAPIVersion(v string) *PluginVersionUpdate {
	_u.mutation.SetMinAPIVersion(v)
	return _u
}

// SetNillableMinAPIVersion sets the "min_api_version" field if the given value is not nil.
func (_u *PluginVersionUpdate) SetNillableMinAPIVersion(v *string) *PluginVersionUpdate {
	if v != nil {
		_u.SetMinAPIVersion(*v)
	}
	return _u
}

// SetPluginAPIVersion sets the "plugin_api_version" field.
func (_u *PluginVersionUpdate) SetPluginAPIVersion(v string) *PluginVersionUpdate {
	_u.mutation.SetPluginAPIVersion(v)
	return _u
}

// SetNillablePluginAPIVersion sets the "plugin_api_version" field if the given value is not nil.
func (_u *PluginVersionUpdate) SetNillablePluginAPIVersion(v *string) *PluginVersionUpdate {
	if v != nil {
		_u.SetPluginAPIVersion(*v)
	}
	return _u
}

// SetMaxAPIVersion sets the "max_api_version" field.
func (_u *PluginVersionUpdate) SetMaxAPIVersion(v string) *PluginVersionUpdate {
	_u.mutation.SetMaxAPIVersion(v)
	return _u
}

// SetNillableMaxAPIVersion sets the "max_api_version" field if the given value is not nil.
func (_u *PluginVersionUpdate) SetNillableMaxAPIVersion(v *string) *PluginVersionUpdate {
	if v != nil {
		_u.SetMaxAPIVersion(*v)
	}
	return _u
}

// ClearMaxAPIVersion clears the value of the "max_api_version" field.
func (_u *PluginVersionUpdate) ClearMaxAPIVersion() *PluginVersionUpdate {
	_u.mutation.ClearMaxAPIVersion()
	return _u
}

// SetDependencies sets the "dependencies" field.
func (_u *PluginVersionUpdate) SetDependencies(v []map[string]string) *PluginVersionUpdate {
	_u.mutation.SetDependencies(v)
	return _u
}

// AppendDependencies appends value to the "dependencies" field.
func (_u *PluginVersionUpdate) AppendDependencies(v []map[string]string) *PluginVersionUpdate {
	_u.mutation.AppendDependencies(v)
	return _u
}

// ClearDependencies clears the value of the "dependencies" field.
func (_u *PluginVersionUpdate) ClearDependencies() *PluginVersionUpdate {
	_u.mutation.ClearDependencies()
	return _u
}

// SetCapabilities sets the "capabilities" field.
func (_u *PluginVersionUpdate) SetCapabilities(v []string) *PluginVersionUpdate {
	_u.mutation.SetCapabilities(v)
	return _u
}

// AppendCapabilities appends value to the "capabilities" field.
func (_u *PluginVersionUpdate) AppendCapabilities(v []string) *PluginVersionUpdate {
	_u.mutation.AppendCapabilities(v)
	return _u
}

// ClearCapabilities clears the value of the "capabilities" field.
func (_u *PluginVersionUpdate) ClearCapabilities() *PluginVersionUpdate {
	_u.mutation.ClearCapabilities()
	return _u
}

// SetStatus sets the "status" field.
func (_u *PluginVersionUpdate) SetStatus(v pluginversion.Status) *PluginVersionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PluginVersionUpdate) SetNillableStatus(v *pluginversion.Status) *PluginVersionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *PluginVersionUpdate) SetPublishedAt(v time.Time) *PluginVersionUpdate {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *PluginVersionUpdate) SetNillablePublishedAt(v *time.Time) *PluginVersionUpdate {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *PluginVersionUpdate) ClearPublishedAt() *PluginVersionUpdate {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PluginVersionUpdate) SetUpdatedAt(v time.Time) *PluginVersionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPlugin sets the "plugin" edge to the Plugin entity.
func (_u *PluginVersionUpdate) SetPlugin(v *Plugin) *PluginVersionUpdate {
	return _u.SetPluginID(v.ID)
}

// SetSubmissionID sets the "submission" edge to the Submission entity by ID.
func (_u *PluginVersionUpdate) SetSubmissionID(id uuid.UUID) *PluginVersionUpdate {
	_u.mutation.SetSubmissionID(id)
	return _u
}

// SetNillableSubmissionID sets the "submission" edge to the Submission entity by ID if the given value is not nil.
func (_u *PluginVersionUpdate) SetNillableSubmissionID(id *uuid.UUID) *PluginVersionUpdate {
	if id != nil {
		_u = _u.SetSubmissionID(*id)
	}
	return _u
}

// SetSubmission sets the "submission" edge to the Submission entity.
func (_u *PluginVersionUpdate) SetSubmission(v *Submission) *PluginVersionUpdate {
	return _u.SetSubmissionID(v.ID)
}

// Mutation returns the PluginVersionMutation object of the builder.
func (_u *PluginVersionUpdate) Mutation() *PluginVersionMutation {
	return _u.mutation
}

// ClearPlugin clears the "plugin" edge to the Plugin entity.
func (_u *PluginVersionUpdate) ClearPlugin() *PluginVersionUpdate {
	_u.mutation.ClearPlugin()
	return _u
}

// ClearSubmission clears the "submission" edge to the Submission entity.
func (_u *PluginVersionUpdate) ClearSubmission() *PluginVersionUpdate {
	_u.mutation.ClearSubmission()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PluginVersionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PluginVersionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PluginVersionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PluginVersionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PluginVersionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := pluginversion.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PluginVersionUpdate) check() error {
	if v, ok := _u.mutation.Version(); ok {
		if err := pluginversion.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "PluginVersion.version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WasmURL(); ok {
		if err := pluginversion.WasmURLValidator(v); err != nil {
			return &ValidationError{Name: "wasm_url", err: fmt.Errorf(`ent: validator failed for field "PluginVersion.wasm_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WasmHash(); ok {
		if err := pluginversion.WasmHashValidator(v); err != nil {
			return &ValidationError{Name: "wasm_hash", err: fmt.Errorf(`ent: validator failed for field "PluginVersion.wasm_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileSize(); ok {
		if err := pluginversion.FileSizeValidator(v); err != nil {
			return &ValidationError{Name: "file_size", err: fmt.Errorf(`ent: validator failed for field "PluginVersion.file_size": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MinAPIVersion(); ok {
		if err := pluginversion.MinAPIVersionValidator(v); err != nil {
			return &ValidationError{Name: "min_api_version", err: fmt.Errorf(`ent: validator failed for field "PluginVersion.min_api_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PluginAPIVersion(); ok {
		if err := pluginversion.PluginAPIVersionValidator(v); err != nil {
			return &ValidationError{Name: "plugin_api_version", err: fmt.Errorf(`ent: validator failed for field "PluginVersion.plugin_api_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := pluginversion.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PluginVersion.status": %w`, err)}
		}
	}
	if _u.mutation.PluginCleared() && len(_u.mutation.PluginIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PluginVersion.plugin"`)
	}
	return nil
}

func (_u *PluginVersionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pluginversion.Table, pluginversion.Columns, sqlgraph.NewFieldSpec(pluginversion.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(pluginversion.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Changelog(); ok {
		_spec.SetField(pluginversion.FieldChangelog, field.TypeString, value)
	}
	if _u.mutation.ChangelogCleared() {
		_spec.ClearField(pluginversion.FieldChangelog, field.TypeString)
	}
	if value, ok := _u.mutation.WasmURL(); ok {
		_spec.SetField(pluginversion.FieldWasmURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.WasmHash(); ok {
		_spec.SetField(pluginversion.FieldWasmHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Signature(); ok {
		_spec.SetField(pluginversion.FieldSignature, field.TypeString, value)
	}
	if _u.mutation.SignatureCleared() {
		_spec.ClearField(pluginversion.FieldSignature, field.TypeString)
	}
	if value, ok := _u.mutation.SignKeyID(); ok {
		_spec.SetField(pluginversion.FieldSignKeyID, field.TypeString, value)
	}
	if _u.mutation.SignKeyIDCleared() {
		_spec.ClearField(pluginversion.FieldSignKeyID, field.TypeString)
	}
	if value, ok := _u.mutation.FileSize(); ok {
		_spec.SetField(pluginversion.FieldFileSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFileSize(); ok {
		_spec.AddField(pluginversion.FieldFileSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MinAPIVersion(); ok {
		_spec.SetField(pluginversion.FieldMinAPIVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.PluginAPIVersion(); ok {
		_spec.SetField(pluginversion.FieldPluginAPIVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.MaxAPIVersion(); ok {
		_spec.SetField(pluginversion.FieldMaxAPIVersion, field.TypeString, value)
	}
	if _u.mutation.MaxAPIVersionCleared() {
		_spec.ClearField(pluginversion.FieldMaxAPIVersion, field.TypeString)
	}
	if value, ok := _u.mutation.Dependencies(); ok {
		_spec.SetField(pluginversion.FieldDependencies, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDependencies(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, pluginversion.FieldDependencies, value)
		})
	}
	if _u.mutation.DependenciesCleared() {
		_spec.ClearField(pluginversion.FieldDependencies, field.TypeJSON)
	}
	if value, ok := _u.mutation.Capabilities(); ok {
		_spec.SetField(pluginversion.FieldCapabilities, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCapabilities(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, pluginversion.FieldCapabilities, value)
		})
	}
	if _u.mutation.CapabilitiesCleared() {
		_spec.ClearField(pluginversion.FieldCapabilities, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(pluginversion.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(pluginversion.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(pluginversion.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(pluginversion.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.PluginCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pluginversion.PluginTable,
			Columns: []string{pluginversion.PluginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PluginIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pluginversion.PluginTable,
			Columns: []string{pluginversion.PluginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubmissionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   pluginversion.SubmissionTable,
			Columns: []string{pluginversion.SubmissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(submission.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubmissionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   pluginversion.SubmissionTable,
			Columns: []string{pluginversion.SubmissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(submission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pluginversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PluginVersionUpdateOne is the builder for updating a single PluginVersion entity.
type PluginVersionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PluginVersionMutation
}

// SetPluginID sets the "plugin_id" field.
func (_u *PluginVersionUpdateOne) SetPluginID(v uuid.UUID) *PluginVersionUpdateOne {
	_u.mutation.SetPluginID(v)
	return _u
}

// SetNillablePluginID sets the "plugin_id" field if the given value is not nil.
func (_u *PluginVersionUpdateOne) SetNillablePluginID(v *uuid.UUID) *PluginVersionUpdateOne {
	if v != nil {
		_u.SetPluginID(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *PluginVersionUpdateOne) SetVersion(v string) *PluginVersionUpdateOne {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *PluginVersionUpdateOne) SetNillableVersion(v *string) *PluginVersionUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetChangelog sets the "changelog" field.
func (_u *PluginVersionUpdateOne) SetChangelog(v string) *PluginVersionUpdateOne {
	_u.mutation.SetChangelog(v)
	return _u
}

// SetNillableChangelog sets the "changelog" field if the given value is not nil.
func (_u *PluginVersionUpdateOne) SetNillableChangelog(v *string) *PluginVersionUpdateOne {
	if v != nil {
		_u.SetChangelog(*v)
	}
	return _u
}

// ClearChangelog clears the value of the "changelog" field.
func (_u *PluginVersionUpdateOne) ClearChangelog() *PluginVersionUpdateOne {
	_u.mutation.ClearChangelog()
	return _u
}

// SetWasmURL sets the "wasm_url" field.
func (_u *PluginVersionUpdateOne) SetWasmURL(v string) *PluginVersionUpdateOne {
	_u.mutation.SetWasmURL(v)
	return _u
}

// SetNillableWasmURL sets the "wasm_url" field if the given value is not nil.
func (_u *PluginVersionUpdateOne) SetNillableWasmURL(v *string) *PluginVersionUpdateOne {
	if v != nil {
		_u.SetWasmURL(*v)
	}
	return _u
}

// SetWasmHash sets the "wasm_hash" field.
func (_u *PluginVersionUpdateOne) SetWasmHash(v string) *PluginVersionUpdateOne {
	_u.mutation.SetWasmHash(v)
	return _u
}

// SetNillableWasmHash sets the "wasm_hash" field if the given value is not nil.
func (_u *PluginVersionUpdateOne) SetNillableWasmHash(v *string) *PluginVersionUpdateOne {
	if v != nil {
		_u.SetWasmHash(*v)
	}
	return _u
}

// SetSignature sets the "signature" field.
func (_u *PluginVersionUpdateOne) SetSignature(v string) *PluginVersionUpdateOne {
	_u.mutation.SetSignature(v)
	return _u
}

// SetNillableSignature sets the "signature" field if the given value is not nil.
func (_u *PluginVersionUpdateOne) SetNillableSignature(v *string) *PluginVersionUpdateOne {
	if v != nil {
		_u.SetSignature(*v)
	}
	return _u
}

// ClearSignature clears the value of the "signature" field.
func (_u *PluginVersionUpdateOne) ClearSignature() *PluginVersionUpdateOne {
	_u.mutation.ClearSignature()
	return _u
}

// SetSignKeyID sets the "sign_key_id" field.
func (_u *PluginVersionUpdateOne) SetSignKeyID(v string) *PluginVersionUpdateOne {
	_u.mutation.SetSignKeyID(v)
	return _u
}

// SetNillableSignKeyID sets the "sign_key_id" field if the given value is not nil.
func (_u *PluginVersionUpdateOne) SetNillableSignKeyID(v *string) *PluginVersionUpdateOne {
	if v != nil {
		_u.SetSignKeyID(*v)
	}
	return _u
}

// ClearSignKeyID clears the value of the "sign_key_id" field.
func (_u *PluginVersionUpdateOne) ClearSignKeyID() *PluginVersionUpdateOne {
	_u.mutation.ClearSignKeyID()
	return _u
}

// SetFileSize sets the "file_size" field.
func (_u *PluginVersionUpdateOne) SetFileSize(v int) *PluginVersionUpdateOne {
	_u.mutation.ResetFileSize()
	_u.mutation.SetFileSize(v)
	return _u
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (_u *PluginVersionUpdateOne) SetNillableFileSize(v *int) *PluginVersionUpdateOne {
	if v != nil {
		_u.SetFileSize(*v)
	}
	return _u
}

// AddFileSize adds value to the "file_size" field.
func (_u *PluginVersionUpdateOne) AddFileSize(v int) *PluginVersionUpdateOne {
	_u.mutation.AddFileSize(v)
	return _u
}

// SetMinAPIVersion sets the "min_api_version" field.
func (_u *PluginVersionUpdateOne) SetMinAPIVersion(v string) *PluginVersionUpdateOne {
	_u.mutation.SetMinAPIVersion(v)
	return _u
}

// SetNillableMinAPIVersion sets the "min_api_version" field if the given value is not nil.
func (_u *PluginVersionUpdateOne) SetNillableMinAPIVersion(v *string) *PluginVersionUpdateOne {
	if v != nil {
		_u.SetMinAPIVersion(*v)
	}
	return _u
}

// SetPluginAPIVersion sets the "plugin_api_version" field.
func (_u *PluginVersionUpdateOne) SetPluginAPIVersion(v string) *PluginVersionUpdateOne {
	_u.mutation.SetPluginAPIVersion(v)
	return _u
}

// SetNillablePluginAPIVersion sets the "plugin_api_version" field if the given value is not nil.
func (_u *PluginVersionUpdateOne) SetNillablePluginAPIVersion(v *string) *PluginVersionUpdateOne {
	if v != nil {
		_u.SetPluginAPIVersion(*v)
	}
	return _u
}

// SetMaxAPIVersion sets the "max_api_version" field.
func (_u *PluginVersionUpdateOne) SetMaxAPIVersion(v string) *PluginVersionUpdateOne {
	_u.mutation.SetMaxAPIVersion(v)
	return _u
}

// SetNillableMaxAPIVersion sets the "max_api_version" field if the given value is not nil.
func (_u *PluginVersionUpdateOne) SetNillableMaxAPIVersion(v *string) *PluginVersionUpdateOne {
	if v != nil {
		_u.SetMaxAPIVersion(*v)
	}
	return _u
}

// ClearMaxAPIVersion clears the value of the "max_api_version" field.
func (_u *PluginVersionUpdateOne) ClearMaxAPIVersion() *PluginVersionUpdateOne {
	_u.mutation.ClearMaxAPIVersion()
	return _u
}

// SetDependencies sets the "dependencies" field.
func (_u *PluginVersionUpdateOne) SetDependencies(v []map[string]string) *PluginVersionUpdateOne {
	_u.mutation.SetDependencies(v)
	return _u
}

// AppendDependencies appends value to the "dependencies" field.
func (_u *PluginVersionUpdateOne) AppendDependencies(v []map[string]string) *PluginVersionUpdateOne {
	_u.mutation.AppendDependencies(v)
	return _u
}

// ClearDependencies clears the value of the "dependencies" field.
func (_u *PluginVersionUpdateOne) ClearDependencies() *PluginVersionUpdateOne {
	_u.mutation.ClearDependencies()
	return _u
}

// SetCapabilities sets the "capabilities" field.
func (_u *PluginVersionUpdateOne) SetCapabilities(v []string) *PluginVersionUpdateOne {
	_u.mutation.SetCapabilities(v)
	return _u
}

// AppendCapabilities appends value to the "capabilities" field.
func (_u *PluginVersionUpdateOne) AppendCapabilities(v []string) *PluginVersionUpdateOne {
	_u.mutation.AppendCapabilities(v)
	return _u
}

// ClearCapabilities clears the value of the "capabilities" field.
func (_u *PluginVersionUpdateOne) ClearCapabilities() *PluginVersionUpdateOne {
	_u.mutation.ClearCapabilities()
	return _u
}

// SetStatus sets the "status" field.
func (_u *PluginVersionUpdateOne) SetStatus(v pluginversion.Status) *PluginVersionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PluginVersionUpdateOne) SetNillableStatus(v *pluginversion.Status) *PluginVersionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *PluginVersionUpdateOne) SetPublishedAt(v time.Time) *PluginVersionUpdateOne {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *PluginVersionUpdateOne) SetNillablePublishedAt(v *time.Time) *PluginVersionUpdateOne {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *PluginVersionUpdateOne) ClearPublishedAt() *PluginVersionUpdateOne {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PluginVersionUpdateOne) SetUpdatedAt(v time.Time) *PluginVersionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPlugin sets the "plugin" edge to the Plugin entity.
func (_u *PluginVersionUpdateOne) SetPlugin(v *Plugin) *PluginVersionUpdateOne {
	return _u.SetPluginID(v.ID)
}

// SetSubmissionID sets the "submission" edge to the Submission entity by ID.
func (_u *PluginVersionUpdateOne) SetSubmissionID(id uuid.UUID) *PluginVersionUpdateOne {
	_u.mutation.SetSubmissionID(id)
	return _u
}

// SetNillableSubmissionID sets the "submission" edge to the Submission entity by ID if the given value is not nil.
func (_u *PluginVersionUpdateOne) SetNillableSubmissionID(id *uuid.UUID) *PluginVersionUpdateOne {
	if id != nil {
		_u = _u.SetSubmissionID(*id)
	}
	return _u
}

// SetSubmission sets the "submission" edge to the Submission entity.
func (_u *PluginVersionUpdateOne) SetSubmission(v *Submission) *PluginVersionUpdateOne {
	return _u.SetSubmissionID(v.ID)
}

// Mutation returns the PluginVersionMutation object of the builder.
func (_u *PluginVersionUpdateOne) Mutation() *PluginVersionMutation {
	return _u.mutation
}

// ClearPlugin clears the "plugin" edge to the Plugin entity.
func (_u *PluginVersionUpdateOne) ClearPlugin() *PluginVersionUpdateOne {
	_u.mutation.ClearPlugin()
	return _u
}

// ClearSubmission clears the "submission" edge to the Submission entity.
func (_u *PluginVersionUpdateOne) ClearSubmission() *PluginVersionUpdateOne {
	_u.mutation.ClearSubmission()
	return _u
}

// Where appends a list predicates to the PluginVersionUpdate builder.
func (_u *PluginVersionUpdateOne) Where(ps ...predicate.PluginVersion) *PluginVersionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PluginVersionUpdateOne) Select(field string, fields ...string) *PluginVersionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PluginVersion entity.
func (_u *PluginVersionUpdateOne) Save(ctx context.Context) (*PluginVersion, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PluginVersionUpdateOne) SaveX(ctx context.Context) *PluginVersion {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PluginVersionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PluginVersionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PluginVersionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := pluginversion.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PluginVersionUpdateOne) check() error {
	if v, ok := _u.mutation.Version(); ok {
		if err := pluginversion.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "PluginVersion.version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WasmURL(); ok {
		if err := pluginversion.WasmURLValidator(v); err != nil {
			return &ValidationError{Name: "wasm_url", err: fmt.Errorf(`ent: validator failed for field "PluginVersion.wasm_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WasmHash(); ok {
		if err := pluginversion.WasmHashValidator(v); err != nil {
			return &ValidationError{Name: "wasm_hash", err: fmt.Errorf(`ent: validator failed for field "PluginVersion.wasm_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileSize(); ok {
		if err := pluginversion.FileSizeValidator(v); err != nil {
			return &ValidationError{Name: "file_size", err: fmt.Errorf(`ent: validator failed for field "PluginVersion.file_size": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MinAPIVersion(); ok {
		if err := pluginversion.MinAPIVersionValidator(v); err != nil {
			return &ValidationError{Name: "min_api_version", err: fmt.Errorf(`ent: validator failed for field "PluginVersion.min_api_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PluginAPIVersion(); ok {
		if err := pluginversion.PluginAPIVersionValidator(v); err != nil {
			return &ValidationError{Name: "plugin_api_version", err: fmt.Errorf(`ent: validator failed for field "PluginVersion.plugin_api_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := pluginversion.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PluginVersion.status": %w`, err)}
		}
	}
	if _u.mutation.PluginCleared() && len(_u.mutation.PluginIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PluginVersion.plugin"`)
	}
	return nil
}

func (_u *PluginVersionUpdateOne) sqlSave(ctx context.Context) (_node *PluginVersion, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pluginversion.Table, pluginversion.Columns, sqlgraph.NewFieldSpec(pluginversion.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PluginVersion.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pluginversion.FieldID)
		for _, f := range fields {
			if !pluginversion.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pluginversion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(pluginversion.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Changelog(); ok {
		_spec.SetField(pluginversion.FieldChangelog, field.TypeString, value)
	}
	if _u.mutation.ChangelogCleared() {
		_spec.ClearField(pluginversion.FieldChangelog, field.TypeString)
	}
	if value, ok := _u.mutation.WasmURL(); ok {
		_spec.SetField(pluginversion.FieldWasmURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.WasmHash(); ok {
		_spec.SetField(pluginversion.FieldWasmHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Signature(); ok {
		_spec.SetField(pluginversion.FieldSignature, field.TypeString, value)
	}
	if _u.mutation.SignatureCleared() {
		_spec.ClearField(pluginversion.FieldSignature, field.TypeString)
	}
	if value, ok := _u.mutation.SignKeyID(); ok {
		_spec.SetField(pluginversion.FieldSignKeyID, field.TypeString, value)
	}
	if _u.mutation.SignKeyIDCleared() {
		_spec.ClearField(pluginversion.FieldSignKeyID, field.TypeString)
	}
	if value, ok := _u.mutation.FileSize(); ok {
		_spec.SetField(pluginversion.FieldFileSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFileSize(); ok {
		_spec.AddField(pluginversion.FieldFileSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MinAPIVersion(); ok {
		_spec.SetField(pluginversion.FieldMinAPIVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.PluginAPIVersion(); ok {
		_spec.SetField(pluginversion.FieldPluginAPIVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.MaxAPIVersion(); ok {
		_spec.SetField(pluginversion.FieldMaxAPIVersion, field.TypeString, value)
	}
	if _u.mutation.MaxAPIVersionCleared() {
		_spec.ClearField(pluginversion.FieldMaxAPIVersion, field.TypeString)
	}
	if value, ok := _u.mutation.Dependencies(); ok {
		_spec.SetField(pluginversion.FieldDependencies, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDependencies(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, pluginversion.FieldDependencies, value)
		})
	}
	if _u.mutation.DependenciesCleared() {
		_spec.ClearField(pluginversion.FieldDependencies, field.TypeJSON)
	}
	if value, ok := _u.mutation.Capabilities(); ok {
		_spec.SetField(pluginversion.FieldCapabilities, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCapabilities(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, pluginversion.FieldCapabilities, value)
		})
	}
	if _u.mutation.CapabilitiesCleared() {
		_spec.ClearField(pluginversion.FieldCapabilities, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(pluginversion.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(pluginversion.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(pluginversion.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(pluginversion.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.PluginCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pluginversion.PluginTable,
			Columns: []string{pluginversion.PluginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PluginIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pluginversion.PluginTable,
			Columns: []string{pluginversion.PluginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubmissionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   pluginversion.SubmissionTable,
			Columns: []string{pluginversion.SubmissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(submission.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubmissionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   pluginversion.SubmissionTable,
			Columns: []string{pluginversion.SubmissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(submission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PluginVersion{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pluginversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
