// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/IanShaw027/sub2api-plugin-market/ent/downloadlog"
	"github.com/IanShaw027/sub2api-plugin-market/ent/plugin"
	"github.com/IanShaw027/sub2api-plugin-market/ent/pluginversion"
	"github.com/IanShaw027/sub2api-plugin-market/ent/predicate"
	"github.com/IanShaw027/sub2api-plugin-market/ent/submission"
	"github.com/IanShaw027/sub2api-plugin-market/ent/syncjob"
	"github.com/google/uuid"
)

// PluginUpdate is the builder for updating Plugin entities.
type PluginUpdate struct {
	config
	hooks    []Hook
	mutation *PluginMutation
}

// Where appends a list predicates to the PluginUpdate builder.
func (_u *PluginUpdate) Where(ps ...predicate.Plugin) *PluginUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *PluginUpdate) SetName(v string) *PluginUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PluginUpdate) SetNillableName(v *string) *PluginUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *PluginUpdate) SetDisplayName(v string) *PluginUpdate {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *PluginUpdate) SetNillableDisplayName(v *string) *PluginUpdate {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *PluginUpdate) SetDescription(v string) *PluginUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PluginUpdate) SetNillableDescription(v *string) *PluginUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetAuthor sets the "author" field.
func (_u *PluginUpdate) SetAuthor(v string) *PluginUpdate {
	_u.mutation.SetAuthor(v)
	return _u
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (_u *PluginUpdate) SetNillableAuthor(v *string) *PluginUpdate {
	if v != nil {
		_u.SetAuthor(*v)
	}
	return _u
}

// SetRepositoryURL sets the "repository_url" field.
func (_u *PluginUpdate) SetRepositoryURL(v string) *PluginUpdate {
	_u.mutation.SetRepositoryURL(v)
	return _u
}

// SetNillableRepositoryURL sets the "repository_url" field if the given value is not nil.
func (_u *PluginUpdate) SetNillableRepositoryURL(v *string) *PluginUpdate {
	if v != nil {
		_u.SetRepositoryURL(*v)
	}
	return _u
}

// ClearRepositoryURL clears the value of the "repository_url" field.
func (_u *PluginUpdate) ClearRepositoryURL() *PluginUpdate {
	_u.mutation.ClearRepositoryURL()
	return _u
}

// SetHomepageURL sets the "homepage_url" field.
func (_u *PluginUpdate) SetHomepageURL(v string) *PluginUpdate {
	_u.mutation.SetHomepageURL(v)
	return _u
}

// SetNillableHomepageURL sets the "homepage_url" field if the given value is not nil.
func (_u *PluginUpdate) SetNillableHomepageURL(v *string) *PluginUpdate {
	if v != nil {
		_u.SetHomepageURL(*v)
	}
	return _u
}

// ClearHomepageURL clears the value of the "homepage_url" field.
func (_u *PluginUpdate) ClearHomepageURL() *PluginUpdate {
	_u.mutation.ClearHomepageURL()
	return _u
}

// SetLicense sets the "license" field.
func (_u *PluginUpdate) SetLicense(v string) *PluginUpdate {
	_u.mutation.SetLicense(v)
	return _u
}

// SetNillableLicense sets the "license" field if the given value is not nil.
func (_u *PluginUpdate) SetNillableLicense(v *string) *PluginUpdate {
	if v != nil {
		_u.SetLicense(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *PluginUpdate) SetCategory(v plugin.Category) *PluginUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *PluginUpdate) SetNillableCategory(v *plugin.Category) *PluginUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetTags sets the "tags" field.
func (_u *PluginUpdate) SetTags(v []string) *PluginUpdate {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *PluginUpdate) AppendTags(v []string) *PluginUpdate {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *PluginUpdate) ClearTags() *PluginUpdate {
	_u.mutation.ClearTags()
	return _u
}

// SetIsOfficial sets the "is_official" field.
func (_u *PluginUpdate) SetIsOfficial(v bool) *PluginUpdate {
	_u.mutation.SetIsOfficial(v)
	return _u
}

// SetNillableIsOfficial sets the "is_official" field if the given value is not nil.
func (_u *PluginUpdate) SetNillableIsOfficial(v *bool) *PluginUpdate {
	if v != nil {
		_u.SetIsOfficial(*v)
	}
	return _u
}

// SetIsVerified sets the "is_verified" field.
func (_u *PluginUpdate) SetIsVerified(v bool) *PluginUpdate {
	_u.mutation.SetIsVerified(v)
	return _u
}

// SetNillableIsVerified sets the "is_verified" field if the given value is not nil.
func (_u *PluginUpdate) SetNillableIsVerified(v *bool) *PluginUpdate {
	if v != nil {
		_u.SetIsVerified(*v)
	}
	return _u
}

// SetDownloadCount sets the "download_count" field.
func (_u *PluginUpdate) SetDownloadCount(v int) *PluginUpdate {
	_u.mutation.ResetDownloadCount()
	_u.mutation.SetDownloadCount(v)
	return _u
}

// SetNillableDownloadCount sets the "download_count" field if the given value is not nil.
func (_u *PluginUpdate) SetNillableDownloadCount(v *int) *PluginUpdate {
	if v != nil {
		_u.SetDownloadCount(*v)
	}
	return _u
}

// AddDownloadCount adds value to the "download_count" field.
func (_u *PluginUpdate) AddDownloadCount(v int) *PluginUpdate {
	_u.mutation.AddDownloadCount(v)
	return _u
}

// SetRating sets the "rating" field.
func (_u *PluginUpdate) SetRating(v float64) *PluginUpdate {
	_u.mutation.ResetRating()
	_u.mutation.SetRating(v)
	return _u
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (_u *PluginUpdate) SetNillableRating(v *float64) *PluginUpdate {
	if v != nil {
		_u.SetRating(*v)
	}
	return _u
}

// AddRating adds value to the "rating" field.
func (_u *PluginUpdate) AddRating(v float64) *PluginUpdate {
	_u.mutation.AddRating(v)
	return _u
}

// ClearRating clears the value of the "rating" field.
func (_u *PluginUpdate) ClearRating() *PluginUpdate {
	_u.mutation.ClearRating()
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *PluginUpdate) SetSourceType(v plugin.SourceType) *PluginUpdate {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *PluginUpdate) SetNillableSourceType(v *plugin.SourceType) *PluginUpdate {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetGithubRepoURL sets the "github_repo_url" field.
func (_u *PluginUpdate) SetGithubRepoURL(v string) *PluginUpdate {
	_u.mutation.SetGithubRepoURL(v)
	return _u
}

// SetNillableGithubRepoURL sets the "github_repo_url" field if the given value is not nil.
func (_u *PluginUpdate) SetNillableGithubRepoURL(v *string) *PluginUpdate {
	if v != nil {
		_u.SetGithubRepoURL(*v)
	}
	return _u
}

// ClearGithubRepoURL clears the value of the "github_repo_url" field.
func (_u *PluginUpdate) ClearGithubRepoURL() *PluginUpdate {
	_u.mutation.ClearGithubRepoURL()
	return _u
}

// SetGithubRepoNormalized sets the "github_repo_normalized" field.
func (_u *PluginUpdate) SetGithubRepoNormalized(v string) *PluginUpdate {
	_u.mutation.SetGithubRepoNormalized(v)
	return _u
}

// SetNillableGithubRepoNormalized sets the "github_repo_normalized" field if the given value is not nil.
func (_u *PluginUpdate) SetNillableGithubRepoNormalized(v *string) *PluginUpdate {
	if v != nil {
		_u.SetGithubRepoNormalized(*v)
	}
	return _u
}

// ClearGithubRepoNormalized clears the value of the "github_repo_normalized" field.
func (_u *PluginUpdate) ClearGithubRepoNormalized() *PluginUpdate {
	_u.mutation.ClearGithubRepoNormalized()
	return _u
}

// SetAutoUpgradeEnabled sets the "auto_upgrade_enabled" field.
func (_u *PluginUpdate) SetAutoUpgradeEnabled(v bool) *PluginUpdate {
	_u.mutation.SetAutoUpgradeEnabled(v)
	return _u
}

// SetNillableAutoUpgradeEnabled sets the "auto_upgrade_enabled" field if the given value is not nil.
func (_u *PluginUpdate) SetNillableAutoUpgradeEnabled(v *bool) *PluginUpdate {
	if v != nil {
		_u.SetAutoUpgradeEnabled(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PluginUpdate) SetStatus(v plugin.Status) *PluginUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PluginUpdate) SetNillableStatus(v *plugin.Status) *PluginUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PluginUpdate) SetUpdatedAt(v time.Time) *PluginUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddVersionIDs adds the "versions" edge to the PluginVersion entity by IDs.
func (_u *PluginUpdate) AddVersionIDs(ids ...uuid.UUID) *PluginUpdate {
	_u.mutation.AddVersionIDs(ids...)
	return _u
}

// AddVersions adds the "versions" edges to the PluginVersion entity.
func (_u *PluginUpdate) AddVersions(v ...*PluginVersion) *PluginUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddVersionIDs(ids...)
}

// AddSubmissionIDs adds the "submissions" edge to the Submission entity by IDs.
func (_u *PluginUpdate) AddSubmissionIDs(ids ...uuid.UUID) *PluginUpdate {
	_u.mutation.AddSubmissionIDs(ids...)
	return _u
}

// AddSubmissions adds the "submissions" edges to the Submission entity.
func (_u *PluginUpdate) AddSubmissions(v ...*Submission) *PluginUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSubmissionIDs(ids...)
}

// AddDownloadLogIDs adds the "download_logs" edge to the DownloadLog entity by IDs.
func (_u *PluginUpdate) AddDownloadLogIDs(ids ...uuid.UUID) *PluginUpdate {
	_u.mutation.AddDownloadLogIDs(ids...)
	return _u
}

// AddDownloadLogs adds the "download_logs" edges to the DownloadLog entity.
func (_u *PluginUpdate) AddDownloadLogs(v ...*DownloadLog) *PluginUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDownloadLogIDs(ids...)
}

// AddSyncJobIDs adds the "sync_jobs" edge to the SyncJob entity by IDs.
func (_u *PluginUpdate) AddSyncJobIDs(ids ...uuid.UUID) *PluginUpdate {
	_u.mutation.AddSyncJobIDs(ids...)
	return _u
}

// AddSyncJobs adds the "sync_jobs" edges to the SyncJob entity.
func (_u *PluginUpdate) AddSyncJobs(v ...*SyncJob) *PluginUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSyncJobIDs(ids...)
}

// Mutation returns the PluginMutation object of the builder.
func (_u *PluginUpdate) Mutation() *PluginMutation {
	return _u.mutation
}

// ClearVersions clears all "versions" edges to the PluginVersion entity.
func (_u *PluginUpdate) ClearVersions() *PluginUpdate {
	_u.mutation.ClearVersions()
	return _u
}

// RemoveVersionIDs removes the "versions" edge to PluginVersion entities by IDs.
func (_u *PluginUpdate) RemoveVersionIDs(ids ...uuid.UUID) *PluginUpdate {
	_u.mutation.RemoveVersionIDs(ids...)
	return _u
}

// RemoveVersions removes "versions" edges to PluginVersion entities.
func (_u *PluginUpdate) RemoveVersions(v ...*PluginVersion) *PluginUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveVersionIDs(ids...)
}

// ClearSubmissions clears all "submissions" edges to the Submission entity.
func (_u *PluginUpdate) ClearSubmissions() *PluginUpdate {
	_u.mutation.ClearSubmissions()
	return _u
}

// RemoveSubmissionIDs removes the "submissions" edge to Submission entities by IDs.
func (_u *PluginUpdate) RemoveSubmissionIDs(ids ...uuid.UUID) *PluginUpdate {
	_u.mutation.RemoveSubmissionIDs(ids...)
	return _u
}

// RemoveSubmissions removes "submissions" edges to Submission entities.
func (_u *PluginUpdate) RemoveSubmissions(v ...*Submission) *PluginUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSubmissionIDs(ids...)
}

// ClearDownloadLogs clears all "download_logs" edges to the DownloadLog entity.
func (_u *PluginUpdate) ClearDownloadLogs() *PluginUpdate {
	_u.mutation.ClearDownloadLogs()
	return _u
}

// RemoveDownloadLogIDs removes the "download_logs" edge to DownloadLog entities by IDs.
func (_u *PluginUpdate) RemoveDownloadLogIDs(ids ...uuid.UUID) *PluginUpdate {
	_u.mutation.RemoveDownloadLogIDs(ids...)
	return _u
}

// RemoveDownloadLogs removes "download_logs" edges to DownloadLog entities.
func (_u *PluginUpdate) RemoveDownloadLogs(v ...*DownloadLog) *PluginUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDownloadLogIDs(ids...)
}

// ClearSyncJobs clears all "sync_jobs" edges to the SyncJob entity.
func (_u *PluginUpdate) ClearSyncJobs() *PluginUpdate {
	_u.mutation.ClearSyncJobs()
	return _u
}

// RemoveSyncJobIDs removes the "sync_jobs" edge to SyncJob entities by IDs.
func (_u *PluginUpdate) RemoveSyncJobIDs(ids ...uuid.UUID) *PluginUpdate {
	_u.mutation.RemoveSyncJobIDs(ids...)
	return _u
}

// RemoveSyncJobs removes "sync_jobs" edges to SyncJob entities.
func (_u *PluginUpdate) RemoveSyncJobs(v ...*SyncJob) *PluginUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSyncJobIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PluginUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PluginUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PluginUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PluginUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PluginUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := plugin.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PluginUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := plugin.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Plugin.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := plugin.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "Plugin.display_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Author(); ok {
		if err := plugin.AuthorValidator(v); err != nil {
			return &ValidationError{Name: "author", err: fmt.Errorf(`ent: validator failed for field "Plugin.author": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Category(); ok {
		if err := plugin.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "Plugin.category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DownloadCount(); ok {
		if err := plugin.DownloadCountValidator(v); err != nil {
			return &ValidationError{Name: "download_count", err: fmt.Errorf(`ent: validator failed for field "Plugin.download_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Rating(); ok {
		if err := plugin.RatingValidator(v); err != nil {
			return &ValidationError{Name: "rating", err: fmt.Errorf(`ent: validator failed for field "Plugin.rating": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceType(); ok {
		if err := plugin.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "Plugin.source_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := plugin.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Plugin.status": %w`, err)}
		}
	}
	return nil
}

func (_u *PluginUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(plugin.Table, plugin.Columns, sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(plugin.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(plugin.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(plugin.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Author(); ok {
		_spec.SetField(plugin.FieldAuthor, field.TypeString, value)
	}
	if value, ok := _u.mutation.RepositoryURL(); ok {
		_spec.SetField(plugin.FieldRepositoryURL, field.TypeString, value)
	}
	if _u.mutation.RepositoryURLCleared() {
		_spec.ClearField(plugin.FieldRepositoryURL, field.TypeString)
	}
	if value, ok := _u.mutation.HomepageURL(); ok {
		_spec.SetField(plugin.FieldHomepageURL, field.TypeString, value)
	}
	if _u.mutation.HomepageURLCleared() {
		_spec.ClearField(plugin.FieldHomepageURL, field.TypeString)
	}
	if value, ok := _u.mutation.License(); ok {
		_spec.SetField(plugin.FieldLicense, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(plugin.FieldCategory, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(plugin.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, plugin.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(plugin.FieldTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.IsOfficial(); ok {
		_spec.SetField(plugin.FieldIsOfficial, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsVerified(); ok {
		_spec.SetField(plugin.FieldIsVerified, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DownloadCount(); ok {
		_spec.SetField(plugin.FieldDownloadCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDownloadCount(); ok {
		_spec.AddField(plugin.FieldDownloadCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Rating(); ok {
		_spec.SetField(plugin.FieldRating, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRating(); ok {
		_spec.AddField(plugin.FieldRating, field.TypeFloat64, value)
	}
	if _u.mutation.RatingCleared() {
		_spec.ClearField(plugin.FieldRating, field.TypeFloat64)
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(plugin.FieldSourceType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.GithubRepoURL(); ok {
		_spec.SetField(plugin.FieldGithubRepoURL, field.TypeString, value)
	}
	if _u.mutation.GithubRepoURLCleared() {
		_spec.ClearField(plugin.FieldGithubRepoURL, field.TypeString)
	}
	if value, ok := _u.mutation.GithubRepoNormalized(); ok {
		_spec.SetField(plugin.FieldGithubRepoNormalized, field.TypeString, value)
	}
	if _u.mutation.GithubRepoNormalizedCleared() {
		_spec.ClearField(plugin.FieldGithubRepoNormalized, field.TypeString)
	}
	if value, ok := _u.mutation.AutoUpgradeEnabled(); ok {
		_spec.SetField(plugin.FieldAutoUpgradeEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(plugin.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(plugin.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.VersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plugin.VersionsTable,
			Columns: []string{plugin.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pluginversion.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedVersionsIDs(); len(nodes) > 0 && !_u.mutation.VersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plugin.VersionsTable,
			Columns: []string{plugin.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pluginversion.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VersionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plugin.VersionsTable,
			Columns: []string{plugin.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pluginversion.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubmissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plugin.SubmissionsTable,
			Columns: []string{plugin.SubmissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(submission.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSubmissionsIDs(); len(nodes) > 0 && !_u.mutation.SubmissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plugin.SubmissionsTable,
			Columns: []string{plugin.SubmissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(submission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubmissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plugin.SubmissionsTable,
			Columns: []string{plugin.SubmissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(submission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DownloadLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plugin.DownloadLogsTable,
			Columns: []string{plugin.DownloadLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(downloadlog.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDownloadLogsIDs(); len(nodes) > 0 && !_u.mutation.DownloadLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plugin.DownloadLogsTable,
			Columns: []string{plugin.DownloadLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(downloadlog.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DownloadLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plugin.DownloadLogsTable,
			Columns: []string{plugin.DownloadLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(downloadlog.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SyncJobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plugin.SyncJobsTable,
			Columns: []string{plugin.SyncJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(syncjob.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSyncJobsIDs(); len(nodes) > 0 && !_u.mutation.SyncJobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plugin.SyncJobsTable,
			Columns: []string{plugin.SyncJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(syncjob.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SyncJobsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plugin.SyncJobsTable,
			Columns: []string{plugin.SyncJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(syncjob.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{plugin.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PluginUpdateOne is the builder for updating a single Plugin entity.
type PluginUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PluginMutation
}

// SetName sets the "name" field.
func (_u *PluginUpdateOne) SetName(v string) *PluginUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PluginUpdateOne) SetNillableName(v *string) *PluginUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *PluginUpdateOne) SetDisplayName(v string) *PluginUpdateOne {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *PluginUpdateOne) SetNillableDisplayName(v *string) *PluginUpdateOne {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *PluginUpdateOne) SetDescription(v string) *PluginUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PluginUpdateOne) SetNillableDescription(v *string) *PluginUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetAuthor sets the "author" field.
func (_u *PluginUpdateOne) SetAuthor(v string) *PluginUpdateOne {
	_u.mutation.SetAuthor(v)
	return _u
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (_u *PluginUpdateOne) SetNillableAuthor(v *string) *PluginUpdateOne {
	if v != nil {
		_u.SetAuthor(*v)
	}
	return _u
}

// SetRepositoryURL sets the "repository_url" field.
func (_u *PluginUpdateOne) SetRepositoryURL(v string) *PluginUpdateOne {
	_u.mutation.SetRepositoryURL(v)
	return _u
}

// SetNillableRepositoryURL sets the "repository_url" field if the given value is not nil.
func (_u *PluginUpdateOne) SetNillableRepositoryURL(v *string) *PluginUpdateOne {
	if v != nil {
		_u.SetRepositoryURL(*v)
	}
	return _u
}

// ClearRepositoryURL clears the value of the "repository_url" field.
func (_u *PluginUpdateOne) ClearRepositoryURL() *PluginUpdateOne {
	_u.mutation.ClearRepositoryURL()
	return _u
}

// SetHomepageURL sets the "homepage_url" field.
func (_u *PluginUpdateOne) SetHomepageURL(v string) *PluginUpdateOne {
	_u.mutation.SetHomepageURL(v)
	return _u
}

// SetNillableHomepageURL sets the "homepage_url" field if the given value is not nil.
func (_u *PluginUpdateOne) SetNillableHomepageURL(v *string) *PluginUpdateOne {
	if v != nil {
		_u.SetHomepageURL(*v)
	}
	return _u
}

// ClearHomepageURL clears the value of the "homepage_url" field.
func (_u *PluginUpdateOne) ClearHomepageURL() *PluginUpdateOne {
	_u.mutation.ClearHomepageURL()
	return _u
}

// SetLicense sets the "license" field.
func (_u *PluginUpdateOne) SetLicense(v string) *PluginUpdateOne {
	_u.mutation.SetLicense(v)
	return _u
}

// SetNillableLicense sets the "license" field if the given value is not nil.
func (_u *PluginUpdateOne) SetNillableLicense(v *string) *PluginUpdateOne {
	if v != nil {
		_u.SetLicense(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *PluginUpdateOne) SetCategory(v plugin.Category) *PluginUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *PluginUpdateOne) SetNillableCategory(v *plugin.Category) *PluginUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetTags sets the "tags" field.
func (_u *PluginUpdateOne) SetTags(v []string) *PluginUpdateOne {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *PluginUpdateOne) AppendTags(v []string) *PluginUpdateOne {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *PluginUpdateOne) ClearTags() *PluginUpdateOne {
	_u.mutation.ClearTags()
	return _u
}

// SetIsOfficial sets the "is_official" field.
func (_u *PluginUpdateOne) SetIsOfficial(v bool) *PluginUpdateOne {
	_u.mutation.SetIsOfficial(v)
	return _u
}

// SetNillableIsOfficial sets the "is_official" field if the given value is not nil.
func (_u *PluginUpdateOne) SetNillableIsOfficial(v *bool) *PluginUpdateOne {
	if v != nil {
		_u.SetIsOfficial(*v)
	}
	return _u
}

// SetIsVerified sets the "is_verified" field.
func (_u *PluginUpdateOne) SetIsVerified(v bool) *PluginUpdateOne {
	_u.mutation.SetIsVerified(v)
	return _u
}

// SetNillableIsVerified sets the "is_verified" field if the given value is not nil.
func (_u *PluginUpdateOne) SetNillableIsVerified(v *bool) *PluginUpdateOne {
	if v != nil {
		_u.SetIsVerified(*v)
	}
	return _u
}

// SetDownloadCount sets the "download_count" field.
func (_u *PluginUpdateOne) SetDownloadCount(v int) *PluginUpdateOne {
	_u.mutation.ResetDownloadCount()
	_u.mutation.SetDownloadCount(v)
	return _u
}

// SetNillableDownloadCount sets the "download_count" field if the given value is not nil.
func (_u *PluginUpdateOne) SetNillableDownloadCount(v *int) *PluginUpdateOne {
	if v != nil {
		_u.SetDownloadCount(*v)
	}
	return _u
}

// AddDownloadCount adds value to the "download_count" field.
func (_u *PluginUpdateOne) AddDownloadCount(v int) *PluginUpdateOne {
	_u.mutation.AddDownloadCount(v)
	return _u
}

// SetRating sets the "rating" field.
func (_u *PluginUpdateOne) SetRating(v float64) *PluginUpdateOne {
	_u.mutation.ResetRating()
	_u.mutation.SetRating(v)
	return _u
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (_u *PluginUpdateOne) SetNillableRating(v *float64) *PluginUpdateOne {
	if v != nil {
		_u.SetRating(*v)
	}
	return _u
}

// AddRating adds value to the "rating" field.
func (_u *PluginUpdateOne) AddRating(v float64) *PluginUpdateOne {
	_u.mutation.AddRating(v)
	return _u
}

// ClearRating clears the value of the "rating" field.
func (_u *PluginUpdateOne) ClearRating() *PluginUpdateOne {
	_u.mutation.ClearRating()
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *PluginUpdateOne) SetSourceType(v plugin.SourceType) *PluginUpdateOne {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *PluginUpdateOne) SetNillableSourceType(v *plugin.SourceType) *PluginUpdateOne {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetGithubRepoURL sets the "github_repo_url" field.
func (_u *PluginUpdateOne) SetGithubRepoURL(v string) *PluginUpdateOne {
	_u.mutation.SetGithubRepoURL(v)
	return _u
}

// SetNillableGithubRepoURL sets the "github_repo_url" field if the given value is not nil.
func (_u *PluginUpdateOne) SetNillableGithubRepoURL(v *string) *PluginUpdateOne {
	if v != nil {
		_u.SetGithubRepoURL(*v)
	}
	return _u
}

// ClearGithubRepoURL clears the value of the "github_repo_url" field.
func (_u *PluginUpdateOne) ClearGithubRepoURL() *PluginUpdateOne {
	_u.mutation.ClearGithubRepoURL()
	return _u
}

// SetGithubRepoNormalized sets the "github_repo_normalized" field.
func (_u *PluginUpdateOne) SetGithubRepoNormalized(v string) *PluginUpdateOne {
	_u.mutation.SetGithubRepoNormalized(v)
	return _u
}

// SetNillableGithubRepoNormalized sets the "github_repo_normalized" field if the given value is not nil.
func (_u *PluginUpdateOne) SetNillableGithubRepoNormalized(v *string) *PluginUpdateOne {
	if v != nil {
		_u.SetGithubRepoNormalized(*v)
	}
	return _u
}

// ClearGithubRepoNormalized clears the value of the "github_repo_normalized" field.
func (_u *PluginUpdateOne) ClearGithubRepoNormalized() *PluginUpdateOne {
	_u.mutation.ClearGithubRepoNormalized()
	return _u
}

// SetAutoUpgradeEnabled sets the "auto_upgrade_enabled" field.
func (_u *PluginUpdateOne) SetAutoUpgradeEnabled(v bool) *PluginUpdateOne {
	_u.mutation.SetAutoUpgradeEnabled(v)
	return _u
}

// SetNillableAutoUpgradeEnabled sets the "auto_upgrade_enabled" field if the given value is not nil.
func (_u *PluginUpdateOne) SetNillableAutoUpgradeEnabled(v *bool) *PluginUpdateOne {
	if v != nil {
		_u.SetAutoUpgradeEnabled(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PluginUpdateOne) SetStatus(v plugin.Status) *PluginUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PluginUpdateOne) SetNillableStatus(v *plugin.Status) *PluginUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PluginUpdateOne) SetUpdatedAt(v time.Time) *PluginUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddVersionIDs adds the "versions" edge to the PluginVersion entity by IDs.
func (_u *PluginUpdateOne) AddVersionIDs(ids ...uuid.UUID) *PluginUpdateOne {
	_u.mutation.AddVersionIDs(ids...)
	return _u
}

// AddVersions adds the "versions" edges to the PluginVersion entity.
func (_u *PluginUpdateOne) AddVersions(v ...*PluginVersion) *PluginUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddVersionIDs(ids...)
}

// AddSubmissionIDs adds the "submissions" edge to the Submission entity by IDs.
func (_u *PluginUpdateOne) AddSubmissionIDs(ids ...uuid.UUID) *PluginUpdateOne {
	_u.mutation.AddSubmissionIDs(ids...)
	return _u
}

// AddSubmissions adds the "submissions" edges to the Submission entity.
func (_u *PluginUpdateOne) AddSubmissions(v ...*Submission) *PluginUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSubmissionIDs(ids...)
}

// AddDownloadLogIDs adds the "download_logs" edge to the DownloadLog entity by IDs.
func (_u *PluginUpdateOne) AddDownloadLogIDs(ids ...uuid.UUID) *PluginUpdateOne {
	_u.mutation.AddDownloadLogIDs(ids...)
	return _u
}

// AddDownloadLogs adds the "download_logs" edges to the DownloadLog entity.
func (_u *PluginUpdateOne) AddDownloadLogs(v ...*DownloadLog) *PluginUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDownloadLogIDs(ids...)
}

// AddSyncJobIDs adds the "sync_jobs" edge to the SyncJob entity by IDs.
func (_u *PluginUpdateOne) AddSyncJobIDs(ids ...uuid.UUID) *PluginUpdateOne {
	_u.mutation.AddSyncJobIDs(ids...)
	return _u
}

// AddSyncJobs adds the "sync_jobs" edges to the SyncJob entity.
func (_u *PluginUpdateOne) AddSyncJobs(v ...*SyncJob) *PluginUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSyncJobIDs(ids...)
}

// Mutation returns the PluginMutation object of the builder.
func (_u *PluginUpdateOne) Mutation() *PluginMutation {
	return _u.mutation
}

// ClearVersions clears all "versions" edges to the PluginVersion entity.
func (_u *PluginUpdateOne) ClearVersions() *PluginUpdateOne {
	_u.mutation.ClearVersions()
	return _u
}

// RemoveVersionIDs removes the "versions" edge to PluginVersion entities by IDs.
func (_u *PluginUpdateOne) RemoveVersionIDs(ids ...uuid.UUID) *PluginUpdateOne {
	_u.mutation.RemoveVersionIDs(ids...)
	return _u
}

// RemoveVersions removes "versions" edges to PluginVersion entities.
func (_u *PluginUpdateOne) RemoveVersions(v ...*PluginVersion) *PluginUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveVersionIDs(ids...)
}

// ClearSubmissions clears all "submissions" edges to the Submission entity.
func (_u *PluginUpdateOne) ClearSubmissions() *PluginUpdateOne {
	_u.mutation.ClearSubmissions()
	return _u
}

// RemoveSubmissionIDs removes the "submissions" edge to Submission entities by IDs.
func (_u *PluginUpdateOne) RemoveSubmissionIDs(ids ...uuid.UUID) *PluginUpdateOne {
	_u.mutation.RemoveSubmissionIDs(ids...)
	return _u
}

// RemoveSubmissions removes "submissions" edges to Submission entities.
func (_u *PluginUpdateOne) RemoveSubmissions(v ...*Submission) *PluginUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSubmissionIDs(ids...)
}

// ClearDownloadLogs clears all "download_logs" edges to the DownloadLog entity.
func (_u *PluginUpdateOne) ClearDownloadLogs() *PluginUpdateOne {
	_u.mutation.ClearDownloadLogs()
	return _u
}

// RemoveDownloadLogIDs removes the "download_logs" edge to DownloadLog entities by IDs.
func (_u *PluginUpdateOne) RemoveDownloadLogIDs(ids ...uuid.UUID) *PluginUpdateOne {
	_u.mutation.RemoveDownloadLogIDs(ids...)
	return _u
}

// RemoveDownloadLogs removes "download_logs" edges to DownloadLog entities.
func (_u *PluginUpdateOne) RemoveDownloadLogs(v ...*DownloadLog) *PluginUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDownloadLogIDs(ids...)
}

// ClearSyncJobs clears all "sync_jobs" edges to the SyncJob entity.
func (_u *PluginUpdateOne) ClearSyncJobs() *PluginUpdateOne {
	_u.mutation.ClearSyncJobs()
	return _u
}

// RemoveSyncJobIDs removes the "sync_jobs" edge to SyncJob entities by IDs.
func (_u *PluginUpdateOne) RemoveSyncJobIDs(ids ...uuid.UUID) *PluginUpdateOne {
	_u.mutation.RemoveSyncJobIDs(ids...)
	return _u
}

// RemoveSyncJobs removes "sync_jobs" edges to SyncJob entities.
func (_u *PluginUpdateOne) RemoveSyncJobs(v ...*SyncJob) *PluginUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSyncJobIDs(ids...)
}

// Where appends a list predicates to the PluginUpdate builder.
func (_u *PluginUpdateOne) Where(ps ...predicate.Plugin) *PluginUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PluginUpdateOne) Select(field string, fields ...string) *PluginUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Plugin entity.
func (_u *PluginUpdateOne) Save(ctx context.Context) (*Plugin, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PluginUpdateOne) SaveX(ctx context.Context) *Plugin {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PluginUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PluginUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PluginUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := plugin.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PluginUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := plugin.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Plugin.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := plugin.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "Plugin.display_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Author(); ok {
		if err := plugin.AuthorValidator(v); err != nil {
			return &ValidationError{Name: "author", err: fmt.Errorf(`ent: validator failed for field "Plugin.author": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Category(); ok {
		if err := plugin.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "Plugin.category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DownloadCount(); ok {
		if err := plugin.DownloadCountValidator(v); err != nil {
			return &ValidationError{Name: "download_count", err: fmt.Errorf(`ent: validator failed for field "Plugin.download_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Rating(); ok {
		if err := plugin.RatingValidator(v); err != nil {
			return &ValidationError{Name: "rating", err: fmt.Errorf(`ent: validator failed for field "Plugin.rating": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceType(); ok {
		if err := plugin.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "Plugin.source_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := plugin.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Plugin.status": %w`, err)}
		}
	}
	return nil
}

func (_u *PluginUpdateOne) sqlSave(ctx context.Context) (_node *Plugin, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(plugin.Table, plugin.Columns, sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Plugin.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, plugin.FieldID)
		for _, f := range fields {
			if !plugin.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != plugin.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(plugin.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(plugin.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(plugin.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Author(); ok {
		_spec.SetField(plugin.FieldAuthor, field.TypeString, value)
	}
	if value, ok := _u.mutation.RepositoryURL(); ok {
		_spec.SetField(plugin.FieldRepositoryURL, field.TypeString, value)
	}
	if _u.mutation.RepositoryURLCleared() {
		_spec.ClearField(plugin.FieldRepositoryURL, field.TypeString)
	}
	if value, ok := _u.mutation.HomepageURL(); ok {
		_spec.SetField(plugin.FieldHomepageURL, field.TypeString, value)
	}
	if _u.mutation.HomepageURLCleared() {
		_spec.ClearField(plugin.FieldHomepageURL, field.TypeString)
	}
	if value, ok := _u.mutation.License(); ok {
		_spec.SetField(plugin.FieldLicense, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(plugin.FieldCategory, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(plugin.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, plugin.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(plugin.FieldTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.IsOfficial(); ok {
		_spec.SetField(plugin.FieldIsOfficial, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsVerified(); ok {
		_spec.SetField(plugin.FieldIsVerified, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DownloadCount(); ok {
		_spec.SetField(plugin.FieldDownloadCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDownloadCount(); ok {
		_spec.AddField(plugin.FieldDownloadCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Rating(); ok {
		_spec.SetField(plugin.FieldRating, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRating(); ok {
		_spec.AddField(plugin.FieldRating, field.TypeFloat64, value)
	}
	if _u.mutation.RatingCleared() {
		_spec.ClearField(plugin.FieldRating, field.TypeFloat64)
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(plugin.FieldSourceType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.GithubRepoURL(); ok {
		_spec.SetField(plugin.FieldGithubRepoURL, field.TypeString, value)
	}
	if _u.mutation.GithubRepoURLCleared() {
		_spec.ClearField(plugin.FieldGithubRepoURL, field.TypeString)
	}
	if value, ok := _u.mutation.GithubRepoNormalized(); ok {
		_spec.SetField(plugin.FieldGithubRepoNormalized, field.TypeString, value)
	}
	if _u.mutation.GithubRepoNormalizedCleared() {
		_spec.ClearField(plugin.FieldGithubRepoNormalized, field.TypeString)
	}
	if value, ok := _u.mutation.AutoUpgradeEnabled(); ok {
		_spec.SetField(plugin.FieldAutoUpgradeEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(plugin.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(plugin.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.VersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plugin.VersionsTable,
			Columns: []string{plugin.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pluginversion.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedVersionsIDs(); len(nodes) > 0 && !_u.mutation.VersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plugin.VersionsTable,
			Columns: []string{plugin.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pluginversion.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VersionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plugin.VersionsTable,
			Columns: []string{plugin.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pluginversion.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubmissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plugin.SubmissionsTable,
			Columns: []string{plugin.SubmissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(submission.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSubmissionsIDs(); len(nodes) > 0 && !_u.mutation.SubmissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plugin.SubmissionsTable,
			Columns: []string{plugin.SubmissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(submission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubmissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plugin.SubmissionsTable,
			Columns: []string{plugin.SubmissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(submission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DownloadLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plugin.DownloadLogsTable,
			Columns: []string{plugin.DownloadLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(downloadlog.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDownloadLogsIDs(); len(nodes) > 0 && !_u.mutation.DownloadLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plugin.DownloadLogsTable,
			Columns: []string{plugin.DownloadLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(downloadlog.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DownloadLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plugin.DownloadLogsTable,
			Columns: []string{plugin.DownloadLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(downloadlog.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SyncJobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plugin.SyncJobsTable,
			Columns: []string{plugin.SyncJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(syncjob.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSyncJobsIDs(); len(nodes) > 0 && !_u.mutation.SyncJobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plugin.SyncJobsTable,
			Columns: []string{plugin.SyncJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(syncjob.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SyncJobsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plugin.SyncJobsTable,
			Columns: []string{plugin.SyncJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(syncjob.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Plugin{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{plugin.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
