// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/IanShaw027/sub2api-plugin-market/ent/downloadlog"
	"github.com/IanShaw027/sub2api-plugin-market/ent/plugin"
	"github.com/IanShaw027/sub2api-plugin-market/ent/pluginversion"
	"github.com/IanShaw027/sub2api-plugin-market/ent/submission"
	"github.com/IanShaw027/sub2api-plugin-market/ent/syncjob"
	"github.com/google/uuid"
)

// PluginCreate is the builder for creating a Plugin entity.
type PluginCreate struct {
	config
	mutation *PluginMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *PluginCreate) SetName(v string) *PluginCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDisplayName sets the "display_name" field.
func (_c *PluginCreate) SetDisplayName(v string) *PluginCreate {
	_c.mutation.SetDisplayName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *PluginCreate) SetDescription(v string) *PluginCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetAuthor sets the "author" field.
func (_c *PluginCreate) SetAuthor(v string) *PluginCreate {
	_c.mutation.SetAuthor(v)
	return _c
}

// SetRepositoryURL sets the "repository_url" field.
func (_c *PluginCreate) SetRepositoryURL(v string) *PluginCreate {
	_c.mutation.SetRepositoryURL(v)
	return _c
}

// SetNillableRepositoryURL sets the "repository_url" field if the given value is not nil.
func (_c *PluginCreate) SetNillableRepositoryURL(v *string) *PluginCreate {
	if v != nil {
		_c.SetRepositoryURL(*v)
	}
	return _c
}

// SetHomepageURL sets the "homepage_url" field.
func (_c *PluginCreate) SetHomepageURL(v string) *PluginCreate {
	_c.mutation.SetHomepageURL(v)
	return _c
}

// SetNillableHomepageURL sets the "homepage_url" field if the given value is not nil.
func (_c *PluginCreate) SetNillableHomepageURL(v *string) *PluginCreate {
	if v != nil {
		_c.SetHomepageURL(*v)
	}
	return _c
}

// SetLicense sets the "license" field.
func (_c *PluginCreate) SetLicense(v string) *PluginCreate {
	_c.mutation.SetLicense(v)
	return _c
}

// SetNillableLicense sets the "license" field if the given value is not nil.
func (_c *PluginCreate) SetNillableLicense(v *string) *PluginCreate {
	if v != nil {
		_c.SetLicense(*v)
	}
	return _c
}

// SetCategory sets the "category" field.
func (_c *PluginCreate) SetCategory(v plugin.Category) *PluginCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_c *PluginCreate) SetNillableCategory(v *plugin.Category) *PluginCreate {
	if v != nil {
		_c.SetCategory(*v)
	}
	return _c
}

// SetTags sets the "tags" field.
func (_c *PluginCreate) SetTags(v []string) *PluginCreate {
	_c.mutation.SetTags(v)
	return _c
}

// SetIsOfficial sets the "is_official" field.
func (_c *PluginCreate) SetIsOfficial(v bool) *PluginCreate {
	_c.mutation.SetIsOfficial(v)
	return _c
}

// SetNillableIsOfficial sets the "is_official" field if the given value is not nil.
func (_c *PluginCreate) SetNillableIsOfficial(v *bool) *PluginCreate {
	if v != nil {
		_c.SetIsOfficial(*v)
	}
	return _c
}

// SetIsVerified sets the "is_verified" field.
func (_c *PluginCreate) SetIsVerified(v bool) *PluginCreate {
	_c.mutation.SetIsVerified(v)
	return _c
}

// SetNillableIsVerified sets the "is_verified" field if the given value is not nil.
func (_c *PluginCreate) SetNillableIsVerified(v *bool) *PluginCreate {
	if v != nil {
		_c.SetIsVerified(*v)
	}
	return _c
}

// SetDownloadCount sets the "download_count" field.
func (_c *PluginCreate) SetDownloadCount(v int) *PluginCreate {
	_c.mutation.SetDownloadCount(v)
	return _c
}

// SetNillableDownloadCount sets the "download_count" field if the given value is not nil.
func (_c *PluginCreate) SetNillableDownloadCount(v *int) *PluginCreate {
	if v != nil {
		_c.SetDownloadCount(*v)
	}
	return _c
}

// SetRating sets the "rating" field.
func (_c *PluginCreate) SetRating(v float64) *PluginCreate {
	_c.mutation.SetRating(v)
	return _c
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (_c *PluginCreate) SetNillableRating(v *float64) *PluginCreate {
	if v != nil {
		_c.SetRating(*v)
	}
	return _c
}

// SetSourceType sets the "source_type" field.
func (_c *PluginCreate) SetSourceType(v plugin.SourceType) *PluginCreate {
	_c.mutation.SetSourceType(v)
	return _c
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_c *PluginCreate) SetNillableSourceType(v *plugin.SourceType) *PluginCreate {
	if v != nil {
		_c.SetSourceType(*v)
	}
	return _c
}

// SetGithubRepoURL sets the "github_repo_url" field.
func (_c *PluginCreate) SetGithubRepoURL(v string) *PluginCreate {
	_c.mutation.SetGithubRepoURL(v)
	return _c
}

// SetNillableGithubRepoURL sets the "github_repo_url" field if the given value is not nil.
func (_c *PluginCreate) SetNillableGithubRepoURL(v *string) *PluginCreate {
	if v != nil {
		_c.SetGithubRepoURL(*v)
	}
	return _c
}

// SetGithubRepoNormalized sets the "github_repo_normalized" field.
func (_c *PluginCreate) SetGithubRepoNormalized(v string) *PluginCreate {
	_c.mutation.SetGithubRepoNormalized(v)
	return _c
}

// SetNillableGithubRepoNormalized sets the "github_repo_normalized" field if the given value is not nil.
func (_c *PluginCreate) SetNillableGithubRepoNormalized(v *string) *PluginCreate {
	if v != nil {
		_c.SetGithubRepoNormalized(*v)
	}
	return _c
}

// SetAutoUpgradeEnabled sets the "auto_upgrade_enabled" field.
func (_c *PluginCreate) SetAutoUpgradeEnabled(v bool) *PluginCreate {
	_c.mutation.SetAutoUpgradeEnabled(v)
	return _c
}

// SetNillableAutoUpgradeEnabled sets the "auto_upgrade_enabled" field if the given value is not nil.
func (_c *PluginCreate) SetNillableAutoUpgradeEnabled(v *bool) *PluginCreate {
	if v != nil {
		_c.SetAutoUpgradeEnabled(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *PluginCreate) SetStatus(v plugin.Status) *PluginCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *PluginCreate) SetNillableStatus(v *plugin.Status) *PluginCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PluginCreate) SetCreatedAt(v time.Time) *PluginCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PluginCreate) SetNillableCreatedAt(v *time.Time) *PluginCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PluginCreate) SetUpdatedAt(v time.Time) *PluginCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PluginCreate) SetNillableUpdatedAt(v *time.Time) *PluginCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PluginCreate) SetID(v uuid.UUID) *PluginCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PluginCreate) SetNillableID(v *uuid.UUID) *PluginCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddVersionIDs adds the "versions" edge to the PluginVersion entity by IDs.
func (_c *PluginCreate) AddVersionIDs(ids ...uuid.UUID) *PluginCreate {
	_c.mutation.AddVersionIDs(ids...)
	return _c
}

// AddVersions adds the "versions" edges to the PluginVersion entity.
func (_c *PluginCreate) AddVersions(v ...*PluginVersion) *PluginCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddVersionIDs(ids...)
}

// AddSubmissionIDs adds the "submissions" edge to the Submission entity by IDs.
func (_c *PluginCreate) AddSubmissionIDs(ids ...uuid.UUID) *PluginCreate {
	_c.mutation.AddSubmissionIDs(ids...)
	return _c
}

// AddSubmissions adds the "submissions" edges to the Submission entity.
func (_c *PluginCreate) AddSubmissions(v ...*Submission) *PluginCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSubmissionIDs(ids...)
}

// AddDownloadLogIDs adds the "download_logs" edge to the DownloadLog entity by IDs.
func (_c *PluginCreate) AddDownloadLogIDs(ids ...uuid.UUID) *PluginCreate {
	_c.mutation.AddDownloadLogIDs(ids...)
	return _c
}

// AddDownloadLogs adds the "download_logs" edges to the DownloadLog entity.
func (_c *PluginCreate) AddDownloadLogs(v ...*DownloadLog) *PluginCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddDownloadLogIDs(ids...)
}

// AddSyncJobIDs adds the "sync_jobs" edge to the SyncJob entity by IDs.
func (_c *PluginCreate) AddSyncJobIDs(ids ...uuid.UUID) *PluginCreate {
	_c.mutation.AddSyncJobIDs(ids...)
	return _c
}

// AddSyncJobs adds the "sync_jobs" edges to the SyncJob entity.
func (_c *PluginCreate) AddSyncJobs(v ...*SyncJob) *PluginCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSyncJobIDs(ids...)
}

// Mutation returns the PluginMutation object of the builder.
func (_c *PluginCreate) Mutation() *PluginMutation {
	return _c.mutation
}

// Save creates the Plugin in the database.
func (_c *PluginCreate) Save(ctx context.Context) (*Plugin, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PluginCreate) SaveX(ctx context.Context) *Plugin {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PluginCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PluginCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PluginCreate) defaults() {
	if _, ok := _c.mutation.License(); !ok {
		v := plugin.DefaultLicense
		_c.mutation.SetLicense(v)
	}
	if _, ok := _c.mutation.Category(); !ok {
		v := plugin.DefaultCategory
		_c.mutation.SetCategory(v)
	}
	if _, ok := _c.mutation.IsOfficial(); !ok {
		v := plugin.DefaultIsOfficial
		_c.mutation.SetIsOfficial(v)
	}
	if _, ok := _c.mutation.IsVerified(); !ok {
		v := plugin.DefaultIsVerified
		_c.mutation.SetIsVerified(v)
	}
	if _, ok := _c.mutation.DownloadCount(); !ok {
		v := plugin.DefaultDownloadCount
		_c.mutation.SetDownloadCount(v)
	}
	if _, ok := _c.mutation.SourceType(); !ok {
		v := plugin.DefaultSourceType
		_c.mutation.SetSourceType(v)
	}
	if _, ok := _c.mutation.AutoUpgradeEnabled(); !ok {
		v := plugin.DefaultAutoUpgradeEnabled
		_c.mutation.SetAutoUpgradeEnabled(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := plugin.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := plugin.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := plugin.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := plugin.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PluginCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Plugin.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := plugin.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Plugin.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DisplayName(); !ok {
		return &ValidationError{Name: "display_name", err: errors.New(`ent: missing required field "Plugin.display_name"`)}
	}
	if v, ok := _c.mutation.DisplayName(); ok {
		if err := plugin.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "Plugin.display_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Plugin.description"`)}
	}
	if _, ok := _c.mutation.Author(); !ok {
		return &ValidationError{Name: "author", err: errors.New(`ent: missing required field "Plugin.author"`)}
	}
	if v, ok := _c.mutation.Author(); ok {
		if err := plugin.AuthorValidator(v); err != nil {
			return &ValidationError{Name: "author", err: fmt.Errorf(`ent: validator failed for field "Plugin.author": %w`, err)}
		}
	}
	if _, ok := _c.mutation.License(); !ok {
		return &ValidationError{Name: "license", err: errors.New(`ent: missing required field "Plugin.license"`)}
	}
	if _, ok := _c.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "Plugin.category"`)}
	}
	if v, ok := _c.mutation.Category(); ok {
		if err := plugin.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "Plugin.category": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsOfficial(); !ok {
		return &ValidationError{Name: "is_official", err: errors.New(`ent: missing required field "Plugin.is_official"`)}
	}
	if _, ok := _c.mutation.IsVerified(); !ok {
		return &ValidationError{Name: "is_verified", err: errors.New(`ent: missing required field "Plugin.is_verified"`)}
	}
	if _, ok := _c.mutation.DownloadCount(); !ok {
		return &ValidationError{Name: "download_count", err: errors.New(`ent: missing required field "Plugin.download_count"`)}
	}
	if v, ok := _c.mutation.DownloadCount(); ok {
		if err := plugin.DownloadCountValidator(v); err != nil {
			return &ValidationError{Name: "download_count", err: fmt.Errorf(`ent: validator failed for field "Plugin.download_count": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Rating(); ok {
		if err := plugin.RatingValidator(v); err != nil {
			return &ValidationError{Name: "rating", err: fmt.Errorf(`ent: validator failed for field "Plugin.rating": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SourceType(); !ok {
		return &ValidationError{Name: "source_type", err: errors.New(`ent: missing required field "Plugin.source_type"`)}
	}
	if v, ok := _c.mutation.SourceType(); ok {
		if err := plugin.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "Plugin.source_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AutoUpgradeEnabled(); !ok {
		return &ValidationError{Name: "auto_upgrade_enabled", err: errors.New(`ent: missing required field "Plugin.auto_upgrade_enabled"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Plugin.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := plugin.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Plugin.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Plugin.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Plugin.updated_at"`)}
	}
	return nil
}

func (_c *PluginCreate) sqlSave(ctx context.Context) (*Plugin, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PluginCreate) createSpec() (*Plugin, *sqlgraph.CreateSpec) {
	var (
		_node = &Plugin{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(plugin.Table, sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(plugin.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.DisplayName(); ok {
		_spec.SetField(plugin.FieldDisplayName, field.TypeString, value)
		_node.DisplayName = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(plugin.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Author(); ok {
		_spec.SetField(plugin.FieldAuthor, field.TypeString, value)
		_node.Author = value
	}
	if value, ok := _c.mutation.RepositoryURL(); ok {
		_spec.SetField(plugin.FieldRepositoryURL, field.TypeString, value)
		_node.RepositoryURL = value
	}
	if value, ok := _c.mutation.HomepageURL(); ok {
		_spec.SetField(plugin.FieldHomepageURL, field.TypeString, value)
		_node.HomepageURL = value
	}
	if value, ok := _c.mutation.License(); ok {
		_spec.SetField(plugin.FieldLicense, field.TypeString, value)
		_node.License = value
	}
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(plugin.FieldCategory, field.TypeEnum, value)
		_node.Category = value
	}
	if value, ok := _c.mutation.Tags(); ok {
		_spec.SetField(plugin.FieldTags, field.TypeJSON, value)
		_node.Tags = value
	}
	if value, ok := _c.mutation.IsOfficial(); ok {
		_spec.SetField(plugin.FieldIsOfficial, field.TypeBool, value)
		_node.IsOfficial = value
	}
	if value, ok := _c.mutation.IsVerified(); ok {
		_spec.SetField(plugin.FieldIsVerified, field.TypeBool, value)
		_node.IsVerified = value
	}
	if value, ok := _c.mutation.DownloadCount(); ok {
		_spec.SetField(plugin.FieldDownloadCount, field.TypeInt, value)
		_node.DownloadCount = value
	}
	if value, ok := _c.mutation.Rating(); ok {
		_spec.SetField(plugin.FieldRating, field.TypeFloat64, value)
		_node.Rating = value
	}
	if value, ok := _c.mutation.SourceType(); ok {
		_spec.SetField(plugin.FieldSourceType, field.TypeEnum, value)
		_node.SourceType = value
	}
	if value, ok := _c.mutation.GithubRepoURL(); ok {
		_spec.SetField(plugin.FieldGithubRepoURL, field.TypeString, value)
		_node.GithubRepoURL = value
	}
	if value, ok := _c.mutation.GithubRepoNormalized(); ok {
		_spec.SetField(plugin.FieldGithubRepoNormalized, field.TypeString, value)
		_node.GithubRepoNormalized = value
	}
	if value, ok := _c.mutation.AutoUpgradeEnabled(); ok {
		_spec.SetField(plugin.FieldAutoUpgradeEnabled, field.TypeBool, value)
		_node.AutoUpgradeEnabled = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(plugin.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(plugin.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(plugin.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.VersionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plugin.VersionsTable,
			Columns: []string{plugin.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pluginversion.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SubmissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plugin.SubmissionsTable,
			Columns: []string{plugin.SubmissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(submission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DownloadLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plugin.DownloadLogsTable,
			Columns: []string{plugin.DownloadLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(downloadlog.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SyncJobsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plugin.SyncJobsTable,
			Columns: []string{plugin.SyncJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(syncjob.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PluginCreateBulk is the builder for creating many Plugin entities in bulk.
type PluginCreateBulk struct {
	config
	err      error
	builders []*PluginCreate
}

// Save creates the Plugin entities in the database.
func (_c *PluginCreateBulk) Save(ctx context.Context) ([]*Plugin, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Plugin, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PluginMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PluginCreateBulk) SaveX(ctx context.Context) []*Plugin {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PluginCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PluginCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
