// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/IanShaw027/sub2api-plugin-market/ent/adminuser"
	"github.com/IanShaw027/sub2api-plugin-market/ent/downloadlog"
	"github.com/IanShaw027/sub2api-plugin-market/ent/plugin"
	"github.com/IanShaw027/sub2api-plugin-market/ent/pluginversion"
	"github.com/IanShaw027/sub2api-plugin-market/ent/schema"
	"github.com/IanShaw027/sub2api-plugin-market/ent/submission"
	"github.com/IanShaw027/sub2api-plugin-market/ent/syncjob"
	"github.com/IanShaw027/sub2api-plugin-market/ent/trustkey"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	adminuserFields := schema.AdminUser{}.Fields()
	_ = adminuserFields
	// adminuserDescUsername is the schema descriptor for username field.
	adminuserDescUsername := adminuserFields[1].Descriptor()
	// adminuser.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	adminuser.UsernameValidator = adminuserDescUsername.Validators[0].(func(string) error)
	// adminuserDescEmail is the schema descriptor for email field.
	adminuserDescEmail := adminuserFields[2].Descriptor()
	// adminuser.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	adminuser.EmailValidator = adminuserDescEmail.Validators[0].(func(string) error)
	// adminuserDescPasswordHash is the schema descriptor for password_hash field.
	adminuserDescPasswordHash := adminuserFields[3].Descriptor()
	// adminuser.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	adminuser.PasswordHashValidator = adminuserDescPasswordHash.Validators[0].(func(string) error)
	// adminuserDescIsActive is the schema descriptor for is_active field.
	adminuserDescIsActive := adminuserFields[5].Descriptor()
	// adminuser.DefaultIsActive holds the default value on creation for the is_active field.
	adminuser.DefaultIsActive = adminuserDescIsActive.Default.(bool)
	// adminuserDescCreatedAt is the schema descriptor for created_at field.
	adminuserDescCreatedAt := adminuserFields[7].Descriptor()
	// adminuser.DefaultCreatedAt holds the default value on creation for the created_at field.
	adminuser.DefaultCreatedAt = adminuserDescCreatedAt.Default.(func() time.Time)
	// adminuserDescUpdatedAt is the schema descriptor for updated_at field.
	adminuserDescUpdatedAt := adminuserFields[8].Descriptor()
	// adminuser.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	adminuser.DefaultUpdatedAt = adminuserDescUpdatedAt.Default.(func() time.Time)
	// adminuser.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	adminuser.UpdateDefaultUpdatedAt = adminuserDescUpdatedAt.UpdateDefault.(func() time.Time)
	// adminuserDescID is the schema descriptor for id field.
	adminuserDescID := adminuserFields[0].Descriptor()
	// adminuser.DefaultID holds the default value on creation for the id field.
	adminuser.DefaultID = adminuserDescID.Default.(func() uuid.UUID)
	downloadlogFields := schema.DownloadLog{}.Fields()
	_ = downloadlogFields
	// downloadlogDescVersion is the schema descriptor for version field.
	downloadlogDescVersion := downloadlogFields[2].Descriptor()
	// downloadlog.VersionValidator is a validator for the "version" field. It is called by the builders before save.
	downloadlog.VersionValidator = downloadlogDescVersion.Validators[0].(func(string) error)
	// downloadlogDescClientIP is the schema descriptor for client_ip field.
	downloadlogDescClientIP := downloadlogFields[3].Descriptor()
	// downloadlog.ClientIPValidator is a validator for the "client_ip" field. It is called by the builders before save.
	downloadlog.ClientIPValidator = downloadlogDescClientIP.Validators[0].(func(string) error)
	// downloadlogDescCountryCode is the schema descriptor for country_code field.
	downloadlogDescCountryCode := downloadlogFields[5].Descriptor()
	// downloadlog.CountryCodeValidator is a validator for the "country_code" field. It is called by the builders before save.
	downloadlog.CountryCodeValidator = downloadlogDescCountryCode.Validators[0].(func(string) error)
	// downloadlogDescSuccess is the schema descriptor for success field.
	downloadlogDescSuccess := downloadlogFields[6].Descriptor()
	// downloadlog.DefaultSuccess holds the default value on creation for the success field.
	downloadlog.DefaultSuccess = downloadlogDescSuccess.Default.(bool)
	// downloadlogDescDownloadedAt is the schema descriptor for downloaded_at field.
	downloadlogDescDownloadedAt := downloadlogFields[8].Descriptor()
	// downloadlog.DefaultDownloadedAt holds the default value on creation for the downloaded_at field.
	downloadlog.DefaultDownloadedAt = downloadlogDescDownloadedAt.Default.(func() time.Time)
	// downloadlogDescID is the schema descriptor for id field.
	downloadlogDescID := downloadlogFields[0].Descriptor()
	// downloadlog.DefaultID holds the default value on creation for the id field.
	downloadlog.DefaultID = downloadlogDescID.Default.(func() uuid.UUID)
	pluginFields := schema.Plugin{}.Fields()
	_ = pluginFields
	// pluginDescName is the schema descriptor for name field.
	pluginDescName := pluginFields[1].Descriptor()
	// plugin.NameValidator is a validator for the "name" field. It is called by the builders before save.
	plugin.NameValidator = pluginDescName.Validators[0].(func(string) error)
	// pluginDescDisplayName is the schema descriptor for display_name field.
	pluginDescDisplayName := pluginFields[2].Descriptor()
	// plugin.DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	plugin.DisplayNameValidator = pluginDescDisplayName.Validators[0].(func(string) error)
	// pluginDescAuthor is the schema descriptor for author field.
	pluginDescAuthor := pluginFields[4].Descriptor()
	// plugin.AuthorValidator is a validator for the "author" field. It is called by the builders before save.
	plugin.AuthorValidator = pluginDescAuthor.Validators[0].(func(string) error)
	// pluginDescLicense is the schema descriptor for license field.
	pluginDescLicense := pluginFields[7].Descriptor()
	// plugin.DefaultLicense holds the default value on creation for the license field.
	plugin.DefaultLicense = pluginDescLicense.Default.(string)
	// pluginDescIsOfficial is the schema descriptor for is_official field.
	pluginDescIsOfficial := pluginFields[10].Descriptor()
	// plugin.DefaultIsOfficial holds the default value on creation for the is_official field.
	plugin.DefaultIsOfficial = pluginDescIsOfficial.Default.(bool)
	// pluginDescIsVerified is the schema descriptor for is_verified field.
	pluginDescIsVerified := pluginFields[11].Descriptor()
	// plugin.DefaultIsVerified holds the default value on creation for the is_verified field.
	plugin.DefaultIsVerified = pluginDescIsVerified.Default.(bool)
	// pluginDescDownloadCount is the schema descriptor for download_count field.
	pluginDescDownloadCount := pluginFields[12].Descriptor()
	// plugin.DefaultDownloadCount holds the default value on creation for the download_count field.
	plugin.DefaultDownloadCount = pluginDescDownloadCount.Default.(int)
	// plugin.DownloadCountValidator is a validator for the "download_count" field. It is called by the builders before save.
	plugin.DownloadCountValidator = pluginDescDownloadCount.Validators[0].(func(int) error)
	// pluginDescRating is the schema descriptor for rating field.
	pluginDescRating := pluginFields[13].Descriptor()
	// plugin.RatingValidator is a validator for the "rating" field. It is called by the builders before save.
	plugin.RatingValidator = func() func(float64) error {
		validators := pluginDescRating.Validators
		fns := [...]func(float64) error{
			validators[0].(func(float64) error),
			validators[1].(func(float64) error),
		}
		return func(rating float64) error {
			for _, fn := range fns {
				if err := fn(rating); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// pluginDescAutoUpgradeEnabled is the schema descriptor for auto_upgrade_enabled field.
	pluginDescAutoUpgradeEnabled := pluginFields[17].Descriptor()
	// plugin.DefaultAutoUpgradeEnabled holds the default value on creation for the auto_upgrade_enabled field.
	plugin.DefaultAutoUpgradeEnabled = pluginDescAutoUpgradeEnabled.Default.(bool)
	// pluginDescCreatedAt is the schema descriptor for created_at field.
	pluginDescCreatedAt := pluginFields[19].Descriptor()
	// plugin.DefaultCreatedAt holds the default value on creation for the created_at field.
	plugin.DefaultCreatedAt = pluginDescCreatedAt.Default.(func() time.Time)
	// pluginDescUpdatedAt is the schema descriptor for updated_at field.
	pluginDescUpdatedAt := pluginFields[20].Descriptor()
	// plugin.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	plugin.DefaultUpdatedAt = pluginDescUpdatedAt.Default.(func() time.Time)
	// plugin.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	plugin.UpdateDefaultUpdatedAt = pluginDescUpdatedAt.UpdateDefault.(func() time.Time)
	// pluginDescID is the schema descriptor for id field.
	pluginDescID := pluginFields[0].Descriptor()
	// plugin.DefaultID holds the default value on creation for the id field.
	plugin.DefaultID = pluginDescID.Default.(func() uuid.UUID)
	pluginversionFields := schema.PluginVersion{}.Fields()
	_ = pluginversionFields
	// pluginversionDescVersion is the schema descriptor for version field.
	pluginversionDescVersion := pluginversionFields[2].Descriptor()
	// pluginversion.VersionValidator is a validator for the "version" field. It is called by the builders before save.
	pluginversion.VersionValidator = pluginversionDescVersion.Validators[0].(func(string) error)
	// pluginversionDescWasmURL is the schema descriptor for wasm_url field.
	pluginversionDescWasmURL := pluginversionFields[4].Descriptor()
	// pluginversion.WasmURLValidator is a validator for the "wasm_url" field. It is called by the builders before save.
	pluginversion.WasmURLValidator = pluginversionDescWasmURL.Validators[0].(func(string) error)
	// pluginversionDescWasmHash is the schema descriptor for wasm_hash field.
	pluginversionDescWasmHash := pluginversionFields[5].Descriptor()
	// pluginversion.WasmHashValidator is a validator for the "wasm_hash" field. It is called by the builders before save.
	pluginversion.WasmHashValidator = pluginversionDescWasmHash.Validators[0].(func(string) error)
	// pluginversionDescSignature is the schema descriptor for signature field.
	pluginversionDescSignature := pluginversionFields[6].Descriptor()
	// pluginversion.SignatureValidator is a validator for the "signature" field. It is called by the builders before save.
	pluginversion.SignatureValidator = pluginversionDescSignature.Validators[0].(func(string) error)
	// pluginversionDescFileSize is the schema descriptor for file_size field.
	pluginversionDescFileSize := pluginversionFields[8].Descriptor()
	// pluginversion.FileSizeValidator is a validator for the "file_size" field. It is called by the builders before save.
	pluginversion.FileSizeValidator = pluginversionDescFileSize.Validators[0].(func(int) error)
	// pluginversionDescMinAPIVersion is the schema descriptor for min_api_version field.
	pluginversionDescMinAPIVersion := pluginversionFields[9].Descriptor()
	// pluginversion.MinAPIVersionValidator is a validator for the "min_api_version" field. It is called by the builders before save.
	pluginversion.MinAPIVersionValidator = pluginversionDescMinAPIVersion.Validators[0].(func(string) error)
	// pluginversionDescPluginAPIVersion is the schema descriptor for plugin_api_version field.
	pluginversionDescPluginAPIVersion := pluginversionFields[10].Descriptor()
	// pluginversion.PluginAPIVersionValidator is a validator for the "plugin_api_version" field. It is called by the builders before save.
	pluginversion.PluginAPIVersionValidator = pluginversionDescPluginAPIVersion.Validators[0].(func(string) error)
	// pluginversionDescCreatedAt is the schema descriptor for created_at field.
	pluginversionDescCreatedAt := pluginversionFields[15].Descriptor()
	// pluginversion.DefaultCreatedAt holds the default value on creation for the created_at field.
	pluginversion.DefaultCreatedAt = pluginversionDescCreatedAt.Default.(func() time.Time)
	// pluginversionDescUpdatedAt is the schema descriptor for updated_at field.
	pluginversionDescUpdatedAt := pluginversionFields[16].Descriptor()
	// pluginversion.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	pluginversion.DefaultUpdatedAt = pluginversionDescUpdatedAt.Default.(func() time.Time)
	// pluginversion.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	pluginversion.UpdateDefaultUpdatedAt = pluginversionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// pluginversionDescID is the schema descriptor for id field.
	pluginversionDescID := pluginversionFields[0].Descriptor()
	// pluginversion.DefaultID holds the default value on creation for the id field.
	pluginversion.DefaultID = pluginversionDescID.Default.(func() uuid.UUID)
	submissionFields := schema.Submission{}.Fields()
	_ = submissionFields
	// submissionDescSubmitterEmail is the schema descriptor for submitter_email field.
	submissionDescSubmitterEmail := submissionFields[3].Descriptor()
	// submission.SubmitterEmailValidator is a validator for the "submitter_email" field. It is called by the builders before save.
	submission.SubmitterEmailValidator = submissionDescSubmitterEmail.Validators[0].(func(string) error)
	// submissionDescSubmitterName is the schema descriptor for submitter_name field.
	submissionDescSubmitterName := submissionFields[4].Descriptor()
	// submission.SubmitterNameValidator is a validator for the "submitter_name" field. It is called by the builders before save.
	submission.SubmitterNameValidator = submissionDescSubmitterName.Validators[0].(func(string) error)
	// submissionDescAutoUpgradeEnabled is the schema descriptor for auto_upgrade_enabled field.
	submissionDescAutoUpgradeEnabled := submissionFields[8].Descriptor()
	// submission.DefaultAutoUpgradeEnabled holds the default value on creation for the auto_upgrade_enabled field.
	submission.DefaultAutoUpgradeEnabled = submissionDescAutoUpgradeEnabled.Default.(bool)
	// submissionDescCreatedAt is the schema descriptor for created_at field.
	submissionDescCreatedAt := submissionFields[13].Descriptor()
	// submission.DefaultCreatedAt holds the default value on creation for the created_at field.
	submission.DefaultCreatedAt = submissionDescCreatedAt.Default.(func() time.Time)
	// submissionDescUpdatedAt is the schema descriptor for updated_at field.
	submissionDescUpdatedAt := submissionFields[14].Descriptor()
	// submission.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	submission.DefaultUpdatedAt = submissionDescUpdatedAt.Default.(func() time.Time)
	// submission.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	submission.UpdateDefaultUpdatedAt = submissionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// submissionDescID is the schema descriptor for id field.
	submissionDescID := submissionFields[0].Descriptor()
	// submission.DefaultID holds the default value on creation for the id field.
	submission.DefaultID = submissionDescID.Default.(func() uuid.UUID)
	syncjobFields := schema.SyncJob{}.Fields()
	_ = syncjobFields
	// syncjobDescCreatedAt is the schema descriptor for created_at field.
	syncjobDescCreatedAt := syncjobFields[8].Descriptor()
	// syncjob.DefaultCreatedAt holds the default value on creation for the created_at field.
	syncjob.DefaultCreatedAt = syncjobDescCreatedAt.Default.(func() time.Time)
	// syncjobDescUpdatedAt is the schema descriptor for updated_at field.
	syncjobDescUpdatedAt := syncjobFields[9].Descriptor()
	// syncjob.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	syncjob.DefaultUpdatedAt = syncjobDescUpdatedAt.Default.(func() time.Time)
	// syncjob.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	syncjob.UpdateDefaultUpdatedAt = syncjobDescUpdatedAt.UpdateDefault.(func() time.Time)
	// syncjobDescID is the schema descriptor for id field.
	syncjobDescID := syncjobFields[0].Descriptor()
	// syncjob.DefaultID holds the default value on creation for the id field.
	syncjob.DefaultID = syncjobDescID.Default.(func() uuid.UUID)
	trustkeyFields := schema.TrustKey{}.Fields()
	_ = trustkeyFields
	// trustkeyDescKeyID is the schema descriptor for key_id field.
	trustkeyDescKeyID := trustkeyFields[1].Descriptor()
	// trustkey.KeyIDValidator is a validator for the "key_id" field. It is called by the builders before save.
	trustkey.KeyIDValidator = trustkeyDescKeyID.Validators[0].(func(string) error)
	// trustkeyDescPublicKey is the schema descriptor for public_key field.
	trustkeyDescPublicKey := trustkeyFields[2].Descriptor()
	// trustkey.PublicKeyValidator is a validator for the "public_key" field. It is called by the builders before save.
	trustkey.PublicKeyValidator = trustkeyDescPublicKey.Validators[0].(func(string) error)
	// trustkeyDescOwnerName is the schema descriptor for owner_name field.
	trustkeyDescOwnerName := trustkeyFields[4].Descriptor()
	// trustkey.OwnerNameValidator is a validator for the "owner_name" field. It is called by the builders before save.
	trustkey.OwnerNameValidator = trustkeyDescOwnerName.Validators[0].(func(string) error)
	// trustkeyDescOwnerEmail is the schema descriptor for owner_email field.
	trustkeyDescOwnerEmail := trustkeyFields[5].Descriptor()
	// trustkey.OwnerEmailValidator is a validator for the "owner_email" field. It is called by the builders before save.
	trustkey.OwnerEmailValidator = trustkeyDescOwnerEmail.Validators[0].(func(string) error)
	// trustkeyDescIsActive is the schema descriptor for is_active field.
	trustkeyDescIsActive := trustkeyFields[7].Descriptor()
	// trustkey.DefaultIsActive holds the default value on creation for the is_active field.
	trustkey.DefaultIsActive = trustkeyDescIsActive.Default.(bool)
	// trustkeyDescCreatedAt is the schema descriptor for created_at field.
	trustkeyDescCreatedAt := trustkeyFields[9].Descriptor()
	// trustkey.DefaultCreatedAt holds the default value on creation for the created_at field.
	trustkey.DefaultCreatedAt = trustkeyDescCreatedAt.Default.(func() time.Time)
	// trustkeyDescUpdatedAt is the schema descriptor for updated_at field.
	trustkeyDescUpdatedAt := trustkeyFields[10].Descriptor()
	// trustkey.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	trustkey.DefaultUpdatedAt = trustkeyDescUpdatedAt.Default.(func() time.Time)
	// trustkey.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	trustkey.UpdateDefaultUpdatedAt = trustkeyDescUpdatedAt.UpdateDefault.(func() time.Time)
	// trustkeyDescID is the schema descriptor for id field.
	trustkeyDescID := trustkeyFields[0].Descriptor()
	// trustkey.DefaultID holds the default value on creation for the id field.
	trustkey.DefaultID = trustkeyDescID.Default.(func() uuid.UUID)
}
