// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/IanShaw027/sub2api-plugin-market/ent/plugin"
	"github.com/IanShaw027/sub2api-plugin-market/ent/pluginversion"
	"github.com/IanShaw027/sub2api-plugin-market/ent/predicate"
	"github.com/IanShaw027/sub2api-plugin-market/ent/submission"
	"github.com/google/uuid"
)

// SubmissionUpdate is the builder for updating Submission entities.
type SubmissionUpdate struct {
	config
	hooks    []Hook
	mutation *SubmissionMutation
}

// Where appends a list predicates to the SubmissionUpdate builder.
func (_u *SubmissionUpdate) Where(ps ...predicate.Submission) *SubmissionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPluginID sets the "plugin_id" field.
func (_u *SubmissionUpdate) SetPluginID(v uuid.UUID) *SubmissionUpdate {
	_u.mutation.SetPluginID(v)
	return _u
}

// SetNillablePluginID sets the "plugin_id" field if the given value is not nil.
func (_u *SubmissionUpdate) SetNillablePluginID(v *uuid.UUID) *SubmissionUpdate {
	if v != nil {
		_u.SetPluginID(*v)
	}
	return _u
}

// SetSubmissionType sets the "submission_type" field.
func (_u *SubmissionUpdate) SetSubmissionType(v submission.SubmissionType) *SubmissionUpdate {
	_u.mutation.SetSubmissionType(v)
	return _u
}

// SetNillableSubmissionType sets the "submission_type" field if the given value is not nil.
func (_u *SubmissionUpdate) SetNillableSubmissionType(v *submission.SubmissionType) *SubmissionUpdate {
	if v != nil {
		_u.SetSubmissionType(*v)
	}
	return _u
}

// SetSubmitterEmail sets the "submitter_email" field.
func (_u *SubmissionUpdate) SetSubmitterEmail(v string) *SubmissionUpdate {
	_u.mutation.SetSubmitterEmail(v)
	return _u
}

// SetNillableSubmitterEmail sets the "submitter_email" field if the given value is not nil.
func (_u *SubmissionUpdate) SetNillableSubmitterEmail(v *string) *SubmissionUpdate {
	if v != nil {
		_u.SetSubmitterEmail(*v)
	}
	return _u
}

// SetSubmitterName sets the "submitter_name" field.
func (_u *SubmissionUpdate) SetSubmitterName(v string) *SubmissionUpdate {
	_u.mutation.SetSubmitterName(v)
	return _u
}

// SetNillableSubmitterName sets the "submitter_name" field if the given value is not nil.
func (_u *SubmissionUpdate) SetNillableSubmitterName(v *string) *SubmissionUpdate {
	if v != nil {
		_u.SetSubmitterName(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *SubmissionUpdate) SetNotes(v string) *SubmissionUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *SubmissionUpdate) SetNillableNotes(v *string) *SubmissionUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *SubmissionUpdate) ClearNotes() *SubmissionUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetStatus sets the "status" field.
func (_u *SubmissionUpdate) SetStatus(v submission.Status) *SubmissionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SubmissionUpdate) SetNillableStatus(v *submission.Status) *SubmissionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetReviewerNotes sets the "reviewer_notes" field.
func (_u *SubmissionUpdate) SetReviewerNotes(v string) *SubmissionUpdate {
	_u.mutation.SetReviewerNotes(v)
	return _u
}

// SetNillableReviewerNotes sets the "reviewer_notes" field if the given value is not nil.
func (_u *SubmissionUpdate) SetNillableReviewerNotes(v *string) *SubmissionUpdate {
	if v != nil {
		_u.SetReviewerNotes(*v)
	}
	return _u
}

// ClearReviewerNotes clears the value of the "reviewer_notes" field.
func (_u *SubmissionUpdate) ClearReviewerNotes() *SubmissionUpdate {
	_u.mutation.ClearReviewerNotes()
	return _u
}

// SetReviewedBy sets the "reviewed_by" field.
func (_u *SubmissionUpdate) SetReviewedBy(v string) *SubmissionUpdate {
	_u.mutation.SetReviewedBy(v)
	return _u
}

// SetNillableReviewedBy sets the "reviewed_by" field if the given value is not nil.
func (_u *SubmissionUpdate) SetNillableReviewedBy(v *string) *SubmissionUpdate {
	if v != nil {
		_u.SetReviewedBy(*v)
	}
	return _u
}

// ClearReviewedBy clears the value of the "reviewed_by" field.
func (_u *SubmissionUpdate) ClearReviewedBy() *SubmissionUpdate {
	_u.mutation.ClearReviewedBy()
	return _u
}

// SetReviewedAt sets the "reviewed_at" field.
func (_u *SubmissionUpdate) SetReviewedAt(v time.Time) *SubmissionUpdate {
	_u.mutation.SetReviewedAt(v)
	return _u
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_u *SubmissionUpdate) SetNillableReviewedAt(v *time.Time) *SubmissionUpdate {
	if v != nil {
		_u.SetReviewedAt(*v)
	}
	return _u
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (_u *SubmissionUpdate) ClearReviewedAt() *SubmissionUpdate {
	_u.mutation.ClearReviewedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubmissionUpdate) SetUpdatedAt(v time.Time) *SubmissionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPlugin sets the "plugin" edge to the Plugin entity.
func (_u *SubmissionUpdate) SetPlugin(v *Plugin) *SubmissionUpdate {
	return _u.SetPluginID(v.ID)
}

// SetVersionID sets the "version" edge to the PluginVersion entity by ID.
func (_u *SubmissionUpdate) SetVersionID(id uuid.UUID) *SubmissionUpdate {
	_u.mutation.SetVersionID(id)
	return _u
}

// SetNillableVersionID sets the "version" edge to the PluginVersion entity by ID if the given value is not nil.
func (_u *SubmissionUpdate) SetNillableVersionID(id *uuid.UUID) *SubmissionUpdate {
	if id != nil {
		_u = _u.SetVersionID(*id)
	}
	return _u
}

// SetVersion sets the "version" edge to the PluginVersion entity.
func (_u *SubmissionUpdate) SetVersion(v *PluginVersion) *SubmissionUpdate {
	return _u.SetVersionID(v.ID)
}

// Mutation returns the SubmissionMutation object of the builder.
func (_u *SubmissionUpdate) Mutation() *SubmissionMutation {
	return _u.mutation
}

// ClearPlugin clears the "plugin" edge to the Plugin entity.
func (_u *SubmissionUpdate) ClearPlugin() *SubmissionUpdate {
	_u.mutation.ClearPlugin()
	return _u
}

// ClearVersion clears the "version" edge to the PluginVersion entity.
func (_u *SubmissionUpdate) ClearVersion() *SubmissionUpdate {
	_u.mutation.ClearVersion()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubmissionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubmissionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubmissionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubmissionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubmissionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := submission.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubmissionUpdate) check() error {
	if v, ok := _u.mutation.SubmissionType(); ok {
		if err := submission.SubmissionTypeValidator(v); err != nil {
			return &ValidationError{Name: "submission_type", err: fmt.Errorf(`ent: validator failed for field "Submission.submission_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SubmitterEmail(); ok {
		if err := submission.SubmitterEmailValidator(v); err != nil {
			return &ValidationError{Name: "submitter_email", err: fmt.Errorf(`ent: validator failed for field "Submission.submitter_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SubmitterName(); ok {
		if err := submission.SubmitterNameValidator(v); err != nil {
			return &ValidationError{Name: "submitter_name", err: fmt.Errorf(`ent: validator failed for field "Submission.submitter_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := submission.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Submission.status": %w`, err)}
		}
	}
	if _u.mutation.PluginCleared() && len(_u.mutation.PluginIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Submission.plugin"`)
	}
	return nil
}

func (_u *SubmissionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(submission.Table, submission.Columns, sqlgraph.NewFieldSpec(submission.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SubmissionType(); ok {
		_spec.SetField(submission.FieldSubmissionType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SubmitterEmail(); ok {
		_spec.SetField(submission.FieldSubmitterEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.SubmitterName(); ok {
		_spec.SetField(submission.FieldSubmitterName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(submission.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(submission.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(submission.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ReviewerNotes(); ok {
		_spec.SetField(submission.FieldReviewerNotes, field.TypeString, value)
	}
	if _u.mutation.ReviewerNotesCleared() {
		_spec.ClearField(submission.FieldReviewerNotes, field.TypeString)
	}
	if value, ok := _u.mutation.ReviewedBy(); ok {
		_spec.SetField(submission.FieldReviewedBy, field.TypeString, value)
	}
	if _u.mutation.ReviewedByCleared() {
		_spec.ClearField(submission.FieldReviewedBy, field.TypeString)
	}
	if value, ok := _u.mutation.ReviewedAt(); ok {
		_spec.SetField(submission.FieldReviewedAt, field.TypeTime, value)
	}
	if _u.mutation.ReviewedAtCleared() {
		_spec.ClearField(submission.FieldReviewedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(submission.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.PluginCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   submission.PluginTable,
			Columns: []string{submission.PluginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PluginIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   submission.PluginTable,
			Columns: []string{submission.PluginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VersionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   submission.VersionTable,
			Columns: []string{submission.VersionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pluginversion.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VersionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   submission.VersionTable,
			Columns: []string{submission.VersionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pluginversion.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{submission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubmissionUpdateOne is the builder for updating a single Submission entity.
type SubmissionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubmissionMutation
}

// SetPluginID sets the "plugin_id" field.
func (_u *SubmissionUpdateOne) SetPluginID(v uuid.UUID) *SubmissionUpdateOne {
	_u.mutation.SetPluginID(v)
	return _u
}

// SetNillablePluginID sets the "plugin_id" field if the given value is not nil.
func (_u *SubmissionUpdateOne) SetNillablePluginID(v *uuid.UUID) *SubmissionUpdateOne {
	if v != nil {
		_u.SetPluginID(*v)
	}
	return _u
}

// SetSubmissionType sets the "submission_type" field.
func (_u *SubmissionUpdateOne) SetSubmissionType(v submission.SubmissionType) *SubmissionUpdateOne {
	_u.mutation.SetSubmissionType(v)
	return _u
}

// SetNillableSubmissionType sets the "submission_type" field if the given value is not nil.
func (_u *SubmissionUpdateOne) SetNillableSubmissionType(v *submission.SubmissionType) *SubmissionUpdateOne {
	if v != nil {
		_u.SetSubmissionType(*v)
	}
	return _u
}

// SetSubmitterEmail sets the "submitter_email" field.
func (_u *SubmissionUpdateOne) SetSubmitterEmail(v string) *SubmissionUpdateOne {
	_u.mutation.SetSubmitterEmail(v)
	return _u
}

// SetNillableSubmitterEmail sets the "submitter_email" field if the given value is not nil.
func (_u *SubmissionUpdateOne) SetNillableSubmitterEmail(v *string) *SubmissionUpdateOne {
	if v != nil {
		_u.SetSubmitterEmail(*v)
	}
	return _u
}

// SetSubmitterName sets the "submitter_name" field.
func (_u *SubmissionUpdateOne) SetSubmitterName(v string) *SubmissionUpdateOne {
	_u.mutation.SetSubmitterName(v)
	return _u
}

// SetNillableSubmitterName sets the "submitter_name" field if the given value is not nil.
func (_u *SubmissionUpdateOne) SetNillableSubmitterName(v *string) *SubmissionUpdateOne {
	if v != nil {
		_u.SetSubmitterName(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *SubmissionUpdateOne) SetNotes(v string) *SubmissionUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *SubmissionUpdateOne) SetNillableNotes(v *string) *SubmissionUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *SubmissionUpdateOne) ClearNotes() *SubmissionUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetStatus sets the "status" field.
func (_u *SubmissionUpdateOne) SetStatus(v submission.Status) *SubmissionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SubmissionUpdateOne) SetNillableStatus(v *submission.Status) *SubmissionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetReviewerNotes sets the "reviewer_notes" field.
func (_u *SubmissionUpdateOne) SetReviewerNotes(v string) *SubmissionUpdateOne {
	_u.mutation.SetReviewerNotes(v)
	return _u
}

// SetNillableReviewerNotes sets the "reviewer_notes" field if the given value is not nil.
func (_u *SubmissionUpdateOne) SetNillableReviewerNotes(v *string) *SubmissionUpdateOne {
	if v != nil {
		_u.SetReviewerNotes(*v)
	}
	return _u
}

// ClearReviewerNotes clears the value of the "reviewer_notes" field.
func (_u *SubmissionUpdateOne) ClearReviewerNotes() *SubmissionUpdateOne {
	_u.mutation.ClearReviewerNotes()
	return _u
}

// SetReviewedBy sets the "reviewed_by" field.
func (_u *SubmissionUpdateOne) SetReviewedBy(v string) *SubmissionUpdateOne {
	_u.mutation.SetReviewedBy(v)
	return _u
}

// SetNillableReviewedBy sets the "reviewed_by" field if the given value is not nil.
func (_u *SubmissionUpdateOne) SetNillableReviewedBy(v *string) *SubmissionUpdateOne {
	if v != nil {
		_u.SetReviewedBy(*v)
	}
	return _u
}

// ClearReviewedBy clears the value of the "reviewed_by" field.
func (_u *SubmissionUpdateOne) ClearReviewedBy() *SubmissionUpdateOne {
	_u.mutation.ClearReviewedBy()
	return _u
}

// SetReviewedAt sets the "reviewed_at" field.
func (_u *SubmissionUpdateOne) SetReviewedAt(v time.Time) *SubmissionUpdateOne {
	_u.mutation.SetReviewedAt(v)
	return _u
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_u *SubmissionUpdateOne) SetNillableReviewedAt(v *time.Time) *SubmissionUpdateOne {
	if v != nil {
		_u.SetReviewedAt(*v)
	}
	return _u
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (_u *SubmissionUpdateOne) ClearReviewedAt() *SubmissionUpdateOne {
	_u.mutation.ClearReviewedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubmissionUpdateOne) SetUpdatedAt(v time.Time) *SubmissionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPlugin sets the "plugin" edge to the Plugin entity.
func (_u *SubmissionUpdateOne) SetPlugin(v *Plugin) *SubmissionUpdateOne {
	return _u.SetPluginID(v.ID)
}

// SetVersionID sets the "version" edge to the PluginVersion entity by ID.
func (_u *SubmissionUpdateOne) SetVersionID(id uuid.UUID) *SubmissionUpdateOne {
	_u.mutation.SetVersionID(id)
	return _u
}

// SetNillableVersionID sets the "version" edge to the PluginVersion entity by ID if the given value is not nil.
func (_u *SubmissionUpdateOne) SetNillableVersionID(id *uuid.UUID) *SubmissionUpdateOne {
	if id != nil {
		_u = _u.SetVersionID(*id)
	}
	return _u
}

// SetVersion sets the "version" edge to the PluginVersion entity.
func (_u *SubmissionUpdateOne) SetVersion(v *PluginVersion) *SubmissionUpdateOne {
	return _u.SetVersionID(v.ID)
}

// Mutation returns the SubmissionMutation object of the builder.
func (_u *SubmissionUpdateOne) Mutation() *SubmissionMutation {
	return _u.mutation
}

// ClearPlugin clears the "plugin" edge to the Plugin entity.
func (_u *SubmissionUpdateOne) ClearPlugin() *SubmissionUpdateOne {
	_u.mutation.ClearPlugin()
	return _u
}

// ClearVersion clears the "version" edge to the PluginVersion entity.
func (_u *SubmissionUpdateOne) ClearVersion() *SubmissionUpdateOne {
	_u.mutation.ClearVersion()
	return _u
}

// Where appends a list predicates to the SubmissionUpdate builder.
func (_u *SubmissionUpdateOne) Where(ps ...predicate.Submission) *SubmissionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubmissionUpdateOne) Select(field string, fields ...string) *SubmissionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Submission entity.
func (_u *SubmissionUpdateOne) Save(ctx context.Context) (*Submission, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubmissionUpdateOne) SaveX(ctx context.Context) *Submission {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubmissionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubmissionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubmissionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := submission.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubmissionUpdateOne) check() error {
	if v, ok := _u.mutation.SubmissionType(); ok {
		if err := submission.SubmissionTypeValidator(v); err != nil {
			return &ValidationError{Name: "submission_type", err: fmt.Errorf(`ent: validator failed for field "Submission.submission_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SubmitterEmail(); ok {
		if err := submission.SubmitterEmailValidator(v); err != nil {
			return &ValidationError{Name: "submitter_email", err: fmt.Errorf(`ent: validator failed for field "Submission.submitter_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SubmitterName(); ok {
		if err := submission.SubmitterNameValidator(v); err != nil {
			return &ValidationError{Name: "submitter_name", err: fmt.Errorf(`ent: validator failed for field "Submission.submitter_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := submission.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Submission.status": %w`, err)}
		}
	}
	if _u.mutation.PluginCleared() && len(_u.mutation.PluginIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Submission.plugin"`)
	}
	return nil
}

func (_u *SubmissionUpdateOne) sqlSave(ctx context.Context) (_node *Submission, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(submission.Table, submission.Columns, sqlgraph.NewFieldSpec(submission.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Submission.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, submission.FieldID)
		for _, f := range fields {
			if !submission.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != submission.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SubmissionType(); ok {
		_spec.SetField(submission.FieldSubmissionType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SubmitterEmail(); ok {
		_spec.SetField(submission.FieldSubmitterEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.SubmitterName(); ok {
		_spec.SetField(submission.FieldSubmitterName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(submission.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(submission.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(submission.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ReviewerNotes(); ok {
		_spec.SetField(submission.FieldReviewerNotes, field.TypeString, value)
	}
	if _u.mutation.ReviewerNotesCleared() {
		_spec.ClearField(submission.FieldReviewerNotes, field.TypeString)
	}
	if value, ok := _u.mutation.ReviewedBy(); ok {
		_spec.SetField(submission.FieldReviewedBy, field.TypeString, value)
	}
	if _u.mutation.ReviewedByCleared() {
		_spec.ClearField(submission.FieldReviewedBy, field.TypeString)
	}
	if value, ok := _u.mutation.ReviewedAt(); ok {
		_spec.SetField(submission.FieldReviewedAt, field.TypeTime, value)
	}
	if _u.mutation.ReviewedAtCleared() {
		_spec.ClearField(submission.FieldReviewedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(submission.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.PluginCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   submission.PluginTable,
			Columns: []string{submission.PluginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PluginIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   submission.PluginTable,
			Columns: []string{submission.PluginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VersionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   submission.VersionTable,
			Columns: []string{submission.VersionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pluginversion.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VersionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   submission.VersionTable,
			Columns: []string{submission.VersionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pluginversion.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Submission{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{submission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
