// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/IanShaw027/sub2api-plugin-market/ent/plugin"
	"github.com/IanShaw027/sub2api-plugin-market/ent/pluginversion"
	"github.com/IanShaw027/sub2api-plugin-market/ent/submission"
	"github.com/google/uuid"
)

// Submission is the model entity for the Submission schema.
type Submission struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// 关联的插件 ID
	PluginID uuid.UUID `json:"plugin_id,omitempty"`
	// 提交类型
	SubmissionType submission.SubmissionType `json:"submission_type,omitempty"`
	// 提交者邮箱
	SubmitterEmail string `json:"submitter_email,omitempty"`
	// 提交者姓名
	SubmitterName string `json:"submitter_name,omitempty"`
	// 提交说明
	Notes string `json:"notes,omitempty"`
	// 审核状态
	Status submission.Status `json:"status,omitempty"`
	// 审核意见
	ReviewerNotes string `json:"reviewer_notes,omitempty"`
	// 审核人
	ReviewedBy string `json:"reviewed_by,omitempty"`
	// 审核时间
	ReviewedAt time.Time `json:"reviewed_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SubmissionQuery when eager-loading is set.
	Edges        SubmissionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SubmissionEdges holds the relations/edges for other nodes in the graph.
type SubmissionEdges struct {
	// Plugin holds the value of the plugin edge.
	Plugin *Plugin `json:"plugin,omitempty"`
	// Version holds the value of the version edge.
	Version *PluginVersion `json:"version,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// PluginOrErr returns the Plugin value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubmissionEdges) PluginOrErr() (*Plugin, error) {
	if e.Plugin != nil {
		return e.Plugin, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: plugin.Label}
	}
	return nil, &NotLoadedError{edge: "plugin"}
}

// VersionOrErr returns the Version value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubmissionEdges) VersionOrErr() (*PluginVersion, error) {
	if e.Version != nil {
		return e.Version, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: pluginversion.Label}
	}
	return nil, &NotLoadedError{edge: "version"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Submission) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case submission.FieldSubmissionType, submission.FieldSubmitterEmail, submission.FieldSubmitterName, submission.FieldNotes, submission.FieldStatus, submission.FieldReviewerNotes, submission.FieldReviewedBy:
			values[i] = new(sql.NullString)
		case submission.FieldReviewedAt, submission.FieldCreatedAt, submission.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case submission.FieldID, submission.FieldPluginID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Submission fields.
func (_m *Submission) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case submission.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case submission.FieldPluginID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field plugin_id", values[i])
			} else if value != nil {
				_m.PluginID = *value
			}
		case submission.FieldSubmissionType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field submission_type", values[i])
			} else if value.Valid {
				_m.SubmissionType = submission.SubmissionType(value.String)
			}
		case submission.FieldSubmitterEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field submitter_email", values[i])
			} else if value.Valid {
				_m.SubmitterEmail = value.String
			}
		case submission.FieldSubmitterName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field submitter_name", values[i])
			} else if value.Valid {
				_m.SubmitterName = value.String
			}
		case submission.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = value.String
			}
		case submission.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = submission.Status(value.String)
			}
		case submission.FieldReviewerNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reviewer_notes", values[i])
			} else if value.Valid {
				_m.ReviewerNotes = value.String
			}
		case submission.FieldReviewedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reviewed_by", values[i])
			} else if value.Valid {
				_m.ReviewedBy = value.String
			}
		case submission.FieldReviewedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field reviewed_at", values[i])
			} else if value.Valid {
				_m.ReviewedAt = value.Time
			}
		case submission.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case submission.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Submission.
// This includes values selected through modifiers, order, etc.
func (_m *Submission) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPlugin queries the "plugin" edge of the Submission entity.
func (_m *Submission) QueryPlugin() *PluginQuery {
	return NewSubmissionClient(_m.config).QueryPlugin(_m)
}

// QueryVersion queries the "version" edge of the Submission entity.
func (_m *Submission) QueryVersion() *PluginVersionQuery {
	return NewSubmissionClient(_m.config).QueryVersion(_m)
}

// Update returns a builder for updating this Submission.
// Note that you need to call Submission.Unwrap() before calling this method if this Submission
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Submission) Update() *SubmissionUpdateOne {
	return NewSubmissionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Submission entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Submission) Unwrap() *Submission {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Submission is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Submission) String() string {
	var builder strings.Builder
	builder.WriteString("Submission(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("plugin_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PluginID))
	builder.WriteString(", ")
	builder.WriteString("submission_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.SubmissionType))
	builder.WriteString(", ")
	builder.WriteString("submitter_email=")
	builder.WriteString(_m.SubmitterEmail)
	builder.WriteString(", ")
	builder.WriteString("submitter_name=")
	builder.WriteString(_m.SubmitterName)
	builder.WriteString(", ")
	builder.WriteString("notes=")
	builder.WriteString(_m.Notes)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("reviewer_notes=")
	builder.WriteString(_m.ReviewerNotes)
	builder.WriteString(", ")
	builder.WriteString("reviewed_by=")
	builder.WriteString(_m.ReviewedBy)
	builder.WriteString(", ")
	builder.WriteString("reviewed_at=")
	builder.WriteString(_m.ReviewedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Submissions is a parsable slice of Submission.
type Submissions []*Submission
