// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sub2api/plugin-market/ent/plugin"
	"github.com/sub2api/plugin-market/ent/pluginversion"
	"github.com/sub2api/plugin-market/ent/submission"
)

// SubmissionCreate is the builder for creating a Submission entity.
type SubmissionCreate struct {
	config
	mutation *SubmissionMutation
	hooks    []Hook
}

// SetPluginID sets the "plugin_id" field.
func (_c *SubmissionCreate) SetPluginID(v uuid.UUID) *SubmissionCreate {
	_c.mutation.SetPluginID(v)
	return _c
}

// SetSubmissionType sets the "submission_type" field.
func (_c *SubmissionCreate) SetSubmissionType(v submission.SubmissionType) *SubmissionCreate {
	_c.mutation.SetSubmissionType(v)
	return _c
}

// SetSubmitterEmail sets the "submitter_email" field.
func (_c *SubmissionCreate) SetSubmitterEmail(v string) *SubmissionCreate {
	_c.mutation.SetSubmitterEmail(v)
	return _c
}

// SetSubmitterName sets the "submitter_name" field.
func (_c *SubmissionCreate) SetSubmitterName(v string) *SubmissionCreate {
	_c.mutation.SetSubmitterName(v)
	return _c
}

// SetNotes sets the "notes" field.
func (_c *SubmissionCreate) SetNotes(v string) *SubmissionCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *SubmissionCreate) SetNillableNotes(v *string) *SubmissionCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *SubmissionCreate) SetStatus(v submission.Status) *SubmissionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SubmissionCreate) SetNillableStatus(v *submission.Status) *SubmissionCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetReviewerNotes sets the "reviewer_notes" field.
func (_c *SubmissionCreate) SetReviewerNotes(v string) *SubmissionCreate {
	_c.mutation.SetReviewerNotes(v)
	return _c
}

// SetNillableReviewerNotes sets the "reviewer_notes" field if the given value is not nil.
func (_c *SubmissionCreate) SetNillableReviewerNotes(v *string) *SubmissionCreate {
	if v != nil {
		_c.SetReviewerNotes(*v)
	}
	return _c
}

// SetReviewedBy sets the "reviewed_by" field.
func (_c *SubmissionCreate) SetReviewedBy(v string) *SubmissionCreate {
	_c.mutation.SetReviewedBy(v)
	return _c
}

// SetNillableReviewedBy sets the "reviewed_by" field if the given value is not nil.
func (_c *SubmissionCreate) SetNillableReviewedBy(v *string) *SubmissionCreate {
	if v != nil {
		_c.SetReviewedBy(*v)
	}
	return _c
}

// SetReviewedAt sets the "reviewed_at" field.
func (_c *SubmissionCreate) SetReviewedAt(v time.Time) *SubmissionCreate {
	_c.mutation.SetReviewedAt(v)
	return _c
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_c *SubmissionCreate) SetNillableReviewedAt(v *time.Time) *SubmissionCreate {
	if v != nil {
		_c.SetReviewedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SubmissionCreate) SetCreatedAt(v time.Time) *SubmissionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SubmissionCreate) SetNillableCreatedAt(v *time.Time) *SubmissionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SubmissionCreate) SetUpdatedAt(v time.Time) *SubmissionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SubmissionCreate) SetNillableUpdatedAt(v *time.Time) *SubmissionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SubmissionCreate) SetID(v uuid.UUID) *SubmissionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *SubmissionCreate) SetNillableID(v *uuid.UUID) *SubmissionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetPlugin sets the "plugin" edge to the Plugin entity.
func (_c *SubmissionCreate) SetPlugin(v *Plugin) *SubmissionCreate {
	return _c.SetPluginID(v.ID)
}

// SetVersionID sets the "version" edge to the PluginVersion entity by ID.
func (_c *SubmissionCreate) SetVersionID(id uuid.UUID) *SubmissionCreate {
	_c.mutation.SetVersionID(id)
	return _c
}

// SetNillableVersionID sets the "version" edge to the PluginVersion entity by ID if the given value is not nil.
func (_c *SubmissionCreate) SetNillableVersionID(id *uuid.UUID) *SubmissionCreate {
	if id != nil {
		_c = _c.SetVersionID(*id)
	}
	return _c
}

// SetVersion sets the "version" edge to the PluginVersion entity.
func (_c *SubmissionCreate) SetVersion(v *PluginVersion) *SubmissionCreate {
	return _c.SetVersionID(v.ID)
}

// Mutation returns the SubmissionMutation object of the builder.
func (_c *SubmissionCreate) Mutation() *SubmissionMutation {
	return _c.mutation
}

// Save creates the Submission in the database.
func (_c *SubmissionCreate) Save(ctx context.Context) (*Submission, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SubmissionCreate) SaveX(ctx context.Context) *Submission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubmissionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubmissionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SubmissionCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := submission.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := submission.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := submission.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := submission.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SubmissionCreate) check() error {
	if _, ok := _c.mutation.PluginID(); !ok {
		return &ValidationError{Name: "plugin_id", err: errors.New(`ent: missing required field "Submission.plugin_id"`)}
	}
	if _, ok := _c.mutation.SubmissionType(); !ok {
		return &ValidationError{Name: "submission_type", err: errors.New(`ent: missing required field "Submission.submission_type"`)}
	}
	if v, ok := _c.mutation.SubmissionType(); ok {
		if err := submission.SubmissionTypeValidator(v); err != nil {
			return &ValidationError{Name: "submission_type", err: fmt.Errorf(`ent: validator failed for field "Submission.submission_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SubmitterEmail(); !ok {
		return &ValidationError{Name: "submitter_email", err: errors.New(`ent: missing required field "Submission.submitter_email"`)}
	}
	if v, ok := _c.mutation.SubmitterEmail(); ok {
		if err := submission.SubmitterEmailValidator(v); err != nil {
			return &ValidationError{Name: "submitter_email", err: fmt.Errorf(`ent: validator failed for field "Submission.submitter_email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SubmitterName(); !ok {
		return &ValidationError{Name: "submitter_name", err: errors.New(`ent: missing required field "Submission.submitter_name"`)}
	}
	if v, ok := _c.mutation.SubmitterName(); ok {
		if err := submission.SubmitterNameValidator(v); err != nil {
			return &ValidationError{Name: "submitter_name", err: fmt.Errorf(`ent: validator failed for field "Submission.submitter_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Submission.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := submission.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Submission.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Submission.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Submission.updated_at"`)}
	}
	if len(_c.mutation.PluginIDs()) == 0 {
		return &ValidationError{Name: "plugin", err: errors.New(`ent: missing required edge "Submission.plugin"`)}
	}
	return nil
}

func (_c *SubmissionCreate) sqlSave(ctx context.Context) (*Submission, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SubmissionCreate) createSpec() (*Submission, *sqlgraph.CreateSpec) {
	var (
		_node = &Submission{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(submission.Table, sqlgraph.NewFieldSpec(submission.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.SubmissionType(); ok {
		_spec.SetField(submission.FieldSubmissionType, field.TypeEnum, value)
		_node.SubmissionType = value
	}
	if value, ok := _c.mutation.SubmitterEmail(); ok {
		_spec.SetField(submission.FieldSubmitterEmail, field.TypeString, value)
		_node.SubmitterEmail = value
	}
	if value, ok := _c.mutation.SubmitterName(); ok {
		_spec.SetField(submission.FieldSubmitterName, field.TypeString, value)
		_node.SubmitterName = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(submission.FieldNotes, field.TypeString, value)
		_node.Notes = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(submission.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ReviewerNotes(); ok {
		_spec.SetField(submission.FieldReviewerNotes, field.TypeString, value)
		_node.ReviewerNotes = value
	}
	if value, ok := _c.mutation.ReviewedBy(); ok {
		_spec.SetField(submission.FieldReviewedBy, field.TypeString, value)
		_node.ReviewedBy = value
	}
	if value, ok := _c.mutation.ReviewedAt(); ok {
		_spec.SetField(submission.FieldReviewedAt, field.TypeTime, value)
		_node.ReviewedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(submission.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(submission.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.PluginIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   submission.PluginTable,
			Columns: []string{submission.PluginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PluginID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.VersionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   submission.VersionTable,
			Columns: []string{submission.VersionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pluginversion.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SubmissionCreateBulk is the builder for creating many Submission entities in bulk.
type SubmissionCreateBulk struct {
	config
	err      error
	builders []*SubmissionCreate
}

// Save creates the Submission entities in the database.
func (_c *SubmissionCreateBulk) Save(ctx context.Context) ([]*Submission, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Submission, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SubmissionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SubmissionCreateBulk) SaveX(ctx context.Context) []*Submission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubmissionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubmissionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
