// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/IanShaw027/sub2api-plugin-market/ent/plugin"
	"github.com/IanShaw027/sub2api-plugin-market/ent/predicate"
	"github.com/IanShaw027/sub2api-plugin-market/ent/syncjob"
	"github.com/google/uuid"
)

// SyncJobUpdate is the builder for updating SyncJob entities.
type SyncJobUpdate struct {
	config
	hooks    []Hook
	mutation *SyncJobMutation
}

// Where appends a list predicates to the SyncJobUpdate builder.
func (_u *SyncJobUpdate) Where(ps ...predicate.SyncJob) *SyncJobUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPluginID sets the "plugin_id" field.
func (_u *SyncJobUpdate) SetPluginID(v uuid.UUID) *SyncJobUpdate {
	_u.mutation.SetPluginID(v)
	return _u
}

// SetNillablePluginID sets the "plugin_id" field if the given value is not nil.
func (_u *SyncJobUpdate) SetNillablePluginID(v *uuid.UUID) *SyncJobUpdate {
	if v != nil {
		_u.SetPluginID(*v)
	}
	return _u
}

// SetTriggerType sets the "trigger_type" field.
func (_u *SyncJobUpdate) SetTriggerType(v syncjob.TriggerType) *SyncJobUpdate {
	_u.mutation.SetTriggerType(v)
	return _u
}

// SetNillableTriggerType sets the "trigger_type" field if the given value is not nil.
func (_u *SyncJobUpdate) SetNillableTriggerType(v *syncjob.TriggerType) *SyncJobUpdate {
	if v != nil {
		_u.SetTriggerType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SyncJobUpdate) SetStatus(v syncjob.Status) *SyncJobUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SyncJobUpdate) SetNillableStatus(v *syncjob.Status) *SyncJobUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTargetRef sets the "target_ref" field.
func (_u *SyncJobUpdate) SetTargetRef(v string) *SyncJobUpdate {
	_u.mutation.SetTargetRef(v)
	return _u
}

// SetNillableTargetRef sets the "target_ref" field if the given value is not nil.
func (_u *SyncJobUpdate) SetNillableTargetRef(v *string) *SyncJobUpdate {
	if v != nil {
		_u.SetTargetRef(*v)
	}
	return _u
}

// ClearTargetRef clears the value of the "target_ref" field.
func (_u *SyncJobUpdate) ClearTargetRef() *SyncJobUpdate {
	_u.mutation.ClearTargetRef()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *SyncJobUpdate) SetErrorMessage(v string) *SyncJobUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *SyncJobUpdate) SetNillableErrorMessage(v *string) *SyncJobUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *SyncJobUpdate) ClearErrorMessage() *SyncJobUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *SyncJobUpdate) SetStartedAt(v time.Time) *SyncJobUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *SyncJobUpdate) SetNillableStartedAt(v *time.Time) *SyncJobUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *SyncJobUpdate) ClearStartedAt() *SyncJobUpdate {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *SyncJobUpdate) SetFinishedAt(v time.Time) *SyncJobUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *SyncJobUpdate) SetNillableFinishedAt(v *time.Time) *SyncJobUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *SyncJobUpdate) ClearFinishedAt() *SyncJobUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SyncJobUpdate) SetUpdatedAt(v time.Time) *SyncJobUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPlugin sets the "plugin" edge to the Plugin entity.
func (_u *SyncJobUpdate) SetPlugin(v *Plugin) *SyncJobUpdate {
	return _u.SetPluginID(v.ID)
}

// Mutation returns the SyncJobMutation object of the builder.
func (_u *SyncJobUpdate) Mutation() *SyncJobMutation {
	return _u.mutation
}

// ClearPlugin clears the "plugin" edge to the Plugin entity.
func (_u *SyncJobUpdate) ClearPlugin() *SyncJobUpdate {
	_u.mutation.ClearPlugin()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SyncJobUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SyncJobUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SyncJobUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SyncJobUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SyncJobUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := syncjob.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SyncJobUpdate) check() error {
	if v, ok := _u.mutation.TriggerType(); ok {
		if err := syncjob.TriggerTypeValidator(v); err != nil {
			return &ValidationError{Name: "trigger_type", err: fmt.Errorf(`ent: validator failed for field "SyncJob.trigger_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := syncjob.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SyncJob.status": %w`, err)}
		}
	}
	if _u.mutation.PluginCleared() && len(_u.mutation.PluginIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SyncJob.plugin"`)
	}
	return nil
}

func (_u *SyncJobUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(syncjob.Table, syncjob.Columns, sqlgraph.NewFieldSpec(syncjob.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TriggerType(); ok {
		_spec.SetField(syncjob.FieldTriggerType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(syncjob.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TargetRef(); ok {
		_spec.SetField(syncjob.FieldTargetRef, field.TypeString, value)
	}
	if _u.mutation.TargetRefCleared() {
		_spec.ClearField(syncjob.FieldTargetRef, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(syncjob.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(syncjob.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(syncjob.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(syncjob.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(syncjob.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(syncjob.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(syncjob.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.PluginCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   syncjob.PluginTable,
			Columns: []string{syncjob.PluginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PluginIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   syncjob.PluginTable,
			Columns: []string{syncjob.PluginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{syncjob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SyncJobUpdateOne is the builder for updating a single SyncJob entity.
type SyncJobUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SyncJobMutation
}

// SetPluginID sets the "plugin_id" field.
func (_u *SyncJobUpdateOne) SetPluginID(v uuid.UUID) *SyncJobUpdateOne {
	_u.mutation.SetPluginID(v)
	return _u
}

// SetNillablePluginID sets the "plugin_id" field if the given value is not nil.
func (_u *SyncJobUpdateOne) SetNillablePluginID(v *uuid.UUID) *SyncJobUpdateOne {
	if v != nil {
		_u.SetPluginID(*v)
	}
	return _u
}

// SetTriggerType sets the "trigger_type" field.
func (_u *SyncJobUpdateOne) SetTriggerType(v syncjob.TriggerType) *SyncJobUpdateOne {
	_u.mutation.SetTriggerType(v)
	return _u
}

// SetNillableTriggerType sets the "trigger_type" field if the given value is not nil.
func (_u *SyncJobUpdateOne) SetNillableTriggerType(v *syncjob.TriggerType) *SyncJobUpdateOne {
	if v != nil {
		_u.SetTriggerType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SyncJobUpdateOne) SetStatus(v syncjob.Status) *SyncJobUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SyncJobUpdateOne) SetNillableStatus(v *syncjob.Status) *SyncJobUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTargetRef sets the "target_ref" field.
func (_u *SyncJobUpdateOne) SetTargetRef(v string) *SyncJobUpdateOne {
	_u.mutation.SetTargetRef(v)
	return _u
}

// SetNillableTargetRef sets the "target_ref" field if the given value is not nil.
func (_u *SyncJobUpdateOne) SetNillableTargetRef(v *string) *SyncJobUpdateOne {
	if v != nil {
		_u.SetTargetRef(*v)
	}
	return _u
}

// ClearTargetRef clears the value of the "target_ref" field.
func (_u *SyncJobUpdateOne) ClearTargetRef() *SyncJobUpdateOne {
	_u.mutation.ClearTargetRef()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *SyncJobUpdateOne) SetErrorMessage(v string) *SyncJobUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *SyncJobUpdateOne) SetNillableErrorMessage(v *string) *SyncJobUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *SyncJobUpdateOne) ClearErrorMessage() *SyncJobUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *SyncJobUpdateOne) SetStartedAt(v time.Time) *SyncJobUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *SyncJobUpdateOne) SetNillableStartedAt(v *time.Time) *SyncJobUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *SyncJobUpdateOne) ClearStartedAt() *SyncJobUpdateOne {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *SyncJobUpdateOne) SetFinishedAt(v time.Time) *SyncJobUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *SyncJobUpdateOne) SetNillableFinishedAt(v *time.Time) *SyncJobUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *SyncJobUpdateOne) ClearFinishedAt() *SyncJobUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SyncJobUpdateOne) SetUpdatedAt(v time.Time) *SyncJobUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPlugin sets the "plugin" edge to the Plugin entity.
func (_u *SyncJobUpdateOne) SetPlugin(v *Plugin) *SyncJobUpdateOne {
	return _u.SetPluginID(v.ID)
}

// Mutation returns the SyncJobMutation object of the builder.
func (_u *SyncJobUpdateOne) Mutation() *SyncJobMutation {
	return _u.mutation
}

// ClearPlugin clears the "plugin" edge to the Plugin entity.
func (_u *SyncJobUpdateOne) ClearPlugin() *SyncJobUpdateOne {
	_u.mutation.ClearPlugin()
	return _u
}

// Where appends a list predicates to the SyncJobUpdate builder.
func (_u *SyncJobUpdateOne) Where(ps ...predicate.SyncJob) *SyncJobUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SyncJobUpdateOne) Select(field string, fields ...string) *SyncJobUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SyncJob entity.
func (_u *SyncJobUpdateOne) Save(ctx context.Context) (*SyncJob, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SyncJobUpdateOne) SaveX(ctx context.Context) *SyncJob {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SyncJobUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SyncJobUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SyncJobUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := syncjob.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SyncJobUpdateOne) check() error {
	if v, ok := _u.mutation.TriggerType(); ok {
		if err := syncjob.TriggerTypeValidator(v); err != nil {
			return &ValidationError{Name: "trigger_type", err: fmt.Errorf(`ent: validator failed for field "SyncJob.trigger_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := syncjob.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SyncJob.status": %w`, err)}
		}
	}
	if _u.mutation.PluginCleared() && len(_u.mutation.PluginIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SyncJob.plugin"`)
	}
	return nil
}

func (_u *SyncJobUpdateOne) sqlSave(ctx context.Context) (_node *SyncJob, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(syncjob.Table, syncjob.Columns, sqlgraph.NewFieldSpec(syncjob.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SyncJob.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, syncjob.FieldID)
		for _, f := range fields {
			if !syncjob.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != syncjob.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TriggerType(); ok {
		_spec.SetField(syncjob.FieldTriggerType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(syncjob.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TargetRef(); ok {
		_spec.SetField(syncjob.FieldTargetRef, field.TypeString, value)
	}
	if _u.mutation.TargetRefCleared() {
		_spec.ClearField(syncjob.FieldTargetRef, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(syncjob.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(syncjob.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(syncjob.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(syncjob.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(syncjob.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(syncjob.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(syncjob.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.PluginCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   syncjob.PluginTable,
			Columns: []string{syncjob.PluginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PluginIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   syncjob.PluginTable,
			Columns: []string{syncjob.PluginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SyncJob{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{syncjob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
