// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/IanShaw027/sub2api-plugin-market/ent/plugin"
	"github.com/IanShaw027/sub2api-plugin-market/ent/syncjob"
	"github.com/google/uuid"
)

// SyncJobCreate is the builder for creating a SyncJob entity.
type SyncJobCreate struct {
	config
	mutation *SyncJobMutation
	hooks    []Hook
}

// SetPluginID sets the "plugin_id" field.
func (_c *SyncJobCreate) SetPluginID(v uuid.UUID) *SyncJobCreate {
	_c.mutation.SetPluginID(v)
	return _c
}

// SetTriggerType sets the "trigger_type" field.
func (_c *SyncJobCreate) SetTriggerType(v syncjob.TriggerType) *SyncJobCreate {
	_c.mutation.SetTriggerType(v)
	return _c
}

// SetNillableTriggerType sets the "trigger_type" field if the given value is not nil.
func (_c *SyncJobCreate) SetNillableTriggerType(v *syncjob.TriggerType) *SyncJobCreate {
	if v != nil {
		_c.SetTriggerType(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *SyncJobCreate) SetStatus(v syncjob.Status) *SyncJobCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SyncJobCreate) SetNillableStatus(v *syncjob.Status) *SyncJobCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetTargetRef sets the "target_ref" field.
func (_c *SyncJobCreate) SetTargetRef(v string) *SyncJobCreate {
	_c.mutation.SetTargetRef(v)
	return _c
}

// SetNillableTargetRef sets the "target_ref" field if the given value is not nil.
func (_c *SyncJobCreate) SetNillableTargetRef(v *string) *SyncJobCreate {
	if v != nil {
		_c.SetTargetRef(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *SyncJobCreate) SetErrorMessage(v string) *SyncJobCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *SyncJobCreate) SetNillableErrorMessage(v *string) *SyncJobCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *SyncJobCreate) SetStartedAt(v time.Time) *SyncJobCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *SyncJobCreate) SetNillableStartedAt(v *time.Time) *SyncJobCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetFinishedAt sets the "finished_at" field.
func (_c *SyncJobCreate) SetFinishedAt(v time.Time) *SyncJobCreate {
	_c.mutation.SetFinishedAt(v)
	return _c
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_c *SyncJobCreate) SetNillableFinishedAt(v *time.Time) *SyncJobCreate {
	if v != nil {
		_c.SetFinishedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SyncJobCreate) SetCreatedAt(v time.Time) *SyncJobCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SyncJobCreate) SetNillableCreatedAt(v *time.Time) *SyncJobCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SyncJobCreate) SetUpdatedAt(v time.Time) *SyncJobCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SyncJobCreate) SetNillableUpdatedAt(v *time.Time) *SyncJobCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SyncJobCreate) SetID(v uuid.UUID) *SyncJobCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *SyncJobCreate) SetNillableID(v *uuid.UUID) *SyncJobCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetPlugin sets the "plugin" edge to the Plugin entity.
func (_c *SyncJobCreate) SetPlugin(v *Plugin) *SyncJobCreate {
	return _c.SetPluginID(v.ID)
}

// Mutation returns the SyncJobMutation object of the builder.
func (_c *SyncJobCreate) Mutation() *SyncJobMutation {
	return _c.mutation
}

// Save creates the SyncJob in the database.
func (_c *SyncJobCreate) Save(ctx context.Context) (*SyncJob, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SyncJobCreate) SaveX(ctx context.Context) *SyncJob {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SyncJobCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SyncJobCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SyncJobCreate) defaults() {
	if _, ok := _c.mutation.TriggerType(); !ok {
		v := syncjob.DefaultTriggerType
		_c.mutation.SetTriggerType(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := syncjob.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := syncjob.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := syncjob.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := syncjob.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SyncJobCreate) check() error {
	if _, ok := _c.mutation.PluginID(); !ok {
		return &ValidationError{Name: "plugin_id", err: errors.New(`ent: missing required field "SyncJob.plugin_id"`)}
	}
	if _, ok := _c.mutation.TriggerType(); !ok {
		return &ValidationError{Name: "trigger_type", err: errors.New(`ent: missing required field "SyncJob.trigger_type"`)}
	}
	if v, ok := _c.mutation.TriggerType(); ok {
		if err := syncjob.TriggerTypeValidator(v); err != nil {
			return &ValidationError{Name: "trigger_type", err: fmt.Errorf(`ent: validator failed for field "SyncJob.trigger_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "SyncJob.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := syncjob.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SyncJob.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SyncJob.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SyncJob.updated_at"`)}
	}
	if len(_c.mutation.PluginIDs()) == 0 {
		return &ValidationError{Name: "plugin", err: errors.New(`ent: missing required edge "SyncJob.plugin"`)}
	}
	return nil
}

func (_c *SyncJobCreate) sqlSave(ctx context.Context) (*SyncJob, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SyncJobCreate) createSpec() (*SyncJob, *sqlgraph.CreateSpec) {
	var (
		_node = &SyncJob{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(syncjob.Table, sqlgraph.NewFieldSpec(syncjob.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.TriggerType(); ok {
		_spec.SetField(syncjob.FieldTriggerType, field.TypeEnum, value)
		_node.TriggerType = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(syncjob.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.TargetRef(); ok {
		_spec.SetField(syncjob.FieldTargetRef, field.TypeString, value)
		_node.TargetRef = value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(syncjob.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(syncjob.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = value
	}
	if value, ok := _c.mutation.FinishedAt(); ok {
		_spec.SetField(syncjob.FieldFinishedAt, field.TypeTime, value)
		_node.FinishedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(syncjob.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(syncjob.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.PluginIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   syncjob.PluginTable,
			Columns: []string{syncjob.PluginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PluginID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SyncJobCreateBulk is the builder for creating many SyncJob entities in bulk.
type SyncJobCreateBulk struct {
	config
	err      error
	builders []*SyncJobCreate
}

// Save creates the SyncJob entities in the database.
func (_c *SyncJobCreateBulk) Save(ctx context.Context) ([]*SyncJob, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SyncJob, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SyncJobMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SyncJobCreateBulk) SaveX(ctx context.Context) []*SyncJob {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SyncJobCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SyncJobCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
