// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/IanShaw027/sub2api-plugin-market/ent/plugin"
	"github.com/IanShaw027/sub2api-plugin-market/ent/syncjob"
	"github.com/google/uuid"
)

// SyncJob is the model entity for the SyncJob schema.
type SyncJob struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// 关联的插件 ID
	PluginID uuid.UUID `json:"plugin_id,omitempty"`
	// 触发类型
	TriggerType syncjob.TriggerType `json:"trigger_type,omitempty"`
	// 同步任务状态
	Status syncjob.Status `json:"status,omitempty"`
	// 目标引用，如分支或标签
	TargetRef string `json:"target_ref,omitempty"`
	// 错误信息
	ErrorMessage string `json:"error_message,omitempty"`
	// 开始时间
	StartedAt time.Time `json:"started_at,omitempty"`
	// 结束时间
	FinishedAt time.Time `json:"finished_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SyncJobQuery when eager-loading is set.
	Edges        SyncJobEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SyncJobEdges holds the relations/edges for other nodes in the graph.
type SyncJobEdges struct {
	// Plugin holds the value of the plugin edge.
	Plugin *Plugin `json:"plugin,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PluginOrErr returns the Plugin value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SyncJobEdges) PluginOrErr() (*Plugin, error) {
	if e.Plugin != nil {
		return e.Plugin, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: plugin.Label}
	}
	return nil, &NotLoadedError{edge: "plugin"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SyncJob) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case syncjob.FieldTriggerType, syncjob.FieldStatus, syncjob.FieldTargetRef, syncjob.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case syncjob.FieldStartedAt, syncjob.FieldFinishedAt, syncjob.FieldCreatedAt, syncjob.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case syncjob.FieldID, syncjob.FieldPluginID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SyncJob fields.
func (_m *SyncJob) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case syncjob.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case syncjob.FieldPluginID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field plugin_id", values[i])
			} else if value != nil {
				_m.PluginID = *value
			}
		case syncjob.FieldTriggerType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trigger_type", values[i])
			} else if value.Valid {
				_m.TriggerType = syncjob.TriggerType(value.String)
			}
		case syncjob.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = syncjob.Status(value.String)
			}
		case syncjob.FieldTargetRef:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_ref", values[i])
			} else if value.Valid {
				_m.TargetRef = value.String
			}
		case syncjob.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = value.String
			}
		case syncjob.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = value.Time
			}
		case syncjob.FieldFinishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field finished_at", values[i])
			} else if value.Valid {
				_m.FinishedAt = value.Time
			}
		case syncjob.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case syncjob.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SyncJob.
// This includes values selected through modifiers, order, etc.
func (_m *SyncJob) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPlugin queries the "plugin" edge of the SyncJob entity.
func (_m *SyncJob) QueryPlugin() *PluginQuery {
	return NewSyncJobClient(_m.config).QueryPlugin(_m)
}

// Update returns a builder for updating this SyncJob.
// Note that you need to call SyncJob.Unwrap() before calling this method if this SyncJob
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SyncJob) Update() *SyncJobUpdateOne {
	return NewSyncJobClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SyncJob entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SyncJob) Unwrap() *SyncJob {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SyncJob is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SyncJob) String() string {
	var builder strings.Builder
	builder.WriteString("SyncJob(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("plugin_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PluginID))
	builder.WriteString(", ")
	builder.WriteString("trigger_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.TriggerType))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("target_ref=")
	builder.WriteString(_m.TargetRef)
	builder.WriteString(", ")
	builder.WriteString("error_message=")
	builder.WriteString(_m.ErrorMessage)
	builder.WriteString(", ")
	builder.WriteString("started_at=")
	builder.WriteString(_m.StartedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("finished_at=")
	builder.WriteString(_m.FinishedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SyncJobs is a parsable slice of SyncJob.
type SyncJobs []*SyncJob
