// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/sub2api/plugin-market/ent/trustkey"
)

// TrustKey is the model entity for the TrustKey schema.
type TrustKey struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// 密钥短标识符
	KeyID string `json:"key_id,omitempty"`
	// Ed25519 公钥（base64 编码）
	PublicKey string `json:"public_key,omitempty"`
	// 密钥类型
	KeyType trustkey.KeyType `json:"key_type,omitempty"`
	// 所有者姓名
	OwnerName string `json:"owner_name,omitempty"`
	// 所有者邮箱
	OwnerEmail string `json:"owner_email,omitempty"`
	// 密钥描述
	Description string `json:"description,omitempty"`
	// 是否激活
	IsActive bool `json:"is_active,omitempty"`
	// 过期时间
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TrustKey) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case trustkey.FieldIsActive:
			values[i] = new(sql.NullBool)
		case trustkey.FieldKeyID, trustkey.FieldPublicKey, trustkey.FieldKeyType, trustkey.FieldOwnerName, trustkey.FieldOwnerEmail, trustkey.FieldDescription:
			values[i] = new(sql.NullString)
		case trustkey.FieldExpiresAt, trustkey.FieldCreatedAt, trustkey.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case trustkey.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TrustKey fields.
func (_m *TrustKey) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case trustkey.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case trustkey.FieldKeyID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key_id", values[i])
			} else if value.Valid {
				_m.KeyID = value.String
			}
		case trustkey.FieldPublicKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field public_key", values[i])
			} else if value.Valid {
				_m.PublicKey = value.String
			}
		case trustkey.FieldKeyType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key_type", values[i])
			} else if value.Valid {
				_m.KeyType = trustkey.KeyType(value.String)
			}
		case trustkey.FieldOwnerName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field owner_name", values[i])
			} else if value.Valid {
				_m.OwnerName = value.String
			}
		case trustkey.FieldOwnerEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field owner_email", values[i])
			} else if value.Valid {
				_m.OwnerEmail = value.String
			}
		case trustkey.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case trustkey.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		case trustkey.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case trustkey.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case trustkey.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TrustKey.
// This includes values selected through modifiers, order, etc.
func (_m *TrustKey) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this TrustKey.
// Note that you need to call TrustKey.Unwrap() before calling this method if this TrustKey
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TrustKey) Update() *TrustKeyUpdateOne {
	return NewTrustKeyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TrustKey entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TrustKey) Unwrap() *TrustKey {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TrustKey is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TrustKey) String() string {
	var builder strings.Builder
	builder.WriteString("TrustKey(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("key_id=")
	builder.WriteString(_m.KeyID)
	builder.WriteString(", ")
	builder.WriteString("public_key=")
	builder.WriteString(_m.PublicKey)
	builder.WriteString(", ")
	builder.WriteString("key_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.KeyType))
	builder.WriteString(", ")
	builder.WriteString("owner_name=")
	builder.WriteString(_m.OwnerName)
	builder.WriteString(", ")
	builder.WriteString("owner_email=")
	builder.WriteString(_m.OwnerEmail)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TrustKeys is a parsable slice of TrustKey.
type TrustKeys []*TrustKey
