// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/IanShaw027/sub2api-plugin-market/ent/trustkey"
)

// TrustKeyCreate is the builder for creating a TrustKey entity.
type TrustKeyCreate struct {
	config
	mutation *TrustKeyMutation
	hooks    []Hook
}

// SetKeyID sets the "key_id" field.
func (_c *TrustKeyCreate) SetKeyID(v string) *TrustKeyCreate {
	_c.mutation.SetKeyID(v)
	return _c
}

// SetPublicKey sets the "public_key" field.
func (_c *TrustKeyCreate) SetPublicKey(v string) *TrustKeyCreate {
	_c.mutation.SetPublicKey(v)
	return _c
}

// SetKeyType sets the "key_type" field.
func (_c *TrustKeyCreate) SetKeyType(v trustkey.KeyType) *TrustKeyCreate {
	_c.mutation.SetKeyType(v)
	return _c
}

// SetNillableKeyType sets the "key_type" field if the given value is not nil.
func (_c *TrustKeyCreate) SetNillableKeyType(v *trustkey.KeyType) *TrustKeyCreate {
	if v != nil {
		_c.SetKeyType(*v)
	}
	return _c
}

// SetOwnerName sets the "owner_name" field.
func (_c *TrustKeyCreate) SetOwnerName(v string) *TrustKeyCreate {
	_c.mutation.SetOwnerName(v)
	return _c
}

// SetOwnerEmail sets the "owner_email" field.
func (_c *TrustKeyCreate) SetOwnerEmail(v string) *TrustKeyCreate {
	_c.mutation.SetOwnerEmail(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *TrustKeyCreate) SetDescription(v string) *TrustKeyCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *TrustKeyCreate) SetNillableDescription(v *string) *TrustKeyCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *TrustKeyCreate) SetIsActive(v bool) *TrustKeyCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *TrustKeyCreate) SetNillableIsActive(v *bool) *TrustKeyCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *TrustKeyCreate) SetExpiresAt(v time.Time) *TrustKeyCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *TrustKeyCreate) SetNillableExpiresAt(v *time.Time) *TrustKeyCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TrustKeyCreate) SetCreatedAt(v time.Time) *TrustKeyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TrustKeyCreate) SetNillableCreatedAt(v *time.Time) *TrustKeyCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TrustKeyCreate) SetUpdatedAt(v time.Time) *TrustKeyCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TrustKeyCreate) SetNillableUpdatedAt(v *time.Time) *TrustKeyCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TrustKeyCreate) SetID(v uuid.UUID) *TrustKeyCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *TrustKeyCreate) SetNillableID(v *uuid.UUID) *TrustKeyCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the TrustKeyMutation object of the builder.
func (_c *TrustKeyCreate) Mutation() *TrustKeyMutation {
	return _c.mutation
}

// Save creates the TrustKey in the database.
func (_c *TrustKeyCreate) Save(ctx context.Context) (*TrustKey, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TrustKeyCreate) SaveX(ctx context.Context) *TrustKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TrustKeyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TrustKeyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TrustKeyCreate) defaults() {
	if _, ok := _c.mutation.KeyType(); !ok {
		v := trustkey.DefaultKeyType
		_c.mutation.SetKeyType(v)
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		v := trustkey.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := trustkey.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := trustkey.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := trustkey.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TrustKeyCreate) check() error {
	if _, ok := _c.mutation.KeyID(); !ok {
		return &ValidationError{Name: "key_id", err: errors.New(`ent: missing required field "TrustKey.key_id"`)}
	}
	if v, ok := _c.mutation.KeyID(); ok {
		if err := trustkey.KeyIDValidator(v); err != nil {
			return &ValidationError{Name: "key_id", err: fmt.Errorf(`ent: validator failed for field "TrustKey.key_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PublicKey(); !ok {
		return &ValidationError{Name: "public_key", err: errors.New(`ent: missing required field "TrustKey.public_key"`)}
	}
	if v, ok := _c.mutation.PublicKey(); ok {
		if err := trustkey.PublicKeyValidator(v); err != nil {
			return &ValidationError{Name: "public_key", err: fmt.Errorf(`ent: validator failed for field "TrustKey.public_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.KeyType(); !ok {
		return &ValidationError{Name: "key_type", err: errors.New(`ent: missing required field "TrustKey.key_type"`)}
	}
	if v, ok := _c.mutation.KeyType(); ok {
		if err := trustkey.KeyTypeValidator(v); err != nil {
			return &ValidationError{Name: "key_type", err: fmt.Errorf(`ent: validator failed for field "TrustKey.key_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OwnerName(); !ok {
		return &ValidationError{Name: "owner_name", err: errors.New(`ent: missing required field "TrustKey.owner_name"`)}
	}
	if v, ok := _c.mutation.OwnerName(); ok {
		if err := trustkey.OwnerNameValidator(v); err != nil {
			return &ValidationError{Name: "owner_name", err: fmt.Errorf(`ent: validator failed for field "TrustKey.owner_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OwnerEmail(); !ok {
		return &ValidationError{Name: "owner_email", err: errors.New(`ent: missing required field "TrustKey.owner_email"`)}
	}
	if v, ok := _c.mutation.OwnerEmail(); ok {
		if err := trustkey.OwnerEmailValidator(v); err != nil {
			return &ValidationError{Name: "owner_email", err: fmt.Errorf(`ent: validator failed for field "TrustKey.owner_email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "TrustKey.is_active"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TrustKey.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "TrustKey.updated_at"`)}
	}
	return nil
}

func (_c *TrustKeyCreate) sqlSave(ctx context.Context) (*TrustKey, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TrustKeyCreate) createSpec() (*TrustKey, *sqlgraph.CreateSpec) {
	var (
		_node = &TrustKey{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(trustkey.Table, sqlgraph.NewFieldSpec(trustkey.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.KeyID(); ok {
		_spec.SetField(trustkey.FieldKeyID, field.TypeString, value)
		_node.KeyID = value
	}
	if value, ok := _c.mutation.PublicKey(); ok {
		_spec.SetField(trustkey.FieldPublicKey, field.TypeString, value)
		_node.PublicKey = value
	}
	if value, ok := _c.mutation.KeyType(); ok {
		_spec.SetField(trustkey.FieldKeyType, field.TypeEnum, value)
		_node.KeyType = value
	}
	if value, ok := _c.mutation.OwnerName(); ok {
		_spec.SetField(trustkey.FieldOwnerName, field.TypeString, value)
		_node.OwnerName = value
	}
	if value, ok := _c.mutation.OwnerEmail(); ok {
		_spec.SetField(trustkey.FieldOwnerEmail, field.TypeString, value)
		_node.OwnerEmail = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(trustkey.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(trustkey.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(trustkey.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(trustkey.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(trustkey.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// TrustKeyCreateBulk is the builder for creating many TrustKey entities in bulk.
type TrustKeyCreateBulk struct {
	config
	err      error
	builders []*TrustKeyCreate
}

// Save creates the TrustKey entities in the database.
func (_c *TrustKeyCreateBulk) Save(ctx context.Context) ([]*TrustKey, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TrustKey, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TrustKeyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TrustKeyCreateBulk) SaveX(ctx context.Context) []*TrustKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TrustKeyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TrustKeyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
