// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/IanShaw027/sub2api-plugin-market/ent/predicate"
	"github.com/IanShaw027/sub2api-plugin-market/ent/trustkey"
)

// TrustKeyUpdate is the builder for updating TrustKey entities.
type TrustKeyUpdate struct {
	config
	hooks    []Hook
	mutation *TrustKeyMutation
}

// Where appends a list predicates to the TrustKeyUpdate builder.
func (_u *TrustKeyUpdate) Where(ps ...predicate.TrustKey) *TrustKeyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetKeyID sets the "key_id" field.
func (_u *TrustKeyUpdate) SetKeyID(v string) *TrustKeyUpdate {
	_u.mutation.SetKeyID(v)
	return _u
}

// SetNillableKeyID sets the "key_id" field if the given value is not nil.
func (_u *TrustKeyUpdate) SetNillableKeyID(v *string) *TrustKeyUpdate {
	if v != nil {
		_u.SetKeyID(*v)
	}
	return _u
}

// SetPublicKey sets the "public_key" field.
func (_u *TrustKeyUpdate) SetPublicKey(v string) *TrustKeyUpdate {
	_u.mutation.SetPublicKey(v)
	return _u
}

// SetNillablePublicKey sets the "public_key" field if the given value is not nil.
func (_u *TrustKeyUpdate) SetNillablePublicKey(v *string) *TrustKeyUpdate {
	if v != nil {
		_u.SetPublicKey(*v)
	}
	return _u
}

// SetKeyType sets the "key_type" field.
func (_u *TrustKeyUpdate) SetKeyType(v trustkey.KeyType) *TrustKeyUpdate {
	_u.mutation.SetKeyType(v)
	return _u
}

// SetNillableKeyType sets the "key_type" field if the given value is not nil.
func (_u *TrustKeyUpdate) SetNillableKeyType(v *trustkey.KeyType) *TrustKeyUpdate {
	if v != nil {
		_u.SetKeyType(*v)
	}
	return _u
}

// SetOwnerName sets the "owner_name" field.
func (_u *TrustKeyUpdate) SetOwnerName(v string) *TrustKeyUpdate {
	_u.mutation.SetOwnerName(v)
	return _u
}

// SetNillableOwnerName sets the "owner_name" field if the given value is not nil.
func (_u *TrustKeyUpdate) SetNillableOwnerName(v *string) *TrustKeyUpdate {
	if v != nil {
		_u.SetOwnerName(*v)
	}
	return _u
}

// SetOwnerEmail sets the "owner_email" field.
func (_u *TrustKeyUpdate) SetOwnerEmail(v string) *TrustKeyUpdate {
	_u.mutation.SetOwnerEmail(v)
	return _u
}

// SetNillableOwnerEmail sets the "owner_email" field if the given value is not nil.
func (_u *TrustKeyUpdate) SetNillableOwnerEmail(v *string) *TrustKeyUpdate {
	if v != nil {
		_u.SetOwnerEmail(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TrustKeyUpdate) SetDescription(v string) *TrustKeyUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TrustKeyUpdate) SetNillableDescription(v *string) *TrustKeyUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TrustKeyUpdate) ClearDescription() *TrustKeyUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *TrustKeyUpdate) SetIsActive(v bool) *TrustKeyUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *TrustKeyUpdate) SetNillableIsActive(v *bool) *TrustKeyUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *TrustKeyUpdate) SetExpiresAt(v time.Time) *TrustKeyUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *TrustKeyUpdate) SetNillableExpiresAt(v *time.Time) *TrustKeyUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *TrustKeyUpdate) ClearExpiresAt() *TrustKeyUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TrustKeyUpdate) SetUpdatedAt(v time.Time) *TrustKeyUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the TrustKeyMutation object of the builder.
func (_u *TrustKeyUpdate) Mutation() *TrustKeyMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TrustKeyUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TrustKeyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TrustKeyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TrustKeyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TrustKeyUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := trustkey.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TrustKeyUpdate) check() error {
	if v, ok := _u.mutation.KeyID(); ok {
		if err := trustkey.KeyIDValidator(v); err != nil {
			return &ValidationError{Name: "key_id", err: fmt.Errorf(`ent: validator failed for field "TrustKey.key_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PublicKey(); ok {
		if err := trustkey.PublicKeyValidator(v); err != nil {
			return &ValidationError{Name: "public_key", err: fmt.Errorf(`ent: validator failed for field "TrustKey.public_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.KeyType(); ok {
		if err := trustkey.KeyTypeValidator(v); err != nil {
			return &ValidationError{Name: "key_type", err: fmt.Errorf(`ent: validator failed for field "TrustKey.key_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OwnerName(); ok {
		if err := trustkey.OwnerNameValidator(v); err != nil {
			return &ValidationError{Name: "owner_name", err: fmt.Errorf(`ent: validator failed for field "TrustKey.owner_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OwnerEmail(); ok {
		if err := trustkey.OwnerEmailValidator(v); err != nil {
			return &ValidationError{Name: "owner_email", err: fmt.Errorf(`ent: validator failed for field "TrustKey.owner_email": %w`, err)}
		}
	}
	return nil
}

func (_u *TrustKeyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(trustkey.Table, trustkey.Columns, sqlgraph.NewFieldSpec(trustkey.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.KeyID(); ok {
		_spec.SetField(trustkey.FieldKeyID, field.TypeString, value)
	}
	if value, ok := _u.mutation.PublicKey(); ok {
		_spec.SetField(trustkey.FieldPublicKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.KeyType(); ok {
		_spec.SetField(trustkey.FieldKeyType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.OwnerName(); ok {
		_spec.SetField(trustkey.FieldOwnerName, field.TypeString, value)
	}
	if value, ok := _u.mutation.OwnerEmail(); ok {
		_spec.SetField(trustkey.FieldOwnerEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(trustkey.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(trustkey.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(trustkey.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(trustkey.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(trustkey.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(trustkey.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{trustkey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TrustKeyUpdateOne is the builder for updating a single TrustKey entity.
type TrustKeyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TrustKeyMutation
}

// SetKeyID sets the "key_id" field.
func (_u *TrustKeyUpdateOne) SetKeyID(v string) *TrustKeyUpdateOne {
	_u.mutation.SetKeyID(v)
	return _u
}

// SetNillableKeyID sets the "key_id" field if the given value is not nil.
func (_u *TrustKeyUpdateOne) SetNillableKeyID(v *string) *TrustKeyUpdateOne {
	if v != nil {
		_u.SetKeyID(*v)
	}
	return _u
}

// SetPublicKey sets the "public_key" field.
func (_u *TrustKeyUpdateOne) SetPublicKey(v string) *TrustKeyUpdateOne {
	_u.mutation.SetPublicKey(v)
	return _u
}

// SetNillablePublicKey sets the "public_key" field if the given value is not nil.
func (_u *TrustKeyUpdateOne) SetNillablePublicKey(v *string) *TrustKeyUpdateOne {
	if v != nil {
		_u.SetPublicKey(*v)
	}
	return _u
}

// SetKeyType sets the "key_type" field.
func (_u *TrustKeyUpdateOne) SetKeyType(v trustkey.KeyType) *TrustKeyUpdateOne {
	_u.mutation.SetKeyType(v)
	return _u
}

// SetNillableKeyType sets the "key_type" field if the given value is not nil.
func (_u *TrustKeyUpdateOne) SetNillableKeyType(v *trustkey.KeyType) *TrustKeyUpdateOne {
	if v != nil {
		_u.SetKeyType(*v)
	}
	return _u
}

// SetOwnerName sets the "owner_name" field.
func (_u *TrustKeyUpdateOne) SetOwnerName(v string) *TrustKeyUpdateOne {
	_u.mutation.SetOwnerName(v)
	return _u
}

// SetNillableOwnerName sets the "owner_name" field if the given value is not nil.
func (_u *TrustKeyUpdateOne) SetNillableOwnerName(v *string) *TrustKeyUpdateOne {
	if v != nil {
		_u.SetOwnerName(*v)
	}
	return _u
}

// SetOwnerEmail sets the "owner_email" field.
func (_u *TrustKeyUpdateOne) SetOwnerEmail(v string) *TrustKeyUpdateOne {
	_u.mutation.SetOwnerEmail(v)
	return _u
}

// SetNillableOwnerEmail sets the "owner_email" field if the given value is not nil.
func (_u *TrustKeyUpdateOne) SetNillableOwnerEmail(v *string) *TrustKeyUpdateOne {
	if v != nil {
		_u.SetOwnerEmail(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TrustKeyUpdateOne) SetDescription(v string) *TrustKeyUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TrustKeyUpdateOne) SetNillableDescription(v *string) *TrustKeyUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TrustKeyUpdateOne) ClearDescription() *TrustKeyUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *TrustKeyUpdateOne) SetIsActive(v bool) *TrustKeyUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *TrustKeyUpdateOne) SetNillableIsActive(v *bool) *TrustKeyUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *TrustKeyUpdateOne) SetExpiresAt(v time.Time) *TrustKeyUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *TrustKeyUpdateOne) SetNillableExpiresAt(v *time.Time) *TrustKeyUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *TrustKeyUpdateOne) ClearExpiresAt() *TrustKeyUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TrustKeyUpdateOne) SetUpdatedAt(v time.Time) *TrustKeyUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the TrustKeyMutation object of the builder.
func (_u *TrustKeyUpdateOne) Mutation() *TrustKeyMutation {
	return _u.mutation
}

// Where appends a list predicates to the TrustKeyUpdate builder.
func (_u *TrustKeyUpdateOne) Where(ps ...predicate.TrustKey) *TrustKeyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TrustKeyUpdateOne) Select(field string, fields ...string) *TrustKeyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TrustKey entity.
func (_u *TrustKeyUpdateOne) Save(ctx context.Context) (*TrustKey, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TrustKeyUpdateOne) SaveX(ctx context.Context) *TrustKey {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TrustKeyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TrustKeyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TrustKeyUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := trustkey.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TrustKeyUpdateOne) check() error {
	if v, ok := _u.mutation.KeyID(); ok {
		if err := trustkey.KeyIDValidator(v); err != nil {
			return &ValidationError{Name: "key_id", err: fmt.Errorf(`ent: validator failed for field "TrustKey.key_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PublicKey(); ok {
		if err := trustkey.PublicKeyValidator(v); err != nil {
			return &ValidationError{Name: "public_key", err: fmt.Errorf(`ent: validator failed for field "TrustKey.public_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.KeyType(); ok {
		if err := trustkey.KeyTypeValidator(v); err != nil {
			return &ValidationError{Name: "key_type", err: fmt.Errorf(`ent: validator failed for field "TrustKey.key_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OwnerName(); ok {
		if err := trustkey.OwnerNameValidator(v); err != nil {
			return &ValidationError{Name: "owner_name", err: fmt.Errorf(`ent: validator failed for field "TrustKey.owner_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OwnerEmail(); ok {
		if err := trustkey.OwnerEmailValidator(v); err != nil {
			return &ValidationError{Name: "owner_email", err: fmt.Errorf(`ent: validator failed for field "TrustKey.owner_email": %w`, err)}
		}
	}
	return nil
}

func (_u *TrustKeyUpdateOne) sqlSave(ctx context.Context) (_node *TrustKey, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(trustkey.Table, trustkey.Columns, sqlgraph.NewFieldSpec(trustkey.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TrustKey.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, trustkey.FieldID)
		for _, f := range fields {
			if !trustkey.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != trustkey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.KeyID(); ok {
		_spec.SetField(trustkey.FieldKeyID, field.TypeString, value)
	}
	if value, ok := _u.mutation.PublicKey(); ok {
		_spec.SetField(trustkey.FieldPublicKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.KeyType(); ok {
		_spec.SetField(trustkey.FieldKeyType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.OwnerName(); ok {
		_spec.SetField(trustkey.FieldOwnerName, field.TypeString, value)
	}
	if value, ok := _u.mutation.OwnerEmail(); ok {
		_spec.SetField(trustkey.FieldOwnerEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(trustkey.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(trustkey.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(trustkey.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(trustkey.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(trustkey.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(trustkey.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &TrustKey{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{trustkey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
