// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AdminUser is the predicate function for adminuser builders.
type AdminUser func(*sql.Selector)

// DownloadLog is the predicate function for downloadlog builders.
type DownloadLog func(*sql.Selector)

// Plugin is the predicate function for plugin builders.
type Plugin func(*sql.Selector)

// PluginVersion is the predicate function for pluginversion builders.
type PluginVersion func(*sql.Selector)

// Submission is the predicate function for submission builders.
type Submission func(*sql.Selector)

// TrustKey is the predicate function for trustkey builders.
type TrustKey func(*sql.Selector)
